import 'dotenv/config';
import {mkdir,readFile,writeFile} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {PrismaClient,Role,UserStatus} from '@prisma/client';import bcrypt from 'bcrypt';import crypto from 'node:crypto';
const prisma=new PrismaClient();const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');const source=path.join(root,'server','data','users.json');const reportDir=path.join(root,'backend','import-reports');
type Legacy={username?:string;email?:string;fullName?:string;phone?:string;role?:string;status?:string;protectedAccount?:boolean;createdAt?:string};
const roleMap:Record<string,Role>={Administrador:Role.ADMINISTRADOR,Notario:Role.NOTARIO,Secretaria:Role.SECRETARIA,Archivador:Role.ARCHIVADOR};
function status(value=''){if(value.startsWith('Activo'))return UserStatus.ACTIVO;if(value.startsWith('Inactivo'))return UserStatus.INACTIVO;if(value.startsWith('Bloqueado'))return UserStatus.BLOQUEADO;return UserStatus.PENDIENTE}
const records=JSON.parse(await readFile(source,'utf8')) as Legacy[];const report:{source:string;startedAt:string;items:unknown[]}={source,startedAt:new Date().toISOString(),items:[]};
for(const item of records){const username=(item.username??'').trim().toLowerCase();const email=(item.email??'').trim().toLowerCase();if(!username||!email||!roleMap[item.role??'']){report.items.push({username,email,result:'skipped',reason:'Datos o rol inválidos'});continue}const exists=await prisma.user.findFirst({where:{OR:[{username},{email}]}});if(exists){report.items.push({username,email,result:'skipped',reason:'Duplicado'});continue}const temporaryPassword=`${crypto.randomBytes(10).toString('base64url')}aA1!`;const user=await prisma.user.create({data:{username,email,fullName:item.fullName?.trim()||username,phone:item.phone||null,passwordHash:await bcrypt.hash(temporaryPassword,12),role:roleMap[item.role!]!,status:status(item.status),protectedAccount:Boolean(item.protectedAccount),passwordResetRequired:true,tempPasswordExpiresAt:new Date(Date.now()+24*3600000),createdAt:item.createdAt?new Date(item.createdAt):undefined}});report.items.push({username,email,userId:user.id,result:'imported',temporaryPassword,note:'Entregar por canal seguro y exigir cambio.'})}
await mkdir(reportDir,{recursive:true});const reportFile=path.join(reportDir,`users-${new Date().toISOString().replace(/[:.]/g,'-')}.json`);await writeFile(reportFile,JSON.stringify({...report,finishedAt:new Date().toISOString()},null,2));console.log(`Importación terminada. Informe local: ${reportFile}`);await prisma.$disconnect();

