import {apiRequest} from './apiClient';

type RawAudit={id:string;action:string;module:string;targetType:string|null;targetId:string|null;detail:string|null;result:'EXITOSO'|'ERROR'|'DENEGADO';createdAt:string;user:{username:string|null;email:string;fullName:string;role:'ADMINISTRADOR'|'NOTARIO'|'SECRETARIA'|'ARCHIVADOR'|'AUDITOR';status:'ACTIVO'|'INACTIVO'|'BLOQUEADO'|'PENDIENTE';deletedAt:string|null}|null};
const role:Record<NonNullable<RawAudit['user']>['role'],string>={ADMINISTRADOR:'Administrador',NOTARIO:'Notario',SECRETARIA:'Secretaria',ARCHIVADOR:'Archivador',AUDITOR:'Auditor'};
const actionLabels:Record<string,string>={LOGIN_SUCCESS:'Inicio de sesión exitoso',PROFILE_UPDATED:'Perfil actualizado',USER_SOFT_DELETED:'Usuario desactivado',LOGIN_FAILED:'Inicio de sesión fallido',LOGOUT:'Cierre de sesión',USER_UNBLOCKED:'Usuario desbloqueado',LOGIN_BLOCKED:'Acceso bloqueado',USER_BLOCKED:'Usuario bloqueado',USER_ACTIVATED:'Usuario activado',USER_APPROVED:'Cuenta aprobada',USER_REJECTED:'Cuenta rechazada',USER_CREATED:'Cuenta creada',USER_ROLE_REQUESTED:'Rol solicitado',USER_UPDATED:'Usuario actualizado',USER_DEACTIVATED:'Usuario desactivado',USER_ROLE_CHANGED:'Rol asignado',PASSWORD_RESET:'Contraseña restablecida',PASSWORD_CHANGED:'Contraseña actualizada',SESSION_REVOKED:'Sesión cerrada',OTHER_SESSIONS_REVOKED:'Otras sesiones cerradas',UNAUTHORIZED_ACCESS:'Acceso no autorizado'};

export function auditActionLabel(code:string){return actionLabels[code]??code.toLowerCase().split('_').map(word=>word.charAt(0).toUpperCase()+word.slice(1)).join(' ')}
export type CentralAuditRecord={id:string;date:string;time:string;username:string;userFullName:string;userStatus:string|null;userDeletedAt:string|null;role:string;actionCode:string;action:string;module:string;document:string;result:string};

export const auditApi={list:async()=>{const rows=await apiRequest<RawAudit[]>('/audit');return rows.map((row):CentralAuditRecord=>{const date=new Date(row.createdAt);return {id:row.id,date:date.toLocaleDateString('es-PE'),time:date.toLocaleTimeString('es-PE'),username:row.user?.email??'Sistema',userFullName:row.user?.fullName??'Sistema',userStatus:row.user?.status??null,userDeletedAt:row.user?.deletedAt??null,role:row.user?role[row.user.role]:'Sistema',actionCode:row.action,action:auditActionLabel(row.action),module:row.module,document:row.detail??row.targetId??'—',result:row.result==='EXITOSO'?'Exitoso':row.result==='DENEGADO'?'Denegado':'Error'}})},stats:()=>apiRequest<{activeUsers:number}>('/audit/stats')};


