/* eslint-disable no-useless-escape */
import {createWorker} from 'tesseract.js';import * as pdfjs from 'pdfjs-dist';import pdfWorkerUrl from 'pdfjs-dist/build/pdf.worker.min.mjs?url';import spaDataUrl from '@tesseract.js-data/spa/4.0.0_best_int/spa.traineddata.gz?url';import type {DocumentMode,DocumentRecord} from '../data/repository';
pdfjs.GlobalWorkerOptions.workerSrc=pdfWorkerUrl;
export type ExtractionKey='escritura'|'kardex'|'minuta'|'acto'|'contratantes'|'fecha'|'paginas'|'observaciones'|'fojaInicial'|'fojaFinal'|'ubicacion';
export type ExtractionField={key:ExtractionKey,label:string,value:string|string[],confidence:number,review:boolean};
export type OcrResult={fields:ExtractionField[],duplicate?:DocumentRecord,averageConfidence:number};
export const actualStages=['Archivo recibido','Validando PDF','Ejecutando OCR','Extrayendo número de escritura','Extrayendo kardex','Extrayendo número de minuta','Identificando acto jurídico','Detectando contratantes','Detectando fecha','Contando páginas','Buscando duplicados','Preparando validación'];
export const historicalStages=['Archivo recibido','Validando PDF','Ejecutando OCR','Extrayendo número de escritura','Extrayendo kardex','Extrayendo número de minuta','Identificando acto jurídico','Detectando contratantes','Detectando foja inicial y final','Detectando fecha, si existe','Contando páginas','Buscando duplicados','Preparando validación'];
type OcrOptions={mode:DocumentMode,bienio?:string,tomo:string,fojaInicial?:string,fojaFinal?:string,existing:DocumentRecord[],onStage:(index:number,progress?:number)=>void};
function match(text:string,patterns:RegExp[]){for(const pattern of patterns){const result=text.match(pattern);if(result?.[1])return result[1].trim()}return ''}
function field(key:ExtractionKey,label:string,value:string|string[],confidence:number):ExtractionField{const missing=Array.isArray(value)?value.length===0:!value;const score=missing?0:Math.max(1,Math.min(100,Math.round(confidence)));return {key,label,value:missing?(Array.isArray(value)?[]:''):value,confidence:score,review:missing||score<85}}
function detectContractors(text:string){const lines=text.split(/\n+/).map(line=>line.replace(/\s+/g,' ').trim()).filter(Boolean);const marker=lines.findIndex(line=>/comparecen|otorgantes|contratantes/i.test(line));const candidates=(marker>=0?lines.slice(marker+1,marker+14):lines).filter(line=>line.length>8&&line.length<120&&(/^[A-ZÁÉÍÓÚÑ][A-ZÁÉÍÓÚÑ\s,.&-]+$/.test(line)||/(S\.A\.|SAC|S\.R\.L\.|EIRL)/i.test(line)));return [...new Set(candidates)].slice(0,8)}
function extract(text:string,mode:DocumentMode,pages:number,confidence:number,bienio?:string,tomo?:string,configuredStart?:string,configuredEnd?:string){const escritura=match(text,[/(?:escritura(?:\s+pública)?(?:\s+(?:número|nro\.?|n[°]))?)\s*[:#-]?\s*(\d{2,})/i]);const kardex=match(text,[/kardex\s*[:#-]?\s*([A-Z0-9-]{3,})/i]);const minuta=match(text,[/minuta(?:\s+(?:número|nro\.?|n[°]))?\s*[:#-]?\s*([A-Z0-9-]{2,})/i]);const acts=['compraventa','poder notarial','testamento','escritura pública','sucesión intestada','constitución','donación','anticipo de legítima','hipoteca'];const acto=acts.find(value=>text.toLowerCase().includes(value))??'';const fecha=match(text,[/(\d{1,2}[\/.-]\d{1,2}[\/.-]\d{4})/,/(\d{1,2}\s+de\s+[a-záéíóú]+\s+de\s+\d{4})/i]);const detectedStart=match(text,[/(?:foja|fojas|folio)\s*(?:inicial|desde|n[°])?\s*[:#-]?\s*(\d{1,5})/i]);const detectedEnd=match(text,[/(?:hasta|foja\s+final)\s*[:#-]?\s*(\d{1,5})/i]);const observations=match(text,[/observaciones?\s*[:#-]\s*([^\n]{4,250})/i]);const base=Math.max(55,confidence);return [field('escritura','Número de escritura',escritura,base),field('kardex','Kardex',kardex,base),field('minuta','Número de minuta',minuta,base-4),field('acto','Acto jurídico',acto,acto?base-2:0),field('contratantes','Contratantes',detectContractors(text),base-8),...(mode==='historico'?[field('fojaInicial','Foja inicial',detectedStart||configuredStart||'',detectedStart?base:100),field('fojaFinal','Foja final',detectedEnd||configuredEnd||'',detectedEnd?base:100)]:[]),field('fecha','Fecha',fecha,base-3),field('paginas','Cantidad de páginas',String(pages),100),field('observaciones','Observaciones',observations,observations?base-8:0),...(mode==='historico'?[field('ubicacion','Ubicación histórica lógica',bienio&&tomo?`${bienio} · ${tomo} · Fojas ${detectedStart||configuredStart||'?'}-${detectedEnd||configuredEnd||'?'}`:'',100)]:[])]}
export async function processDocument(file:File,options:OcrOptions):Promise<OcrResult>{options.onStage(0,100);const bytes=new Uint8Array(await file.arrayBuffer());options.onStage(1,100);const pdf=await pdfjs.getDocument({data:bytes}).promise;let fullText='';for(let index=1;index<=pdf.numPages;index++){const page=await pdf.getPage(index);const content=await page.getTextContent();fullText+=content.items.map(item=>'str' in item?item.str:'').join(' ')+'\n'}let confidence=98;if(fullText.replace(/\s/g,'').length<80){const langPath=spaDataUrl.slice(0,spaDataUrl.lastIndexOf('/'));const worker=await createWorker('spa',undefined,{langPath,logger:message=>{if(message.status==='recognizing text')options.onStage(2,Math.round(message.progress*100))}});const limit=Math.min(pdf.numPages,12);const chunks:string[]=[];const scores:number[]=[];for(let index=1;index<=limit;index++){const page=await pdf.getPage(index);const viewport=page.getViewport({scale:1.6});const canvas=document.createElement('canvas');canvas.width=viewport.width;canvas.height=viewport.height;const context=canvas.getContext('2d');if(!context)continue;await page.render({canvas,canvasContext:context,viewport}).promise;const result=await worker.recognize(canvas);chunks.push(result.data.text);scores.push(result.data.confidence)}await worker.terminate();fullText=chunks.join('\n');confidence=scores.length?scores.reduce((sum,value)=>sum+value,0)/scores.length:0}else options.onStage(2,100);const stages=options.mode==='historico'?historicalStages:actualStages;for(let index=3;index<stages.length-2;index++)options.onStage(index,100);const fields=extract(fullText,options.mode,pdf.numPages,confidence,options.bienio,options.tomo,options.fojaInicial,options.fojaFinal);options.onStage(stages.length-2,100);const value=(key:ExtractionKey)=>fields.find(item=>item.key===key)?.value;const duplicate=options.existing.find(document=>{const escritura=value('escritura');const kardex=value('kardex');const minuta=value('minuta');return Boolean((escritura&&document.escritura===escritura)||(kardex&&document.kardex===kardex)||(minuta&&document.numeroMinuta===minuta))});options.onStage(stages.length-1,100);return {fields,duplicate,averageConfidence:Math.round(confidence)}}

