import type {DocumentRecord} from '../data/repository';

const base=(import.meta.env.VITE_API_URL as string|undefined)?.replace(/\/$/,'')??'/api';
type ApiDocument={id:string;displayName:string;originalFileName:string;filePath:string;storageName:string;fileHash:string;fileSize:number;mimeType:string;pageCount:number;documentMode:string;documentType:string;year?:number|null;biennium?:string|null;tomo:string;fojaInitial?:number|null;fojaFinal?:number|null;escritura?:string|null;kardex?:string|null;minuta?:string|null;actoJuridico?:string|null;documentDate?:string|null;observations?:string|null;ocrConfidence?:number|null;documentStatus:string;ocrStatus:string;isTestData?:boolean;createdAt:string;contractors:{name:string}[]};
const request=async<T>(path:string,options:RequestInit={})=>{const response=await fetch(`${base}${path}`,{...options,credentials:'include',headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...options.headers}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error((data as {error?:string}).error??'No fue posible completar la operación.');return data as T};
const numericId=(id:string)=>{let value=0;for(const char of id)value=(value*31+char.charCodeAt(0))>>>0;return value||1};
export function fromApi(row:ApiDocument):DocumentRecord{return {id:numericId(row.id),backendId:row.id,documentMode:row.documentMode as DocumentRecord['documentMode'],tipo:row.documentType,ano:row.year??undefined,bienio:row.biennium??undefined,tomo:row.tomo,fojaInicial:row.fojaInitial??undefined,fojaFinal:row.fojaFinal??undefined,numeroMinuta:row.minuta??'',actoJuridico:row.actoJuridico??'',kardex:row.kardex??'',escritura:row.escritura??'',contratantes:row.contractors.map(item=>item.name),observaciones:row.observations??'',fecha:row.documentDate??'',fechaRegistro:row.createdAt,cantidadPaginas:row.pageCount,ubicacionHistorica:row.biennium??undefined,documento:row.documentStatus,ocr:row.ocrStatus,confianza:row.ocrConfidence??undefined,fileName:row.originalFileName,fileSize:row.fileSize,file:new Blob([], {type:row.mimeType}),source:'manual',isTestData:row.isTestData}}
export async function listRemote(includeDeleted=false){const data=await request<{documents:ApiDocument[]}>(`/documents?includeDeleted=${includeDeleted}`);return data.documents.map(fromApi)}
export async function uploadTemporary(file:Blob,fileName:string){const form=new FormData();form.append('file',file,fileName);return request<{uploadId:string;jobId:string;pageCount:number;originalFileName:string;temporaryFileStored:boolean}>('/documents/upload',{method:'POST',body:form})}
export async function updateQuality(jobId:string,issues:Array<{pageNumber:number;issueType:string;severity:string;message:string;suggestedAction?:string}>,override=false){return request(`/documents/${jobId}/quality`,{method:'PATCH',body:JSON.stringify({issues,override})})}
export async function continueQuality(jobId:string){return request<{jobId:string;status:string;qualityOverrideAccepted:boolean}>(`/documents/${jobId}/quality/continue`,{method:'POST'})}
export async function cancelProcessing(jobId:string){return request(`/documents/${jobId}/cancel`,{method:'POST'})}
export async function deleteRemote(id:string,reason:string){return request(`/documents/${id}`,{method:'DELETE',body:JSON.stringify({reason})})}
export async function restoreRemote(id:string){return request(`/documents/${id}/restore`,{method:'POST'})}
export async function uploadAndConfirm(document:DocumentRecord){if(!(document.file instanceof Blob))throw new Error('No se recibió el PDF.');const uploadId=document.processingJobId??(await uploadTemporary(document.file,document.fileName)).uploadId;const ocrFields=(document as DocumentRecord & {ocrFields?:unknown}).ocrFields;const data=await request<{document:ApiDocument}>('/documents/'+uploadId+'/confirm',{method:'POST',body:JSON.stringify({displayName:document.fileName,originalFileName:document.fileName,documentMode:document.documentMode,documentType:document.tipo,year:document.ano,biennium:document.bienio,tomo:document.tomo,fojaInitial:document.fojaInicial,fojaFinal:document.fojaFinal,escritura:document.escritura,kardex:document.kardex,minuta:document.numeroMinuta,actoJuridico:document.actoJuridico,documentDate:document.fecha,observations:document.observaciones,ocrConfidence:document.confianza,documentStatus:document.documento,ocrStatus:document.ocr,contractors:document.contratantes,pageCount:document.cantidadPaginas,ocrFields})});return fromApi(data.document)}
export function remoteFileUrl(id:string){return `${base}/documents/${id}/file`}
export async function getRemote(id:string){const data=await request<{document:ApiDocument}>(`/documents/${id}`);return fromApi(data.document)}
