import type {DocumentRecord} from '../data/repository';
import {apiRequest,apiResponse} from './apiClient';

type ApiRelatedDocument={id:string;filename:string;displayName:string;documentClass:string;documentType:string;registryType?:string|null;instrumentNumber?:string|null;minuteNumber?:string|null;kardexNumber:string};
type ApiDocument={id:string;displayName:string;originalFileName:string;filePath:string;storageName:string;fileHash:string;fileSize:number;mimeType:string;pageCount:number;documentMode:string;documentType:string;year?:number|null;biennium?:string|null;bienniumStart?:number|null;bienniumEnd?:number|null;tomo:string;folioRangeStart?:number|null;folioRangeEnd?:number|null;printedFolio?:number|null;fojaInitial?:number|null;fojaFinal?:number|null;escritura?:string|null;kardex?:string|null;minuta?:string|null;actoJuridico?:string|null;documentDate?:string|null;observations?:string|null;ocrConfidence?:number|null;qrUrl?:string|null;qrRawValue?:string|null;qrPageNumber?:number|null;documentStatus:string;ocrStatus:string;isTestData?:boolean;createdAt:string;contractors:{name:string}[];kardexCaseId?:string|null;relationStatus?:string;relatedDocuments?:ApiRelatedDocument[];kardexCase?:{id:string;normalizedKardex:string;status:string;documents:Array<{id:string;displayName:string;documentType:string}>}|null};
const request=<T>(path:string,options:RequestInit={})=>apiRequest<T>(path,options);
const metadataUpdates=new Map<string,Promise<DocumentRecord>>();
const numericId=(id:string)=>{let value=0;for(const char of id)value=(value*31+char.charCodeAt(0))>>>0;return value||1};
export function fromApi(row:ApiDocument):DocumentRecord{const related=row.relatedDocuments?.map(item=>({id:numericId(item.id),backendId:item.id,tipo:item.documentType,fileName:item.filename,instrumentNumber:item.instrumentNumber??undefined,minuteNumber:item.minuteNumber??undefined,kardexNumber:item.kardexNumber}))??(row.kardexCase?.documents??[]).filter(item=>item.id!==row.id).map(item=>({id:numericId(item.id),backendId:item.id,tipo:item.documentType,fileName:item.displayName}));return {id:numericId(row.id),backendId:row.id,kardexCaseId:row.kardexCase?.id??row.kardexCaseId??undefined,normalizedKardex:row.kardexCase?.normalizedKardex,relationStatus:row.relationStatus??row.kardexCase?.status??'Kardex sin confirmar',relatedDocuments:related,documentMode:row.documentMode as DocumentRecord['documentMode'],tipo:row.documentType,ano:row.year??undefined,bienio:row.biennium??undefined,bienniumStart:row.bienniumStart??undefined,bienniumEnd:row.bienniumEnd??undefined,tomo:row.tomo,folioRangeStart:row.folioRangeStart??undefined,folioRangeEnd:row.folioRangeEnd??undefined,printedFolio:row.printedFolio??row.fojaInitial??undefined,fojaInicial:row.fojaInitial??undefined,fojaFinal:row.fojaFinal??undefined,numeroMinuta:row.minuta??'',actoJuridico:row.actoJuridico??'',kardex:row.kardex??'',escritura:row.escritura??'',contratantes:row.contractors.map(item=>item.name),observaciones:row.observations??'',fecha:row.documentDate??'',fechaRegistro:row.createdAt,cantidadPaginas:row.pageCount,ubicacionHistorica:row.biennium??undefined,documento:row.documentStatus,ocr:row.ocrStatus,confianza:row.ocrConfidence??undefined,qrUrl:row.qrUrl??undefined,qrRawValue:row.qrRawValue??undefined,qrPageNumber:row.qrPageNumber??undefined,fileName:row.displayName||row.originalFileName,fileSize:row.fileSize,file:new Blob([], {type:row.mimeType}),source:'manual',isTestData:row.isTestData}}
export async function listRemote(includeDeleted=false){const rows=new Map<string,ApiDocument>();const pageSize=100;for(let offset=0;;offset+=pageSize){const data=await request<{documents?:ApiDocument[];items?:ApiDocument[];total?:number}>(`/documents?includeDeleted=${includeDeleted}&limit=${pageSize}&offset=${offset}`);const page=data.items??data.documents??[];for(const row of page)rows.set(row.id,row);if(page.length<pageSize||rows.size>=(data.total??Number.MAX_SAFE_INTEGER))break}return [...rows.values()].map(fromApi)}
export async function uploadTemporary(file:Blob,fileName:string,importValidated=false){const form=new FormData();form.append('file',file,fileName);return request<{uploadId:string;jobId:string;pageCount:number;originalFileName:string;temporaryFileStored:boolean}>('/documents/upload',{method:'POST',headers:importValidated?{'x-import-validated':'true'}:undefined,body:form})}
export async function updateQuality(jobId:string,issues:Array<{pageNumber:number;issueType:string;severity:string;message:string;suggestedAction?:string}>,override=false){return request(`/documents/${jobId}/quality`,{method:'PATCH',body:JSON.stringify({issues,override})})}
export async function continueQuality(jobId:string){return request<{jobId:string;status:string;qualityOverrideAccepted:boolean}>(`/documents/${jobId}/quality/continue`,{method:'POST'})}
export async function cancelProcessing(jobId:string){return request(`/documents/${jobId}/cancel`,{method:'POST'})}
export async function deleteRemote(id:string,reason:string){return request(`/documents/${id}`,{method:'DELETE',body:JSON.stringify({reason})})}
export async function restoreRemote(id:string){return request(`/documents/${id}/restore`,{method:'POST'})}
export async function uploadAndConfirm(document:DocumentRecord){if(!(document.file instanceof Blob))throw new Error('No se recibió el PDF.');const uploadId=document.processingJobId??(await uploadTemporary(document.file,document.fileName)).uploadId;const ocrFields=(document as DocumentRecord & {ocrFields?:unknown}).ocrFields;const data=await request<{document:ApiDocument}>('/documents/'+uploadId+'/confirm',{method:'POST',body:JSON.stringify({displayName:document.fileName,originalFileName:document.fileName,documentMode:document.documentMode,documentType:document.tipo,year:document.ano,biennium:document.bienio,bienniumStart:document.bienniumStart,bienniumEnd:document.bienniumEnd,tomo:document.tomo,folioRangeStart:document.folioRangeStart,folioRangeEnd:document.folioRangeEnd,printedFolio:document.printedFolio,fojaInitial:document.fojaInicial,fojaFinal:document.fojaFinal,escritura:document.escritura,kardex:document.kardex,minuta:document.numeroMinuta,actoJuridico:document.actoJuridico,documentDate:document.fecha,observations:document.observaciones,ocrConfidence:document.confianza,qrUrl:document.qrUrl,documentStatus:document.documento,ocrStatus:document.ocr,contractors:document.contratantes,pageCount:document.cantidadPaginas,ocrFields})});return fromApi(data.document)}
export async function uploadImportAndConfirm(document:DocumentRecord){const uploaded=await uploadTemporary(document.file,document.fileName,true);return uploadAndConfirm({...document,processingJobId:uploaded.uploadId})}
export async function downloadRemote(id:string){
  const response=await apiResponse(`/documents/${id}/file`);
  try{
    const bytes=await response.arrayBuffer();
    return new Blob([bytes],{type:response.headers.get('content-type')??'application/pdf'});
  }catch(cause){
    const detail=cause instanceof Error?cause.message:'respuesta incompleta';
    throw new Error(`No se pudo recibir el PDF desde el servidor. Detalle: ${detail}`,{cause});
  }
}
export async function getRemote(id:string){const data=await request<{document:ApiDocument}>(`/documents/${id}`);return fromApi(data.document)}
export type DocumentMetadataPatch=Partial<{documentType:string;year:number|null;tomo:string;printedFolio:number|null;escritura:string;minuta:string;actoJuridico:string;kardex:string;contractors:string[];observations:string;qrUrl:string}>;
export async function updateRemoteMetadata(id:string,input:DocumentMetadataPatch){const active=metadataUpdates.get(id);if(active)return active;const operation=request<{document:ApiDocument}>(`/documents/${id}`,{method:'PATCH',body:JSON.stringify(input)}).then(data=>{const document=fromApi(data.document);window.dispatchEvent(new CustomEvent('boveda:documents-changed',{detail:{documentId:document.id}}));return document});metadataUpdates.set(id,operation);try{return await operation}finally{metadataUpdates.delete(id)}}
export async function updateTomeNumber(year:number,currentTome:string,newTome:string){const result=await request<{updated:number;message:string}>('/documents/tomes/number',{method:'PATCH',body:JSON.stringify({year,currentTome,newTome})});window.dispatchEvent(new CustomEvent('boveda:documents-changed'));return result}
export async function updateDocumentTypeGroup(year:number,tome:string,currentType:string,newType:string){const result=await request<{updated:number;message:string}>('/documents/types/name',{method:'PATCH',body:JSON.stringify({year,tome,currentType,newType})});window.dispatchEvent(new CustomEvent('boveda:documents-changed'));return result}
