import ExcelJS from 'exceljs';
import type {ExcelColumnProfile,ExcelSheetProfile,ExcelTargetField,ExcelWorkbookProfile,NormalizedExcelCell,NormalizedExcelRow} from '../domain/document-domain';
import {normalizeHeader,normalizeKardex,splitInstrument,suggestHeader} from './importAnalysis';

type CellValue=string|number|boolean|Date|null;
function apparent(value:unknown){if(value==null||value==='')return'EMPTY';if(value instanceof Date)return'DATE';return typeof value==='number'?'NUMBER':typeof value==='boolean'?'BOOLEAN':'TEXT'}
export async function readExcelFile(file:File):Promise<{profile:ExcelWorkbookProfile;rawSheets:Record<string,unknown[][]>}>{
  const bytes=await file.arrayBuffer();const workbook=new ExcelJS.Workbook();await workbook.xlsx.load(bytes);const sheets:ExcelSheetProfile[]=[];const rawSheets:Record<string,unknown[][]>={};
  workbook.eachSheet(worksheet=>{const matrix:unknown[][]=[];worksheet.eachRow({includeEmpty:true},row=>{const values=row.values as unknown[];matrix.push(Array.from({length:Math.max(0,worksheet.columnCount)},(_,index)=>plainCellValue(values[index+1])))});rawSheets[worksheet.name]=matrix;const headers=(matrix[0]??[]).map((value,index)=>String(value??`Columna ${index+1}`).trim()||`Columna ${index+1}`);const normalized=headers.map(normalizeHeader);const columns:ExcelColumnProfile[]=headers.map((header,index)=>({index,header,normalizedHeader:normalized[index],suggestedTarget:suggestHeader(header),target:suggestHeader(header),emptyCells:matrix.slice(1).filter(row=>row[index]==null||row[index]==='').length,duplicateHeader:normalized.filter(value=>value===normalized[index]).length>1,apparentTypes:[...new Set(matrix.slice(1,101).map(row=>apparent(row[index])))]}));sheets.push({name:worksheet.name,rowCount:Math.max(0,matrix.length-1),headers,columns,sampleRows:matrix.slice(1,6)})});
  const sheetNames=sheets.map(sheet=>sheet.name);return{profile:{fileName:file.name,sheetNames,selectedSheet:sheetNames[0]??'',sheets},rawSheets};
}
function plainCellValue(value:unknown):unknown{if(value==null||typeof value==='string'||typeof value==='number'||typeof value==='boolean'||value instanceof Date)return value;if(typeof value==='object'){const cell=value as {result?:unknown;text?:string;richText?:Array<{text:string}>;hyperlink?:string};if(cell.result!==undefined)return cell.result;if(cell.text!==undefined)return cell.text;if(cell.richText)return cell.richText.map(part=>part.text).join('');if(cell.hyperlink)return cell.hyperlink}return String(value)}
function normalizeCell(rawValue:unknown,rowNumber:number,columnName:string,target:ExcelTargetField):NormalizedExcelCell{
  const errors:string[]=[];let normalizedValue:CellValue=rawValue as CellValue;if(typeof rawValue==='string')normalizedValue=rawValue.trim().replace(/\s+/g,' ');if(target==='kardexNumber')normalizedValue=normalizeKardex(rawValue);if(target==='year'&&normalizedValue&&!/^(19|20)\d{2}$/.test(String(normalizedValue)))errors.push('Año inválido');if(target==='biennium'&&normalizedValue){const match=String(normalizedValue).replace(/[–—]/g,'-').match(/((?:19|20)\d{2})\s*-\s*((?:19|20)\d{2})/);normalizedValue=match?`${match[1]}-${match[2]}`:String(normalizedValue);if(!match)errors.push('Bienio inválido')}return{rawValue,normalizedValue:normalizedValue instanceof Date?normalizedValue.toISOString():normalizedValue,rowNumber,columnName,validationErrors:errors};
}
export function normalizeExcelRows(jobId:string,sheet:ExcelSheetProfile,matrix:unknown[][]){
  const rows:NormalizedExcelRow[]=[];matrix.slice(1).forEach((source,rowIndex)=>{const values:NormalizedExcelRow['values']={};sheet.columns.forEach(column=>{if(column.target==='IGNORE')return;const cell=normalizeCell(source[column.index],rowIndex+2,column.header,column.target);values[column.target]=cell;if(column.target==='instrumentType'){const split=splitInstrument(cell.normalizedValue);if(split.instrumentNumber){values.instrumentType={...cell,normalizedValue:split.instrumentType};values.instrumentNumber={...cell,normalizedValue:split.instrumentNumber}}}});rows.push({id:`${jobId}:${sheet.name}:${rowIndex+2}`,jobId,sheetName:sheet.name,rowNumber:rowIndex+2,values})});return rows;
}
