import type {ExcelWorkbookProfile,ImportJob,ImportValidationResult,InventoryFile,NormalizedExcelRow,ValidationMatchStatus} from '../domain/document-domain';

const DB_NAME='sigadn-imports';const DB_VERSION=2;
type StoredProfile={jobId:string;profile:ExcelWorkbookProfile};
function db(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const value=request.result;if(!value.objectStoreNames.contains('jobs'))value.createObjectStore('jobs',{keyPath:'id'});if(!value.objectStoreNames.contains('files')){const store=value.createObjectStore('files',{keyPath:'id'});store.createIndex('jobId','jobId');store.createIndex('jobStatus',['jobId','analysisStatus']);}if(!value.objectStoreNames.contains('excelRows')){const store=value.createObjectStore('excelRows',{keyPath:'id'});store.createIndex('jobId','jobId');}if(!value.objectStoreNames.contains('profiles'))value.createObjectStore('profiles',{keyPath:'jobId'});if(!value.objectStoreNames.contains('handles'))value.createObjectStore('handles',{keyPath:'jobId'});if(!value.objectStoreNames.contains('results')){const store=value.createObjectStore('results',{keyPath:'id'});store.createIndex('jobId','jobId');store.createIndex('jobStatus',['jobId','status']);}};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
function result<T>(request:IDBRequest<T>){return new Promise<T>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function putMany<T>(storeName:string,values:T[]){if(!values.length)return;const database=await db();await new Promise<void>((resolve,reject)=>{const transaction=database.transaction(storeName,'readwrite');const store=transaction.objectStore(storeName);values.forEach(value=>store.put(value));transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(transaction.error)})}
export async function saveImportJob(job:ImportJob){await putMany('jobs',[job])}
export async function getImportJob(id:string){const database=await db();return result(database.transaction('jobs','readonly').objectStore('jobs').get(id)) as Promise<ImportJob|undefined>}
export async function latestImportJob(){const database=await db();const jobs=await result(database.transaction('jobs','readonly').objectStore('jobs').getAll()) as ImportJob[];return jobs.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))[0]}
export async function saveInventoryFiles(files:InventoryFile[]){await putMany('files',files)}
async function cursorPage<T>(index:IDBIndex,query:IDBValidKey|IDBKeyRange,page:number,pageSize:number){const total=await result(index.count(query));const rows=await new Promise<T[]>((resolve,reject)=>{const output:T[]=[];const request=index.openCursor(query);let skipped=false;request.onsuccess=()=>{const cursor=request.result;if(!cursor||output.length>=pageSize){resolve(output);return}const offset=(page-1)*pageSize;if(!skipped&&offset){skipped=true;cursor.advance(offset);return}skipped=true;output.push(cursor.value as T);cursor.continue()};request.onerror=()=>reject(request.error)});return{total,rows}}
export async function inventoryPage(jobId:string,page:number,pageSize:number){const database=await db();return cursorPage<InventoryFile>(database.transaction('files','readonly').objectStore('files').index('jobId'),jobId,page,pageSize)}
export async function allInventoryFiles(jobId:string){const database=await db();return result(database.transaction('files','readonly').objectStore('files').index('jobId').getAll(jobId)) as Promise<InventoryFile[]>}
export async function saveExcelProfile(jobId:string,profile:ExcelWorkbookProfile){await putMany<StoredProfile>('profiles',[{jobId,profile}])}
export async function getExcelProfile(jobId:string){const database=await db();const stored=await result(database.transaction('profiles','readonly').objectStore('profiles').get(jobId)) as StoredProfile|undefined;return stored?.profile}
export async function saveDirectoryHandle(jobId:string,handle:unknown){await putMany('handles',[{jobId,handle}])}
export async function getDirectoryHandle<T>(jobId:string){const database=await db();const stored=await result(database.transaction('handles','readonly').objectStore('handles').get(jobId)) as {jobId:string;handle:T}|undefined;return stored?.handle}
export async function replaceExcelRows(jobId:string,rows:NormalizedExcelRow[]){const database=await db();await new Promise<void>((resolve,reject)=>{const transaction=database.transaction('excelRows','readwrite');const store=transaction.objectStore('excelRows');const index=store.index('jobId');const request=index.openCursor(IDBKeyRange.only(jobId));request.onsuccess=()=>{const cursor=request.result;if(cursor){cursor.delete();cursor.continue()}else rows.forEach(row=>store.put(row))};transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(transaction.error)})}
export async function allExcelRows(jobId:string){const database=await db();return result(database.transaction('excelRows','readonly').objectStore('excelRows').index('jobId').getAll(jobId)) as Promise<NormalizedExcelRow[]>}
export async function replaceValidationResults(jobId:string,rows:ImportValidationResult[]){const database=await db();await new Promise<void>((resolve,reject)=>{const transaction=database.transaction('results','readwrite');const store=transaction.objectStore('results');const request=store.index('jobId').openCursor(IDBKeyRange.only(jobId));request.onsuccess=()=>{const cursor=request.result;if(cursor){cursor.delete();cursor.continue()}else rows.forEach(row=>store.put(row))};transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(transaction.error)})}
export async function validationPage(jobId:string,status:ValidationMatchStatus|'ALL',page:number,pageSize:number){const database=await db();const store=database.transaction('results','readonly').objectStore('results');return status==='ALL'?cursorPage<ImportValidationResult>(store.index('jobId'),jobId,page,pageSize):cursorPage<ImportValidationResult>(store.index('jobStatus'),IDBKeyRange.only([jobId,status]),page,pageSize)}
export async function validationCounts(jobId:string){const database=await db();const transaction=database.transaction('results','readonly');const index=transaction.objectStore('results').index('jobStatus');const statuses:ValidationMatchStatus[]=['MATCHED','PARTIAL_MATCH','CONFLICT','NOT_FOUND_IN_EXCEL','DUPLICATE_IN_EXCEL','KARDEX_NOT_DETECTED'];const entries=await Promise.all(statuses.map(async status=>[status,await result(index.count(IDBKeyRange.only([jobId,status])))] as const));return Object.fromEntries(entries) as Record<ValidationMatchStatus,number>}
