import {apiRequest} from './apiClient';
import type {ReviewValues} from '../domain/document-domain';
export type OcrJobStartResponse={jobId:string;status:string};
export type OcrJobStatus={jobId:string;status:string;currentStage?:string;totalPages?:number;processedPages?:number;progress?:number;errorCode?:string;error?:string|null};
export type OcrField={fieldName:string;normalizedValue?:string;extractedValue?:string;confidence?:number;requiresReview?:boolean;pageNumber?:number;sourceText?:string};
export type OcrJobResults={documentClass?:string;documentLocation?:Record<string,unknown>;location?:Record<string,unknown>;pages:unknown[];fields:OcrField[];confirmedFields?:OcrField[];reviewFields?:OcrField[];reviewCount:number};
const aliases:Record<keyof Pick<ReviewValues,'kardexNumber'|'destinationRegistryTypeId'|'destinationInstrumentNumber'|'minuteNumber'|'printedFolio'|'documentDate'|'legalActId'|'primaryContractor'|'instrumentType'|'instrumentNumber'>,string[]>={
  kardexNumber:['kardexNumber','kardex','kardex_number'],destinationRegistryTypeId:['destinationRegistryType','destinationRegistryTypeId','registryType'],destinationInstrumentNumber:['destinationInstrumentNumber','instrumentNumber'],minuteNumber:['minuteNumber','minuta','minute'],printedFolio:['printedFolio','folio','foja'],documentDate:['documentDate','date','fecha'],legalActId:['legalAct','legalActId','actoJuridico'],primaryContractor:['primaryContractor','contractor','contratante'],instrumentType:['instrumentType','destinationInstrumentType'],instrumentNumber:['instrumentNumber','destinationInstrumentNumber'],
};
export const normalizeExtractedFieldName=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/gi,'').toLowerCase();
export const normalizeOcrFieldName=normalizeExtractedFieldName;
const normalizedAliases=Object.fromEntries(Object.entries(aliases).map(([target,names])=>[target,names.map(normalizeOcrFieldName)])) as typeof aliases;
const normalizeDate=(value:string)=>{const match=value.match(/^(\d{1,2})[/-](\d{1,2})[/-]((?:19|20)\d{2})$/);return match?`${match[3]}-${match[2].padStart(2,'0')}-${match[1].padStart(2,'0')}`:value};
const normalizeCatalogValue=(target:keyof typeof aliases,value:string)=>target==='destinationRegistryTypeId'?value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,'-'):target==='legalActId'?value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,'-'):target==='documentDate'?normalizeDate(value):value;
export function findOcrField(fields:OcrField[],target:keyof typeof aliases){const names=normalizedAliases[target];return fields.find(item=>names.includes(normalizeOcrFieldName(item.fieldName))&&Boolean(item.normalizedValue||item.extractedValue))}
export function mapOcrFieldsToReview(fields:OcrField[]){const output:Partial<ReviewValues>={};for(const target of Object.keys(aliases) as Array<keyof typeof aliases>){const field=findOcrField(fields,target);if(field)output[target]=normalizeCatalogValue(target,String(field.normalizedValue||field.extractedValue).trim())}return output}
export function mergeOcrFieldsIntoReview(current:ReviewValues,fields:OcrField[],manuallyEdited:ReadonlySet<keyof ReviewValues>){const detected=mapOcrFieldsToReview(fields);return {...current,...Object.fromEntries(Object.entries(detected).filter(([key])=>!manuallyEdited.has(key as keyof ReviewValues)))} as ReviewValues}
export function reviewTargetsFromOcrFields(fields:OcrField[]){const targets=new Set<keyof ReviewValues>();for(const target of Object.keys(aliases) as Array<keyof typeof aliases>){const field=findOcrField(fields,target);if(!field||field.requiresReview)targets.add(target)}return targets}
export const ocrProcessingService={start:(uploadId:string,signal?:AbortSignal)=>apiRequest<OcrJobStartResponse>(`/documents/${uploadId}/ocr/start`,{method:'POST',body:JSON.stringify({}),signal}),status:(jobId:string)=>apiRequest<OcrJobStatus>(`/documents/${jobId}/job`),results:(jobId:string)=>apiRequest<OcrJobResults>(`/documents/document-processing-jobs/${jobId}/results`)};
