import {apiRequest} from './apiClient';
import type {ReviewValues} from '../domain/document-domain';
export type OcrJobStartResponse={jobId:string;status:string};
export type OcrJobStatus={jobId:string;status:string;currentStage?:string;totalPages?:number;processedPages?:number;progress?:number;errorCode?:string;error?:string|null};
export type OcrField={fieldName:string;normalizedValue?:string;extractedValue?:string;confidence?:number;requiresReview?:boolean;pageNumber?:number;sourceText?:string};
export type OcrJobResults={documentClass?:string;documentLocation?:Record<string,unknown>;location?:Record<string,unknown>;pages:unknown[];fields:OcrField[];confirmedFields?:OcrField[];reviewFields?:OcrField[];reviewCount:number};
const aliases:Record<keyof Pick<ReviewValues,'kardexNumber'|'destinationRegistryTypeId'|'destinationInstrumentNumber'|'minuteNumber'|'printedFolio'|'documentDate'|'legalActId'|'primaryContractor'|'instrumentType'|'instrumentNumber'>,string[]>={
  kardexNumber:['kardexNumber','kardex','kardex_number'],destinationRegistryTypeId:['destinationRegistryType','destinationRegistryTypeId','registryType'],destinationInstrumentNumber:['destinationInstrumentNumber','instrumentNumber'],minuteNumber:['minuteNumber','minuta','minute'],printedFolio:['printedFolio','folio','foja'],documentDate:['documentDate','date','fecha'],legalActId:['legalAct','legalActId','actoJuridico'],primaryContractor:['primaryContractor','contractor','contratante'],instrumentType:['instrumentType','destinationInstrumentType'],instrumentNumber:['instrumentNumber','destinationInstrumentNumber'],
};
export function mapOcrFieldsToReview(fields:OcrField[]){const output:Partial<ReviewValues>={};for(const [target,names] of Object.entries(aliases) as Array<[keyof typeof aliases,string[]]>){const field=fields.find(item=>names.includes(item.fieldName)&&Boolean(item.normalizedValue||item.extractedValue));if(field)output[target]=String(field.normalizedValue||field.extractedValue).trim()}return output}
export function reviewTargetsFromOcrFields(fields:OcrField[]){const targets=new Set<keyof ReviewValues>();for(const [target,names] of Object.entries(aliases) as Array<[keyof typeof aliases,string[]]>)if(fields.some(field=>names.includes(field.fieldName)&&field.requiresReview))targets.add(target);return targets}
export const ocrProcessingService={start:(uploadId:string,signal?:AbortSignal)=>apiRequest<OcrJobStartResponse>(`/documents/${uploadId}/ocr/start`,{method:'POST',body:JSON.stringify({}),signal}),status:(jobId:string)=>apiRequest<OcrJobStatus>(`/documents/${jobId}/job`),results:(jobId:string)=>apiRequest<OcrJobResults>(`/documents/document-processing-jobs/${jobId}/results`)};
