import type {DocumentRecord} from '../data/repository';
import {sanitizeDisplayText} from '../utils/displayText';
export type TomeDocument={document:DocumentRecord;label:string;requiresReview:boolean};
export type TomeCategory={name:string;documents:TomeDocument[]};
export type TomeKardex={key:string;label:string;sortValue:string;status:string;categories:TomeCategory[]};
export type TomeGroup={key:string;label:string;sortValue:number;kardexCases:TomeKardex[]};
export type PeriodGroup={key:string;label:string;sortValue:number;tomes:TomeGroup[]};
const definitive=new Set(['CONFIRMED','READY','ARCHIVED','VALIDADO']);const clean=(value:unknown)=>sanitizeDisplayText(value);
export function normalizeKardex(value:unknown){let text=clean(value).toUpperCase().replace(/^KARDEX[\s:-]*/,'').replace(/^K[\s:-]+/,'').replace(/[\s_-]+/g,'');if(/^[0-9O]+$/.test(text))text=text.replace(/O/g,'0').replace(/^0+(?=\d)/,'');return text}
const numberFrom=(value:unknown)=>{const match=clean(value).match(/\d+/);return match?Number(match[0]):Number.MAX_SAFE_INTEGER};
const category=(document:DocumentRecord)=>/minuta/i.test(clean(document.tipo))?'Minuta':/acta|registro|escritura/i.test(clean(document.tipo))?'Acta':clean(document.tipo)||'Requiere revisión';
const categoryRank=(value:string)=>value==='Minuta'?0:value==='Acta'?1:2;
const name=(document:DocumentRecord,type:string)=>{const kardex=normalizeKardex(document.normalizedKardex??document.kardex);if(type==='Minuta')return kardex?`K-${kardex}.pdf`:'DOCUMENTO - REVISAR.pdf';if(type==='Acta'){const contractor=clean(document.contratantes[0]);if(contractor&&kardex)return `${contractor} - KARDEX ${kardex}.pdf`;if(kardex)return `KARDEX ${kardex} - ACTA - REVISAR.pdf`}return clean(document.fileName)||'DOCUMENTO - REVISAR.pdf'};
const period=(document:DocumentRecord)=>{if(document.bienniumStart&&document.bienniumEnd)return {key:`biennium:${document.bienniumStart}-${document.bienniumEnd}`,label:`Bienio ${document.bienniumStart}-${document.bienniumEnd}`,sortValue:document.bienniumEnd};if(document.ano)return {key:`year:${document.ano}`,label:`Año ${document.ano}`,sortValue:document.ano};return {key:'period:unknown',label:'Período sin identificar',sortValue:-1}};
export function buildTomeHierarchy(documents:DocumentRecord[]):PeriodGroup[]{const periods=new Map<string,{label:string;sortValue:number;documents:DocumentRecord[]}>();for(const document of documents){if(!definitive.has(clean(document.documento).toUpperCase()))continue;const value=period(document);const group=periods.get(value.key)??{label:value.label,sortValue:value.sortValue,documents:[]};group.documents.push(document);periods.set(value.key,group)}return [...periods.entries()].map(([periodKey,value])=>{const tomes=new Map<string,DocumentRecord[]>();for(const document of value.documents){const tome=clean(document.tomo)||'unknown';tomes.set(tome,[...(tomes.get(tome)??[]),document])}return {key:periodKey,label:value.label,sortValue:value.sortValue,tomes:[...tomes.entries()].map(([tome,rows])=>{const cases=new Map<string,DocumentRecord[]>();for(const document of rows){const normalized=normalizeKardex(document.normalizedKardex??document.kardex);const caseKey=document.kardexCaseId??(normalized?`${periodKey}|${tome}|${normalized}`:`unconfirmed:${document.id}`);cases.set(caseKey,[...(cases.get(caseKey)??[]),document])}return {key:`${periodKey}/tome:${tome}`,label:tome==='unknown'?'Tomo sin identificar':`Tomo ${tome}`,sortValue:numberFrom(tome),kardexCases:[...cases.entries()].map(([caseKey,caseRows])=>{const normalized=normalizeKardex(caseRows[0].normalizedKardex??caseRows[0].kardex);const categories=new Map<string,TomeDocument[]>();for(const document of caseRows){const type=category(document);categories.set(type,[...(categories.get(type)??[]),{document,label:name(document,type),requiresReview:!normalized||document.relationStatus==='Requiere revisión'||document.relationStatus==='Conflicto'}])}return {key:`${periodKey}/tome:${tome}/case:${caseKey}`,label:normalized?`Kardex ${normalized}`:'Kardex sin confirmar',sortValue:normalized,status:caseRows[0].relationStatus??'Kardex sin confirmar',categories:[...categories.entries()].map(([categoryName,items])=>({name:categoryName,documents:items})).sort((a,b)=>categoryRank(a.name)-categoryRank(b.name))}}).sort((a,b)=>a.sortValue.localeCompare(b.sortValue,'es',{numeric:true}))}}).sort((a,b)=>a.sortValue-b.sortValue)}}).sort((a,b)=>b.sortValue-a.sortValue)}
