import type {DocumentRecord} from '../data/repository';
import {sanitizeDisplayText} from '../utils/displayText';
export type TomeDocument={document:DocumentRecord;label:string;requiresReview:boolean};
export type TomeCategory={name:string;documents:TomeDocument[]};
export type TomeGroup={key:string;label:string;sortValue:number;categories:TomeCategory[]};
export type PeriodGroup={key:string;label:string;sortValue:number;tomes:TomeGroup[]};
const definitive=new Set(['CONFIRMED','READY','ARCHIVED','VALIDADO']);const clean=(value:unknown)=>sanitizeDisplayText(value);
export function normalizeKardex(value:unknown){let text=clean(value).toUpperCase().replace(/^KARDEX[\s:-]*/,'').replace(/^K[\s:-]+/,'').replace(/[\s_-]+/g,'');if(/^[0-9O]+$/.test(text))text=text.replace(/O/g,'0').replace(/^0+(?=\d)/,'');return text}
const numberFrom=(value:unknown)=>{const match=clean(value).match(/\d+/);return match?Number(match[0]):Number.MAX_SAFE_INTEGER};
const category=(document:DocumentRecord)=>/minuta/i.test(clean(document.tipo))?'Minuta':/acta|registro|escritura/i.test(clean(document.tipo))?'Acta':clean(document.tipo)||'Requiere revisión';
const categoryRank=(value:string)=>value==='Minuta'?0:value==='Acta'?1:2;
const filename=(document:DocumentRecord,type:string)=>{const confirmed=clean(document.fileName);const kardex=normalizeKardex(document.normalizedKardex??document.kardex);if(type==='Minuta')return /^K-[^.]+(?: \(\d+\))?\.pdf$/i.test(confirmed)?confirmed:kardex?`K-${kardex}.pdf`:'DOCUMENTO - REVISAR.pdf';if(type==='Acta'){if(confirmed&&!/^document-clean\.pdf$/i.test(confirmed))return confirmed;const contractor=clean(document.contratantes[0]);return contractor&&kardex?`${contractor} - KARDEX ${kardex}.pdf`:kardex?`KARDEX ${kardex} - ACTA - REVISAR.pdf`:'DOCUMENTO - REVISAR.pdf'}return confirmed||'DOCUMENTO - REVISAR.pdf'};
const period=(document:DocumentRecord)=>document.bienniumStart&&document.bienniumEnd?{key:`biennium:${document.bienniumStart}-${document.bienniumEnd}`,label:`Bienio ${document.bienniumStart}-${document.bienniumEnd}`,sortValue:document.bienniumEnd}:document.ano?{key:`year:${document.ano}`,label:`Año ${document.ano}`,sortValue:document.ano}:{key:'period:unknown',label:'Período sin identificar',sortValue:-1};
export function buildTomeHierarchy(documents:DocumentRecord[]):PeriodGroup[]{const periods=new Map<string,{label:string;sortValue:number;documents:DocumentRecord[]}>();for(const document of documents){if(!definitive.has(clean(document.documento).toUpperCase()))continue;const value=period(document);const group=periods.get(value.key)??{label:value.label,sortValue:value.sortValue,documents:[]};group.documents.push(document);periods.set(value.key,group)}return [...periods.entries()].map(([periodKey,value])=>{const tomes=new Map<string,DocumentRecord[]>();for(const document of value.documents){const tome=clean(document.tomo)||'unknown';tomes.set(tome,[...(tomes.get(tome)??[]),document])}return {key:periodKey,label:value.label,sortValue:value.sortValue,tomes:[...tomes.entries()].map(([tome,rows])=>{const categories=new Map<string,TomeDocument[]>();for(const document of rows){const type=category(document);const kardex=normalizeKardex(document.normalizedKardex??document.kardex);categories.set(type,[...(categories.get(type)??[]),{document,label:filename(document,type),requiresReview:!kardex||document.relationStatus==='Requiere revisión'||document.relationStatus==='Conflicto'}])}return {key:`${periodKey}/tome:${tome}`,label:tome==='unknown'?'Tomo sin identificar':`Tomo ${tome}`,sortValue:numberFrom(tome),categories:[...categories.entries()].map(([name,items])=>({name,documents:items.sort((a,b)=>a.label.localeCompare(b.label,'es',{numeric:true}))})).sort((a,b)=>categoryRank(a.name)-categoryRank(b.name))}}).sort((a,b)=>a.sortValue-b.sortValue)}}).sort((a,b)=>b.sortValue-a.sortValue)}
