import {readFileSync} from 'node:fs';
import {describe,expect,it} from 'vitest';
describe('importación masiva',()=>{
 it('marca solo las cargas validadas por importación como listas para revisión',()=>{const backend=readFileSync(new URL('../src/controllers/documents.controller.ts',import.meta.url),'utf8');const api=readFileSync(new URL('../../src/services/documentsApi.ts',import.meta.url),'utf8');expect(backend).toContain("req.get('x-import-validated')==='true'");expect(backend).toContain("importValidated?'REVIEW_REQUIRED':'UPLOADED'");expect(api).toContain("uploadTemporary(document.file,document.fileName,true)")});
 it('mantiene sin cambios el flujo normal de carga',()=>{const api=readFileSync(new URL('../../src/services/documentsApi.ts',import.meta.url),'utf8');expect(api).toContain('uploadTemporary(document.file,document.fileName)).uploadId')});
 it('procesa cada registro con aislamiento de errores',()=>{const component=readFileSync(new URL('../../src/components/ExistingImports.tsx',import.meta.url),'utf8');expect(component).toContain('for(const [index,result] of candidates.entries())');expect(component).toMatch(/try\{setPdfProgress[\s\S]*?completed\+\+\}catch\(error\)\{failed\+\+/)});
 it('aplica período, tomo y Kardex de cada ficha al documento central',()=>{const component=readFileSync(new URL('../../src/components/ExistingImports.tsx',import.meta.url),'utf8');for(const field of ["period=fields.period?.value","tomo:fields.tome?.value","kardex:fields.kardexNumber?.value"])expect(component).toContain(field)});
 it('muestra progreso real y conserva el error individual',()=>{const component=readFileSync(new URL('../../src/components/ExistingImports.tsx',import.meta.url),'utf8');expect(component).toContain('Registrando ${index+1}/${candidates.length}');expect(component).toContain('registrationError:lastError')});
 it('evita duplicados por hash en PostgreSQL y audita éxitos y fallos',()=>{const backend=readFileSync(new URL('../src/controllers/documents.controller.ts',import.meta.url),'utf8');expect(backend).toContain('where:{fileHash:hash}');expect(backend).toContain("station:importValidated?'IMPORT':undefined");expect(backend).toContain("'IMPORT_FILE_UPLOADED'");expect(backend).toContain("'IMPORT_FILE_FAILED'");expect(backend).toContain("'DOCUMENT_CREATED'")});
});
