import {readFileSync} from 'node:fs';
import {describe,expect,it} from 'vitest';
import {documentDisplayName} from '../src/utils/document-filename';

describe('nombre de descarga después de corregir metadatos',()=>{
  it('regenera el nombre de un registro notarial',()=>expect(documentDisplayName({documentType:'Escrituras públicas',kardex:'N7278',instrumentNumber:'294',primaryContractor:'ERIKA RUIZ MARTINEZ'})).toBe('ERIKA RUIZ MARTINEZ - KARDEX N7278 - ESCRITURA 294.pdf'));
  it('regenera una Solicitud sin número de escritura en el nombre',()=>expect(documentDisplayName({documentType:'Solicitud',kardex:'9492',instrumentNumber:'10',primaryContractor:'LUIS PABLO MEDRA VALENCIA'})).toBe('LUIS PABLO MEDRA VALENCIA - KARDEX 9492.pdf'));
  it('evita nombres duplicados',()=>expect(documentDisplayName({documentType:'Escrituras públicas',kardex:'10',instrumentNumber:'20',primaryContractor:'ANA',existingNames:['ANA - KARDEX 10 - ESCRITURA 20.pdf']})).toBe('ANA - KARDEX 10 - ESCRITURA 20 (2).pdf'));
  it('persiste el nuevo displayName en la actualización central',()=>{const source=readFileSync(new URL('../src/controllers/documents.controller.ts',import.meta.url),'utf8');expect(source).toContain('if(renameChanged)data.displayName=nextDisplayName')});
  it('actualiza inmediatamente el encabezado del visor si el servidor activo devuelve temporalmente el nombre anterior',()=>{const source=readFileSync(new URL('../../src/pages/Visor.tsx',import.meta.url),'utf8');expect(source).toContain('updated.fileName===current.fileName');expect(source).toContain('setDocument(refreshed)');expect(source).toContain('El PDF ahora se descargar');expect(source).toContain('${refreshed.fileName}')});
  it('propaga el documento actualizado hacia Gestión Documental y Gestión de Tomos',()=>{const api=readFileSync(new URL('../../src/services/documentsApi.ts',import.meta.url),'utf8');const hook=readFileSync(new URL('../../src/hooks/useDocuments.ts',import.meta.url),'utf8');expect(api).toContain('detail:{documentId:document.backendId,document}');expect(hook).toContain('item.backendId===updated.backendId?updated:item');expect(hook).toContain('refresh(false)')});
  it('no muestra un aviso cuando se cierra la edición sin cambios reales',()=>{const source=readFileSync(new URL('../../src/pages/Visor.tsx',import.meta.url),'utf8');expect(source).not.toContain("setSavedMessage('No se realizaron cambios.')")});
  it('guarda según los campos que el usuario editó sin depender de comparar nuevamente la vista',()=>{const source=readFileSync(new URL('../../src/pages/Visor.tsx',import.meta.url),'utf8');expect(source).toContain('setChangedFields(fields=>new Set(fields).add(field))');expect(source).toContain("if(changed('kardex'))patch.kardex=draft.kardex.trim()");expect(source).toContain("if(changed('contratantes'))patch.contractors=contractors")});
  it('fuerza a Gestión Documental y Gestión de Tomos a leer la lista más reciente',()=>{const client=readFileSync(new URL('../../src/services/documentsApi.ts',import.meta.url),'utf8');const controller=readFileSync(new URL('../src/controllers/documents.controller.ts',import.meta.url),'utf8');expect(client).toContain("{cache:'no-store'}");expect(client).toContain('&revision=${revision}');expect(controller).toContain("res.setHeader('Cache-Control','no-store')")});
  it('deriva el nombre visible desde los metadatos actuales para todas las vistas',()=>{const source=readFileSync(new URL('../../src/services/documentsApi.ts',import.meta.url),'utf8');expect(source).toContain('const currentFileName=currentDocumentFilename(row)');expect(source).toContain("const contractor=row.contractors[0]?.name??''");expect(source).toContain('fileName:currentFileName')});
});
