import {describe,expect,it} from 'vitest';
import {analyzeInventoryPath,compareInventoryWithExcel,comparePdfEvidenceWithExcel,extractFolios,extractKardex,extractPeriod,extractTome,groupWrittenInstrumentPages,normalizeHeader,processMetadataBatches,splitInstrument,suggestHeader} from '../../src/services/importAnalysis';
import type {NormalizedExcelRow,PdfDocumentEvidence} from '../../src/domain/document-domain';

const row=(id:string,kardex:string,contractor='MARÍA PÉREZ'):NormalizedExcelRow=>({id,jobId:'job',sheetName:'Índice',rowNumber:Number(id),values:{kardexNumber:{rawValue:kardex,normalizedValue:kardex,rowNumber:2,columnName:'KARDEX',validationErrors:[]},contractor:{rawValue:contractor,normalizedValue:contractor,rowNumber:2,columnName:'CONTRATANTE',validationErrors:[]}}});

describe('extractores de inventario',()=>{
  it('extrae kardex desde variantes de nombre',()=>{expect(extractKardex('KARDEX N° 333.pdf')?.value).toBe('333');expect(extractKardex('K 334.pdf')?.value).toBe('334');expect(extractKardex('335.pdf')?.value).toBe('335')});
  it('tolera variantes históricas frecuentes de kardex',()=>{expect(extractKardex('KARDES 1551.pdf')?.value).toBe('1551');expect(extractKardex('GARDEX 797.pdf')?.value).toBe('797')});
  it('no asume kardex en un nombre con número aislado ambiguo',()=>expect(extractKardex('TOMO 333.pdf')).toBeUndefined());
  it('detecta año y bienio',()=>{expect(extractPeriod('1995')?.value).toBe('1995');expect(extractPeriod('BIENIO 1994 – 1995')?.value).toBe('1994-1995')});
  it('detecta tomo arábigo y romano',()=>{expect(extractTome('N° TOMO 03')?.value).toBe('3');expect(extractTome('TOMO IV')?.value).toBe('IV')});
  it('detecta foja y rango sin confundir un bienio',()=>{expect(extractFolios('FOJA 465')?.value).toBe('465');expect(extractFolios('FOJAS 100 A 120')?.value).toBe('100-120');expect(extractFolios('BIENIO 1994-1995')).toBeUndefined()});
  it('analiza carpetas profundas sin exponer ruta absoluta',()=>{const value=analyzeInventoryPath({jobId:'j',relativePath:'Escrituras/1994-1995/TOMO 2/FOJAS 100-120/María Pérez/KARDEX 333.pdf',name:'KARDEX 333.pdf',size:10});expect(value.depth).toBe(5);expect(value.relativePath.startsWith('Escrituras')).toBe(true);expect(value.kardex?.value).toBe('333')});
  it('hereda el bienio de la carpeta raíz para cada documento',()=>{const value=analyzeInventoryPath({jobId:'j',relativePath:'TOMO 2/FOJAS 100-120/María Pérez/KARDEX 333.pdf',rootContext:'BIENIO 1994-1995',name:'KARDEX 333.pdf',size:10});expect(value.period?.value).toBe('1994-1995')});
  it('no confunde tomo y fojas con una clase documental',()=>{expect(analyzeInventoryPath({jobId:'j',relativePath:'TOMO 2/FOJAS 100-120/María Pérez/KARDEX 333.pdf',name:'KARDEX 333.pdf',size:10}).preliminaryClass).toBe('UNKNOWN')});
  it('agrupa y ordena páginas de una carpeta escritura como un documento',()=>{const pages=['Pag.2.pdf','Pag.1.pdf'].map(name=>analyzeInventoryPath({jobId:'j',relativePath:`TOMO 1/ESCRITURA 6/${name}`,name,size:10}));const grouped=groupWrittenInstrumentPages(pages);const logical=grouped.find(file=>file.logicalPageGroup);expect(logical?.componentPaths).toEqual(['TOMO 1/ESCRITURA 6/Pag.1.pdf','TOMO 1/ESCRITURA 6/Pag.2.pdf']);expect(logical?.preliminaryClass).toBe('REGISTRO_NOTARIAL');expect(grouped.filter(file=>file.analysisStatus==='IGNORED')).toHaveLength(2)});
});

describe('Excel y vinculación',()=>{
  it('normaliza y sugiere encabezados equivalentes',()=>{expect(normalizeHeader(' N° Kardex ')).toBe('N KARDEX');expect(suggestHeader('NRO KARDEX')).toBe('kardexNumber')});
  it('mapea encabezados del índice histórico',()=>{expect(suggestHeader('N°')).toBe('correlative');expect(suggestHeader('N° ESCRITURA PUBLICA')).toBe('instrumentNumber');expect(suggestHeader('N° DE TOMO')).toBe('tomeNumber');expect(suggestHeader('AÑO 1994-1995')).toBe('biennium');expect(suggestHeader('CONTRATANTES')).toBe('contractor');expect(suggestHeader('OBSERVACIONES')).toBe('observations')});
  it('separa tipo y número de instrumento',()=>expect(splitInstrument('ESCRITURA: 345')).toEqual({instrumentType:'ESCRITURA',instrumentNumber:'345'}));
  it('coincide exactamente por kardex',()=>{const file=analyzeInventoryPath({jobId:'j',relativePath:'KARDEX 333.pdf',name:'KARDEX 333.pdf',size:1});expect(compareInventoryWithExcel(file,[row('2','333')]).status).toBe('MATCHED')});
  it('sugiere un kardex probable usando número y nombre sin aprobarlo automáticamente',()=>{const file=analyzeInventoryPath({jobId:'j',relativePath:'MARÍA PÉREZ/KARDEX 338.pdf',name:'KARDEX 338.pdf',size:1});const result=compareInventoryWithExcel(file,[row('2','333'),row('3','901','JUAN RAMÍREZ')]);expect(result.status).toBe('PARTIAL_MATCH');expect(result.matches[0].values.kardexNumber?.normalizedValue).toBe('333');expect(result.conflicts[0]).toContain('podría ser 333')});
  it('detecta kardex duplicado en Excel',()=>{const file=analyzeInventoryPath({jobId:'j',relativePath:'KARDEX 333.pdf',name:'KARDEX 333.pdf',size:1});expect(compareInventoryWithExcel(file,[row('2','333'),row('3','333')]).status).toBe('DUPLICATE_IN_EXCEL')});
  it('detecta múltiples contratantes',()=>{const file=analyzeInventoryPath({jobId:'j',relativePath:'KARDEX 333.pdf',name:'KARDEX 333.pdf',size:1});expect(compareInventoryWithExcel(file,[row('2','333'),row('3','333','JUAN PÉREZ')]).contractors).toHaveLength(2)});
  it('marca archivo sin kardex',()=>{const file=analyzeInventoryPath({jobId:'j',relativePath:'documento.pdf',name:'documento.pdf',size:1});expect(compareInventoryWithExcel(file,[row('2','333')]).status).toBe('KARDEX_NOT_DETECTED')});
  it('contrasta el kardex leído dentro del PDF con carpeta y Excel',()=>{const file=analyzeInventoryPath({jobId:'j',relativePath:'ACAT VELARDE CARLOS/KARDEX 111.pdf',name:'KARDEX 111.pdf',size:1});const evidence:PdfDocumentEvidence={status:'TEXT_EXTRACTED',pageCount:2,textCharacters:200,usedOcr:false,analyzedAt:new Date().toISOString(),fields:{kardexNumber:'112'}};const comparison=comparePdfEvidenceWithExcel(file,evidence,[row('2','111','ACAT VELARDE CARLOS')]);expect(comparison.conflicts).toContain('Kardex: ruta/archivo 111 ≠ PDF 112')});
  it('acepta una coincidencia comprobada entre PDF e índice',()=>{const file=analyzeInventoryPath({jobId:'j',relativePath:'ACAT VELARDE CARLOS/KARDEX 111.pdf',name:'KARDEX 111.pdf',size:1});const evidence:PdfDocumentEvidence={status:'OCR_COMPLETED',pageCount:2,textCharacters:200,usedOcr:true,analyzedAt:new Date().toISOString(),fields:{kardexNumber:'111'}};expect(comparePdfEvidenceWithExcel(file,evidence,[row('2','111','ACAT VELARDE CARLOS')]).conflicts).toEqual([])});
  it('permite confirmar desde el PDF cuando no existe en Excel y están todos los campos',()=>{const file=analyzeInventoryPath({jobId:'j',relativePath:'ACAT VELARDE CARLOS/KARDEX 111.pdf',name:'KARDEX 111.pdf',size:1});const evidence:PdfDocumentEvidence={status:'OCR_COMPLETED',pageCount:2,textCharacters:500,usedOcr:true,averageConfidence:80,analyzedAt:new Date().toISOString(),fields:{kardexNumber:'111',minuteNumber:'22',printedFolio:'45',instrumentNumber:'10'},legalAct:'compraventa'};const result=comparePdfEvidenceWithExcel(file,evidence,[]);expect(result.pdfOnlyConfirmed).toBe(true);expect(result.conflicts).toEqual([])});
});

describe('procesamiento por lotes',()=>{
  it('reanuda desde el cursor guardado',async()=>{const seen:number[]=[];const result=await processMetadataBatches([0,1,2,3,4],{start:2,batchSize:2,cancelled:()=>false,paused:()=>false,onBatch:batch=>{seen.push(...batch)}});expect(seen).toEqual([2,3,4]);expect(result.completed).toBe(true)});
  it('cancela sin procesar elementos posteriores',async()=>{let cancel=false;const result=await processMetadataBatches([1,2,3,4],{batchSize:2,cancelled:()=>cancel,paused:()=>false,onBatch:()=>{cancel=true}});expect(result.cancelled).toBe(true);expect(result.cursor).toBe(2)});
  it('procesa miles de registros cediendo control por lote',async()=>{let yields=0;const result=await processMetadataBatches(Array.from({length:5000},(_,index)=>index),{batchSize:200,cancelled:()=>false,paused:()=>false,onBatch:()=>undefined,yieldControl:async()=>{yields++}});expect(result.completed).toBe(true);expect(yields).toBe(25)});
});
