import {describe,expect,it} from 'vitest';
import {classifyLegalAct,extractNotarialFields,extractSpatialHistoricalFields,normalizeOcrText,proposedFilename} from '../../src/services/ocrExtraction';
describe('OCR documental',()=>{
 it('normaliza espacios sin perder bloques',()=>expect(normalizeOcrText('KARDEX: 333\n\n  MINUTA N° 116 ')).toBe('KARDEX: 333\nMINUTA N° 116'));
 it('extrae etiquetas y clase notarial',()=>{const fields=extractNotarialFields('KARDEX: 333 MINUTA N° 116 FOJA: 465 ESCRITURA N° 119');expect(fields.slice(0,4).map(f=>f.normalizedValue)).toEqual(['333','116','465','119']);expect(fields.find(field=>field.fieldName==='instrumentType')?.normalizedValue).toBe('ESCRITURA');expect(fields.find(field=>field.fieldName==='documentClass')?.normalizedValue).toBe('REGISTRO_NOTARIAL');});
 it('interpreta las marcas históricas K, E y M sin inventar A.V.',()=>{const fields=extractNotarialFields('ESCRITURA NUMERO 6\nPODER\nK. 009\nE. 6\nM. 7\nA.V.');expect(fields.find(field=>field.fieldName==='kardexNumber')?.normalizedValue).toBe('9');expect(fields.find(field=>field.fieldName==='instrumentNumber')?.normalizedValue).toBe('6');expect(fields.find(field=>field.fieldName==='minuteNumber')?.normalizedValue).toBe('7');expect(fields.find(field=>field.fieldName==='unclassifiedAv')?.normalizedValue).toBeNull();});
 it('tolera confusiones OCR en el margen dirigido',()=>{const fields=extractNotarialFields('MARCAS_LATERALES\nX . O12\nE : 1O\nM - 7');expect(fields.find(field=>field.fieldName==='kardexNumber')?.normalizedValue).toBe('12');expect(fields.find(field=>field.fieldName==='instrumentNumber')?.normalizedValue).toBe('10');expect(fields.find(field=>field.fieldName==='minuteNumber')?.normalizedValue).toBe('7');});
 it('recupera una M.7 degradada como N.T en el recorte lateral',()=>{const fields=extractNotarialFields('MARCAS_LATERALES\nK.012\nE. 10\nN. T');expect(fields.find(field=>field.fieldName==='minuteNumber')?.normalizedValue).toBe('7');});
 it('prioriza el kardex completo cuando una pasada solo reconoce un dígito',()=>{const fields=extractNotarialFields('MARCAS_LATERALES_SUAVE\nK. 012\nMARCAS_LATERALES_BINARIA\nK. 1');expect(fields.find(field=>field.fieldName==='kardexNumber')?.normalizedValue).toBe('12');});
 it('relaciona códigos por cercanía sin depender de posiciones fijas',()=>{const words=[{text:'E.',confidence:91,pageNumber:1,x0:700,y0:100,x1:730,y1:125},{text:'10',confidence:94,pageNumber:1,x0:748,y0:100,x1:790,y1:125},{text:'K.',confidence:90,pageNumber:1,x0:80,y0:420,x1:110,y1:448},{text:'012',confidence:93,pageNumber:1,x0:125,y0:420,x1:180,y1:448},{text:'M.',confidence:88,pageNumber:1,x0:420,y0:760,x1:450,y1:790},{text:'7',confidence:95,pageNumber:1,x0:470,y0:760,x1:490,y1:790},{text:'FOJA',confidence:92,pageNumber:1,x0:100,y0:900,x1:175,y1:930},{text:'321',confidence:96,pageNumber:1,x0:200,y0:900,x1:255,y1:930}];expect(extractSpatialHistoricalFields(words)).toMatchObject({kardexNumber:'12',instrumentNumber:'10',minuteNumber:'7',printedFolio:'321'})});
 it('descarta ruido OCR como contratante',()=>{const fields=extractNotarialFields('SEÑOR: y =—-00=00N |');expect(fields.find(field=>field.fieldName==='contractor')?.normalizedValue).toBeNull()});
 it('conserva nombres válidos como contratante',()=>{const fields=extractNotarialFields('OTORGANTE: ACAT VELARDE CARLOS');expect(fields.find(field=>field.fieldName==='contractor')?.normalizedValue).toBe('ACAT VELARDE CARLOS')});
 it('clasifica acto sin inventar',()=>{expect(classifyLegalAct('otorgan contrato de compraventa').suggested).toBe('compraventa');expect(classifyLegalAct('texto ilegible').requiresReview).toBe(true);});
 it('genera nombre seguro',()=>expect(proposedFilename('María Pérez','333','MINUTA')).toBe('Maria Perez - KARDEX 333 - MINUTA.pdf'));
});
