import {spawn} from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs/promises';
import {prisma} from '../config/prisma.js';
import {env} from '../config/env.js';

const root=path.resolve(env.STORAGE_ROOT);const worker=path.resolve(process.cwd(),'..','src-tauri','vision','processor.py');const pending:string[]=[];let activeJobId:string|undefined;
type OcrResultPage={pageNumber?:number;rawText?:string;averageConfidence?:number;engine?:string};
type PersistedField={fieldName:string;extractedValue:string;normalizedValue:string;confidence:number;requiresReview:boolean;sourceText?:string};
export function extractScanFields(pages:OcrResultPage[]):PersistedField[]{const text=pages.map(page=>String(page.rawText??'')).join('\n').replace(/\s+/g,' ').trim();const value=(pattern:RegExp)=>pattern.exec(text)?.[1]?.trim()??'';const kardex=value(/(?:k(?:ardex|ardes|ardez)|c[oó]digo\s+kardex)\s*(?:n(?:[úu]mero|[.º°])?\s*)?[:.-]?\s*([0-9]{1,8})/i).replace(/^0+(?=\d)/,'');const minute=value(/minuta\s*(?:n(?:[úu]mero|[.º°])?\s*)?[:.-]?\s*([0-9]{1,8})/i);const instrument=/(escritura(?:\s+p[úu]blica)?|acta|poder|testamento|instrumento)\s*(?:n(?:[úu]mero|[.º°])?\s*)?[:.-]?\s*([0-9]{1,8})/i.exec(text);const contractor=value(/(?:comparece(?:n)?|otorgante(?:s)?|contratante(?:s)?|señor(?:a|es)?|a\s+favor\s+de)[\s:.-]+([^.;:\n]{5,100})/i).replace(/\s+(?:QUIEN|DECLARA|MANIFIESTA|OTORGA)\b.*$/i,'').trim();const candidates:[string,string][]=[['kardexNumber',kardex],['minuteNumber',minute],['instrumentType',instrument?.[1]?.toUpperCase()??''],['instrumentNumber',instrument?.[2]??''],['contractor',contractor]];return candidates.map(([fieldName,normalizedValue])=>({fieldName,extractedValue:normalizedValue,normalizedValue,confidence:normalizedValue.length?0.82:0,requiresReview:!normalizedValue,sourceText:normalizedValue?text.slice(0,500):undefined}))}
export async function enqueueOcrJob(jobId:string){const job=await prisma.documentProcessingJob.findUnique({where:{id:jobId}});if(!job)throw new Error('Trabajo documental inexistente.');if(['OCR_PROCESSING','REVIEW_REQUIRED','COMPLETED'].includes(job.status))return {jobId,status:job.status};if(activeJobId){if(!pending.includes(jobId))pending.push(jobId);await prisma.documentProcessingJob.update({where:{id:jobId},data:{status:'OCR_PENDING'}});return {jobId,status:'OCR_PENDING'}}activeJobId=jobId;await prisma.documentProcessingJob.update({where:{id:jobId},data:{status:'OCR_PROCESSING'}});void runOcr(jobId,path.resolve(root,job.temporaryPath));return {jobId,status:'OCR_PROCESSING'}}
async function startNext(){activeJobId=undefined;const jobId=pending.shift();if(!jobId)return;const job=await prisma.documentProcessingJob.findUnique({where:{id:jobId}});if(!job||job.status==='CANCELLED'){void startNext();return}activeJobId=jobId;await prisma.documentProcessingJob.update({where:{id:jobId},data:{status:'OCR_PROCESSING'}});void runOcr(jobId,path.resolve(root,job.temporaryPath))}
async function runOcr(jobId:string,source:string){const session=path.join(root,'ocr-sessions',jobId);await fs.mkdir(session,{recursive:true});const child=spawn(process.env.PYTHON_EXECUTABLE??'python',[worker,'recognize','--source',source,'--session',session],{windowsHide:true});let output='';let error='';child.stdout.on('data',chunk=>{output+=chunk.toString()});child.stderr.on('data',chunk=>{error+=chunk.toString()});child.on('close',async code=>{try{if(code!==0)throw new Error(error||'El worker OCR terminó con error.');const result=JSON.parse(output) as {pages?:OcrResultPage[]};const pages=result.pages??[];const fields=extractScanFields(pages);await prisma.$transaction(async tx=>{await tx.ocrPage.deleteMany({where:{jobId}});await tx.ocrField.deleteMany({where:{jobId}});for(const page of pages)await tx.ocrPage.create({data:{jobId,pageNumber:Number(page.pageNumber),text:String(page.rawText??''),confidence:Number(page.averageConfidence??0),engine:String(page.engine??'tesseract')}});if(fields.length)await tx.ocrField.createMany({data:fields.map(field=>({...field,jobId}))});await tx.documentProcessingJob.update({where:{id:jobId},data:{status:'REVIEW_REQUIRED'}})});}catch(reason){await prisma.documentProcessingJob.update({where:{id:jobId},data:{status:'FAILED',errorMessage:reason instanceof Error?reason.message:String(reason)}}).catch(()=>undefined)}finally{void startNext()}})}
