import {spawn} from 'node:child_process';
import path from 'node:path';
import fs from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {prisma} from '../config/prisma.js';
import {env} from '../config/env.js';

const root=path.resolve(env.STORAGE_ROOT);
const vision=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..','..','..','src-tauri','vision');
const worker=path.join(vision,'processor.py');
const pending:string[]=[];
let activeJobId:string|undefined;
type OcrResultPage={pageNumber?:number;rawText?:string;averageConfidence?:number;engine?:string};
type PersistedField={fieldName:string;extractedValue:string;normalizedValue:string;confidence:number;requiresReview:boolean;sourceText?:string};

export function extractScanFields(pages:OcrResultPage[]):PersistedField[]{const text=pages.map(page=>String(page.rawText??'')).join('\n').replace(/\s+/g,' ').trim();const value=(pattern:RegExp)=>pattern.exec(text)?.[1]?.trim()??'';const kardex=value(/(?:k(?:ardex|ardes|ardez)|c[oó]digo\s+kardex)\s*(?:n(?:[úu]mero|[.º°])?\s*)?[:.-]?\s*([0-9]{1,8})/i).replace(/^0+(?=\d)/,'');const minute=value(/minuta\s*(?:n(?:[úu]mero|[.º°])?\s*)?[:.-]?\s*([0-9]{1,8})/i);const instrument=/(escritura(?:\s+p[úu]blica)?|acta|poder|testamento|instrumento)\s*(?:n(?:[úu]mero|[.º°])?\s*)?[:.-]?\s*([0-9]{1,8})/i.exec(text);const contractor=value(/(?:comparece(?:n)?|otorgante(?:s)?|contratante(?:s)?|señor(?:a|es)?|a\s+favor\s+de)[\s:.-]+([^.;:\n]{5,100})/i).replace(/\s+(?:QUIEN|DECLARA|MANIFIESTA|OTORGA)\b.*$/i,'').trim();const candidates:[string,string][]=[['kardexNumber',kardex],['minuteNumber',minute],['instrumentType',instrument?.[1]?.toUpperCase()??''],['instrumentNumber',instrument?.[2]??''],['contractor',contractor]];return candidates.map(([fieldName,normalizedValue])=>({fieldName,extractedValue:normalizedValue,normalizedValue,confidence:normalizedValue.length?0.82:0,requiresReview:!normalizedValue,sourceText:normalizedValue?text.slice(0,500):undefined}))}

export async function enqueueOcrJob(jobId:string){const job=await prisma.documentProcessingJob.findUnique({where:{id:jobId}});if(!job)throw new Error('Trabajo documental inexistente.');if(['OCR_PROCESSING','REVIEW_REQUIRED','COMPLETED'].includes(job.status))return {jobId,status:job.status};if(activeJobId){if(!pending.includes(jobId))pending.push(jobId);await prisma.documentProcessingJob.update({where:{id:jobId},data:{status:'OCR_PENDING'}});return {jobId,status:'OCR_PENDING'}}activeJobId=jobId;await prisma.documentProcessingJob.update({where:{id:jobId},data:{status:'OCR_PROCESSING',errorMessage:null}});void runOcr(jobId,path.resolve(root,job.temporaryPath));return {jobId,status:'OCR_PROCESSING'}}
async function startNext(){activeJobId=undefined;const jobId=pending.shift();if(!jobId)return;const job=await prisma.documentProcessingJob.findUnique({where:{id:jobId}});if(!job||job.status==='CANCELLED'){void startNext();return}activeJobId=jobId;await prisma.documentProcessingJob.update({where:{id:jobId},data:{status:'OCR_PROCESSING',errorMessage:null}});void runOcr(jobId,path.resolve(root,job.temporaryPath))}
const exists=async(value:string)=>fs.access(value).then(()=>true).catch(()=>false);
const sanitize=(value:string)=>value.replaceAll(root,'[storage]').replaceAll(process.cwd(),'[app]').replace(/[\r\n]+/g,' ').slice(-1200).trim();
async function runtime(){const pythonCandidates=[process.env.PYTHON_EXECUTABLE,path.join(vision,'.venv','Scripts','python.exe'),path.join(vision,'.venv','bin','python'),'python'].filter(Boolean) as string[];const checkedPython=await Promise.all(pythonCandidates.map(async candidate=>({candidate,valid:candidate==='python'||await exists(candidate)})));const python=checkedPython.find(item=>item.valid)?.candidate??'python';const tesseractCandidates=[process.env.TESSERACT_EXECUTABLE,'C:\\Program Files\\Tesseract-OCR\\tesseract.exe','C:\\Program Files (x86)\\Tesseract-OCR\\tesseract.exe'].filter(Boolean) as string[];const checkedTesseract=await Promise.all(tesseractCandidates.map(async candidate=>({candidate,valid:await exists(candidate)})));return {python,tesseract:checkedTesseract.find(item=>item.valid)?.candidate}}
async function failJob(jobId:string,technical:string){const match=/\b([A-Z][A-Z_]+):\s*(.*)/.exec(technical);const errorCode=match?.[1]??'OCR_ENGINE_FAILED';const message=sanitize(match?.[2]??technical);console.error(`[OCR] Fallo job=${jobId} errorCode=${errorCode} detail=${message}`);await prisma.documentProcessingJob.update({where:{id:jobId},data:{status:'FAILED',errorMessage:`${errorCode}: ${message}`}}).catch(()=>undefined)}
async function runOcr(jobId:string,source:string){
  const session=path.join(root,'ocr-sessions',jobId);await fs.mkdir(session,{recursive:true});
  try{
    const stat=await fs.stat(source).catch(()=>undefined);if(!stat?.isFile())throw new Error('TEMP_UPLOAD_NOT_FOUND: No existe la carga temporal.');if(stat.size<=0)throw new Error('PDF_OPEN_FAILED: El PDF temporal está vacío.');
    const handle=await fs.open(source,'r');const signature=Buffer.alloc(4);await handle.read(signature,0,4,0);await handle.close();if(signature.toString()!=='%PDF')throw new Error('PDF_OPEN_FAILED: La carga temporal no es un PDF válido.');
    console.info(`[OCR] PDF encontrado job=${jobId}`);console.info(`[OCR] Tamaño válido job=${jobId} bytes=${stat.size}`);
    const selected=await runtime();console.info(`[OCR] Worker iniciado job=${jobId}`);console.info(`[OCR] Python utilizado: ${path.basename(selected.python)}`);if(!selected.tesseract)throw new Error('TESSERACT_NOT_FOUND: No se encontró el ejecutable de Tesseract.');
    const child=spawn(selected.python,[worker,'recognize','--source',source,'--session',session],{windowsHide:true,env:{...process.env,TESSERACT_EXECUTABLE:selected.tesseract}});let output='';let error='';let spawnFailed=false;
    child.stdout.on('data',chunk=>{output=(output+chunk.toString()).slice(-10_000_000)});child.stderr.on('data',chunk=>{const line=sanitize(chunk.toString());if(line)console.info(`${line} job=${jobId}`);error=(error+chunk.toString()).slice(-4000)});
    child.on('error',reason=>{spawnFailed=true;void failJob(jobId,`OCR_ENGINE_FAILED: ${sanitize(reason.message)}`).finally(()=>startNext())});
    child.on('close',async code=>{if(spawnFailed)return;try{if(code!==0)throw new Error(sanitize(error)||'OCR_ENGINE_FAILED: El worker OCR terminó con error.');const result=JSON.parse(output) as {pages?:OcrResultPage[]};const pages=result.pages??[];if(!pages.length)throw new Error('OCR_RESULT_EMPTY: El worker no devolvió páginas.');const fields=extractScanFields(pages);await prisma.$transaction(async tx=>{await tx.ocrPage.deleteMany({where:{jobId}});await tx.ocrField.deleteMany({where:{jobId}});for(const page of pages)try{await tx.ocrPage.create({data:{jobId,pageNumber:Number(page.pageNumber),text:String(page.rawText??''),confidence:Number(page.averageConfidence??0),engine:String(page.engine??'tesseract')}})}catch{throw new Error(`OCR_PAGE_SAVE_FAILED: No se pudo guardar la página ${page.pageNumber}.`)}if(fields.length)await tx.ocrField.createMany({data:fields.map(field=>({...field,jobId}))});await tx.documentProcessingJob.update({where:{id:jobId},data:{status:'REVIEW_REQUIRED',errorMessage:null}})});}catch(reason){await failJob(jobId,reason instanceof Error?reason.message:String(reason))}finally{void startNext()}});
  }catch(reason){await failJob(jobId,reason instanceof Error?reason.message:String(reason));void startNext()}
}
