import type {IncomingMessage,ServerResponse} from 'node:http';
import {existsSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import type {Plugin} from 'vite';
import {isRole,type Role} from '../src/data/roles';
type AccountStatus='Activo'|'Inactivo'|'Bloqueado'|'Pendiente de activación';
type ProfileAccount={id:string,username:string,fullName:string,email:string,phone?:string,avatar?:string,role:Role,status:AccountStatus,lastAccess:string,createdAt:string,recentActivity:string,failedAttempts:number,protectedAccount:boolean,hasDependencies:boolean,deletedAt?:string,deletedBy?:string};
const usersFile=resolve(process.cwd(),'server/data/users.json');const auditFile=resolve(process.cwd(),'server/data/user-audit.json');
function readJson<T>(file:string,fallback:T):T{try{return existsSync(file)?JSON.parse(readFileSync(file,'utf8')) as T:fallback}catch{return fallback}}
function writeJson(file:string,data:unknown){mkdirSync(dirname(file),{recursive:true});writeFileSync(file,JSON.stringify(data,null,2),'utf8')}
function send(res:ServerResponse,status:number,data:unknown){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(data))}
function identity(req:IncomingMessage){const username=String(req.headers['x-sigadn-user']??'').trim();const role=String(req.headers['x-sigadn-role']??'');return username&&isRole(role)?{username,role}:undefined}
async function readBody(req:IncomingMessage){return new Promise<Record<string,unknown>>((resolveBody,reject)=>{let raw='';req.on('data',chunk=>raw+=String(chunk));req.on('end',()=>{try{resolveBody(raw?JSON.parse(raw) as Record<string,unknown>:{})}catch(error){reject(error)}})})}
function publicProfile(account:ProfileAccount){return{id:account.id,fullName:account.fullName,username:account.username,email:account.email,phone:account.phone??'',avatar:account.avatar??'',role:account.role,status:account.status,lastAccess:account.lastAccess,createdAt:account.createdAt}}
async function handleProfile(req:IncomingMessage,res:ServerResponse){const url=new URL(req.url??'','http://local');if(url.pathname!=='/api/profile')return false;const current=identity(req);if(!current){send(res,401,{error:'Sesión no válida.'});return true}const accounts=readJson<ProfileAccount[]>(usersFile,[]);let account=accounts.find(item=>item.username.toLowerCase()===current.username.toLowerCase());if(!account){const now=new Date().toISOString();const email=current.username.includes('@')?current.username:`${current.username}@local.sigadn`;account={id:crypto.randomUUID(),username:current.username,fullName:current.username.split('@')[0].replace(/[._-]/g,' ').replace(/\b\w/g,value=>value.toUpperCase()),email,phone:'',role:current.role,status:'Activo',lastAccess:now,createdAt:now,recentActivity:'Inicio de sesión local',failedAttempts:0,protectedAccount:false,hasDependencies:false};accounts.push(account);writeJson(usersFile,accounts)}
  if(req.method==='GET'){send(res,200,publicProfile(account));return true}
  if(req.method==='PATCH'){try{const data=await readBody(req);const fullName=String(data.fullName??'').trim();const email=String(data.email??'').trim().toLowerCase();const phone=String(data.phone??'').trim();if(fullName.length<2){send(res,400,{error:'El nombre completo es obligatorio.'});return true}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){send(res,400,{error:'Ingresa un correo válido.'});return true}const before=publicProfile(account);account.fullName=fullName;account.email=email;account.phone=phone;account.recentActivity='Perfil actualizado';writeJson(usersFile,accounts);const now=new Date();const entries=readJson<Record<string,unknown>[]>(auditFile,[]);entries.push({actor:current.username,target:current.username,action:'PROFILE_UPDATED',previousValues:before,newValues:publicProfile(account),date:now.toLocaleDateString('es-PE'),time:now.toLocaleTimeString('es-PE'),ip:req.socket.remoteAddress??'local',result:'Exitoso'});writeJson(auditFile,entries);send(res,200,publicProfile(account));return true}catch(error){send(res,500,{error:error instanceof Error?error.message:'Error al guardar el perfil.'});return true}}
  send(res,405,{error:'Método no permitido.'});return true}
export function profileApiPlugin():Plugin{return{name:'sigadn-profile-api',configureServer(server){server.middlewares.use(async(req,res,next)=>{if(!await handleProfile(req as unknown as IncomingMessage,res as unknown as ServerResponse))next()})}}}
