import type {IncomingMessage,ServerResponse} from 'node:http';
import {existsSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import type {Plugin} from 'vite';
import {hasPermission,rolesAssignableByNotary,type Permission} from '../src/data/permissions';
import {isRole,type Role} from '../src/data/roles';

export type AccountStatus='Activo'|'Inactivo'|'Bloqueado'|'Pendiente de activación';
export type UserAccount={id:string,username:string,fullName:string,email:string,role:Role,status:AccountStatus,lastAccess:string,createdAt:string,recentActivity:string,failedAttempts:number,protectedAccount:boolean,deletedAt?:string,deletedBy?:string,hasDependencies:boolean};
type Actor={username:string,role:Role};
type AuditEntry={actor:string,target:string,action:string,previousStatus?:AccountStatus,newStatus?:AccountStatus,previousRole?:Role,newRole?:Role,reason?:string,date:string,time:string,ip:string,result:'Exitoso'|'Error'};
const usersFile=resolve(process.cwd(),'server/data/users.json');const auditFile=resolve(process.cwd(),'server/data/user-audit.json');
function readJson<T>(file:string,fallback:T):T{try{return existsSync(file)?JSON.parse(readFileSync(file,'utf8')) as T:fallback}catch{return fallback}}
function writeJson(file:string,data:unknown){mkdirSync(dirname(file),{recursive:true});writeFileSync(file,JSON.stringify(data,null,2),'utf8')}
function users(){return readJson<UserAccount[]>(usersFile,[])}function saveUsers(value:UserAccount[]){writeJson(usersFile,value)}
function actor(req:IncomingMessage):Actor|undefined{const username=String(req.headers['x-sigadn-user']??'');const role=String(req.headers['x-sigadn-role']??'');return username&&isRole(role)?{username,role}:undefined}
function send(res:ServerResponse,status:number,data:unknown){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(data))}
async function body(req:IncomingMessage){return new Promise<Record<string,unknown>>((resolveBody,reject)=>{let raw='';req.on('data',chunk=>raw+=String(chunk));req.on('end',()=>{try{resolveBody(raw?JSON.parse(raw) as Record<string,unknown>:{})}catch(error){reject(error)}})})}
function requirePermission(current:Actor|undefined,permission:Permission,res:ServerResponse){if(!current||!hasPermission(current.role,permission)){send(res,403,{error:'No tiene permiso para realizar esta acción.'});return false}return true}
function audit(req:IncomingMessage,current:Actor,target:UserAccount,action:string,before:Partial<UserAccount>,reason:string|undefined,result:'Exitoso'|'Error'='Exitoso'){const now=new Date();const entries=readJson<AuditEntry[]>(auditFile,[]);entries.push({actor:current.username,target:target.username,action,previousStatus:before.status,newStatus:target.status,previousRole:before.role,newRole:target.role,reason,date:now.toLocaleDateString('es-PE'),time:now.toLocaleTimeString('es-PE'),ip:req.socket.remoteAddress??'local',result});writeJson(auditFile,entries)}
function administrative(user:UserAccount){return !user.deletedAt&&user.status==='Activo'&&(user.role==='Notario'||user.role==='Administrador')}
function sensitiveReason(data:Record<string,unknown>,res:ServerResponse){const reason=String(data.reason??'').trim();if(!reason){send(res,400,{error:'Debe indicar un motivo.'});return undefined}return reason}

async function handle(req:IncomingMessage,res:ServerResponse){const url=new URL(req.url??'','http://local');if(!url.pathname.startsWith('/api/users'))return false;const current=actor(req);const list=users();const match=url.pathname.match(/^\/api\/users\/([^/]+)(?:\/(activate|deactivate|block|unblock|reset-password|change-role))?$/);try{
  if(url.pathname==='/api/users'&&req.method==='GET'){if(!requirePermission(current,'users.view',res))return true;send(res,200,list);return true}
  if(url.pathname==='/api/users'&&req.method==='POST'){if(!requirePermission(current,'users.create',res))return true;const data=await body(req);const email=String(data.email??'').trim().toLowerCase();if(!email||list.some(item=>item.email===email)){send(res,409,{error:'El correo ya está registrado o no es válido.'});return true}const requested=String(data.role??'Secretaria');if(!isRole(requested)||(current?.role==='Notario'&&!rolesAssignableByNotary.includes(requested))){send(res,403,{error:'No puede asignar ese rol.'});return true}const now=new Date().toISOString();const created:UserAccount={id:crypto.randomUUID(),username:String(data.username??email.split('@')[0]),fullName:String(data.fullName??''),email,role:requested,status:'Pendiente de activación',lastAccess:'Sin acceso',createdAt:now,recentActivity:'Cuenta creada',failedAttempts:0,protectedAccount:false,hasDependencies:false};list.push(created);saveUsers(list);audit(req,current!,created,'CREAR USUARIO',{},String(data.reason??'Creación de cuenta'));send(res,201,created);return true}
  if(!match){send(res,404,{error:'Ruta no encontrada.'});return true}const id=decodeURIComponent(match[1]);const action=match[2];const index=list.findIndex(item=>item.id===id);if(index<0){send(res,404,{error:'Cuenta no encontrada.'});return true}const target=list[index];
  if(req.method==='GET'&&!action){if(!requirePermission(current,'users.view',res))return true;send(res,200,target);return true}
  if(req.method==='PATCH'&&!action){if(!requirePermission(current,'users.edit',res))return true;const data=await body(req);const before={...target};target.fullName=String(data.fullName??target.fullName);target.email=String(data.email??target.email);target.username=String(data.username??target.username);saveUsers(list);audit(req,current!,target,'EDITAR USUARIO',before,undefined);send(res,200,target);return true}
  if(req.method==='DELETE'&&!action){if(!requirePermission(current,'users.softDelete',res))return true;const data=await body(req);const reason=sensitiveReason(data,res);if(!reason)return true;if(target.username===current!.username){send(res,409,{error:'No puede eliminar su propia cuenta.'});return true}if(target.protectedAccount&&current!.role!=='Administrador'){send(res,403,{error:'La cuenta está protegida.'});return true}if(administrative(target)&&list.filter(administrative).length<=1){send(res,409,{error:'No puede eliminar la última cuenta administrativa activa.'});return true}const hard=url.searchParams.get('permanent')==='true';if(hard){if(!requirePermission(current,'users.hardDelete',res))return true;if(target.hasDependencies){send(res,409,{error:'La cuenta tiene dependencias y no puede eliminarse definitivamente.'});return true}list.splice(index,1);saveUsers(list);audit(req,current!,target,'ELIMINAR DEFINITIVAMENTE',{...target},reason);send(res,200,{deleted:true});return true}const before={...target};target.status='Inactivo';target.deletedAt=new Date().toISOString();target.deletedBy=current!.username;saveUsers(list);audit(req,current!,target,'ELIMINAR LÓGICAMENTE',before,reason);send(res,200,target);return true}
  if(req.method==='POST'&&action){const permission=(`users.${action==='reset-password'?'resetPassword':action==='change-role'?'changeRole':action}`) as Permission;if(!requirePermission(current,permission,res))return true;const data=await body(req);const before={...target};if((action==='deactivate'||action==='block')&&target.username===current!.username){send(res,409,{error:'No puede desactivar ni bloquear su propia cuenta.'});return true}if(target.protectedAccount&&current!.role!=='Administrador'&&(action==='deactivate'||action==='block'||action==='change-role')){send(res,403,{error:'La cuenta está protegida.'});return true}const reason=['deactivate','block','change-role'].includes(action)?sensitiveReason(data,res):String(data.reason??'');if(reason===undefined)return true;if((action==='deactivate'||action==='block')&&administrative(target)&&list.filter(administrative).length<=1){send(res,409,{error:'No puede inhabilitar la última cuenta administrativa activa.'});return true}if(action==='activate')target.status='Activo';if(action==='deactivate')target.status='Inactivo';if(action==='block')target.status='Bloqueado';if(action==='unblock')target.status='Activo';if(action==='reset-password')target.failedAttempts=0;if(action==='change-role'){const role=String(data.role??'');if(!isRole(role)||(current!.role==='Notario'&&!rolesAssignableByNotary.includes(role))){send(res,403,{error:'No puede asignar ese rol.'});return true}if(target.username===current!.username&&role==='Administrador'&&current!.role!=='Administrador'){send(res,403,{error:'No puede asignarse un rol superior.'});return true}target.role=role}saveUsers(list);audit(req,current!,target,action.toUpperCase(),before,reason);send(res,200,target);return true}
  send(res,405,{error:'Método no permitido.'});return true
}catch(error){send(res,500,{error:error instanceof Error?error.message:'Error interno'});return true}}
export function usersApiPlugin():Plugin{return{name:'sigadn-users-api',configureServer(server){server.middlewares.use(async(req,res,next)=>{if(!await handle(req as unknown as IncomingMessage,res as unknown as ServerResponse))next()})}}}
