import type {Request,Response} from 'express';
import {prisma} from '../config/prisma.js';
import {recordAudit} from '../services/audit.service.js';
import {HttpError} from '../utils/http.js';
const key='global';
const defaults={documentTypes:'Compraventa, Poder Notarial, Testamento, Escritura Pública, Sucesión Intestada',legalActs:'Compraventa, Poder, Testamento, Constitución, Sucesión',ocrThreshold:80,ocrLanguage:'Español',retries:2,automaticClassification:true,aiEnabled:true,institutionName:'Notaría Torres Zevallos',email:'',address:'',passwordLength:8,failedAttempts:5};
const clean=(input:Record<string,unknown>)=>({documentTypes:String(input.documentTypes??defaults.documentTypes).slice(0,4000),legalActs:String(input.legalActs??defaults.legalActs).slice(0,4000),ocrThreshold:Math.min(100,Math.max(1,Number(input.ocrThreshold)||defaults.ocrThreshold)),ocrLanguage:'Español',retries:Math.min(5,Math.max(0,Number(input.retries)||0)),automaticClassification:Boolean(input.automaticClassification),aiEnabled:Boolean(input.aiEnabled),institutionName:String(input.institutionName??'').trim().slice(0,200),email:String(input.email??'').trim().slice(0,200),address:String(input.address??'').trim().slice(0,500),passwordLength:Math.min(128,Math.max(8,Number(input.passwordLength)||8)),failedAttempts:Math.min(20,Math.max(1,Number(input.failedAttempts)||5))});
export async function getSettings(_req:Request,res:Response){const row=await prisma.systemSetting.findUnique({where:{key}});res.json({...defaults,...(row?.value as object|undefined)});}
export async function updateSettings(req:Request,res:Response){const value=clean(req.body as Record<string,unknown>);if(!value.institutionName)throw new HttpError(400,'El nombre de la notaría es obligatorio.');await prisma.systemSetting.upsert({where:{key},create:{key,value,updatedBy:req.auth!.userId},update:{value,updatedBy:req.auth!.userId}});await recordAudit(req,{action:'CONFIGURATION_UPDATED',module:'Configuración',targetType:'SystemSetting',targetId:key,detail:'Configuración administrativa central'});res.json(value);}
