import {AuditResult,Role,UserStatus,type User} from '@prisma/client';
import type {Request,Response} from 'express';
import {env} from '../config/env.js';
import {prisma} from '../config/prisma.js';
import {changeRoleSchema,createUserSchema,reasonSchema,updateUserSchema} from '../schemas/user.schemas.js';
import {recordAudit} from '../services/audit.service.js';
import {assertAssignableRole,assertCanManage,isActivePrivileged,privilegedRoles} from '../services/authorization.service.js';
import {HttpError} from '../utils/http.js';
import {hashPassword,temporaryPassword} from '../utils/security.js';

const safeUser=(user:User)=>{const {passwordHash,...safe}=user;void passwordHash;return safe};
const id=(req:Request)=>String(req.params.id);
async function target(req:Request){const user=await prisma.user.findUnique({where:{id:id(req)}});if(!user||user.deletedAt)throw new HttpError(404,'Usuario no encontrado.');return user}
async function ensureNotLastPrivileged(user:User){if(!isActivePrivileged(user))return;const count=await prisma.user.count({where:{role:{in:privilegedRoles},status:UserStatus.ACTIVO,deletedAt:null}});if(count<=1)throw new HttpError(409,'No se puede afectar la última cuenta privilegiada activa.');}
async function auditChange(req:Request,action:string,previous:User,updated:User,reason?:string){await recordAudit(req,{action,module:'Usuarios',targetType:'User',targetId:updated.id,detail:reason,oldValues:{status:previous.status,role:previous.role},newValues:{status:updated.status,role:updated.role}})}

export async function listUsers(req:Request,res:Response){const where={deletedAt:null,...(req.query.role?{role:String(req.query.role) as Role}:{}),...(req.query.status?{status:String(req.query.status) as UserStatus}:{})};const users=await prisma.user.findMany({where,orderBy:{createdAt:'desc'}});res.json(users.map(safeUser))}
export async function getUser(req:Request,res:Response){res.json(safeUser(await target(req)))}
export async function createUser(req:Request,res:Response){const input=createUserSchema.parse(req.body);assertAssignableRole(req.auth!.role,input.role);const password=temporaryPassword();const created=await prisma.user.create({data:{username:input.username.toLowerCase(),email:input.email.toLowerCase(),fullName:input.fullName,phone:input.phone,passwordHash:await hashPassword(password),role:input.role,status:input.status,passwordResetRequired:true,tempPasswordExpiresAt:new Date(Date.now()+env.PASSWORD_RESET_TEMP_EXPIRATION*3600000)}});await recordAudit(req,{action:'USER_CREATED',module:'Usuarios',targetType:'User',targetId:created.id,detail:input.reason,newValues:{username:created.username,email:created.email,role:created.role,status:created.status}});res.status(201).json({...safeUser(created),temporaryPassword:password})}
export async function updateUser(req:Request,res:Response){const previous=await target(req);assertCanManage({id:req.auth!.userId,role:req.auth!.role},previous,'edit');const input=updateUserSchema.parse(req.body);const updated=await prisma.user.update({where:{id:previous.id},data:{...input,email:input.email?.toLowerCase(),phone:input.phone||null}});await recordAudit(req,{action:'USER_UPDATED',module:'Usuarios',targetType:'User',targetId:updated.id,oldValues:{fullName:previous.fullName,email:previous.email,phone:previous.phone},newValues:{fullName:updated.fullName,email:updated.email,phone:updated.phone}});res.json(safeUser(updated))}

async function statusAction(req:Request,res:Response,status:UserStatus,action:string){const {reason}=reasonSchema.parse(req.body);const previous=await target(req);assertCanManage({id:req.auth!.userId,role:req.auth!.role},previous,'status');if(status!==UserStatus.ACTIVO)await ensureNotLastPrivileged(previous);const updated=await prisma.user.update({where:{id:previous.id},data:{status,failedLoginAttempts:status===UserStatus.ACTIVO?0:undefined}});if(status!==UserStatus.ACTIVO)await prisma.userSession.updateMany({where:{userId:previous.id,revokedAt:null},data:{revokedAt:new Date()}});const auditAction=status===UserStatus.ACTIVO&&previous.status===UserStatus.PENDIENTE?'USER_APPROVED':action;await auditChange(req,auditAction,previous,updated,reason);res.json(safeUser(updated))}
export const activateUser=(req:Request,res:Response)=>statusAction(req,res,UserStatus.ACTIVO,'USER_ACTIVATED');
export const deactivateUser=(req:Request,res:Response)=>statusAction(req,res,UserStatus.INACTIVO,'USER_DEACTIVATED');
export const blockUser=(req:Request,res:Response)=>statusAction(req,res,UserStatus.BLOQUEADO,'USER_BLOCKED');
export const unblockUser=(req:Request,res:Response)=>statusAction(req,res,UserStatus.ACTIVO,'USER_UNBLOCKED');
export async function rejectUser(req:Request,res:Response){const {reason}=reasonSchema.parse(req.body);const previous=await target(req);assertCanManage({id:req.auth!.userId,role:req.auth!.role},previous,'status');if(previous.status!==UserStatus.PENDIENTE)throw new HttpError(409,'Solo puede rechazarse una cuenta pendiente.');const updated=await prisma.user.update({where:{id:previous.id},data:{status:UserStatus.INACTIVO}});await auditChange(req,'USER_REJECTED',previous,updated,reason);res.json(safeUser(updated))}

export async function resetPassword(req:Request,res:Response){const {reason}=reasonSchema.parse(req.body);const previous=await target(req);assertCanManage({id:req.auth!.userId,role:req.auth!.role},previous,'edit');const password=temporaryPassword();await prisma.$transaction([prisma.user.update({where:{id:previous.id},data:{passwordHash:await hashPassword(password),passwordResetRequired:true,tempPasswordExpiresAt:new Date(Date.now()+env.PASSWORD_RESET_TEMP_EXPIRATION*3600000)}}),prisma.userSession.updateMany({where:{userId:previous.id,revokedAt:null},data:{revokedAt:new Date()}})]);await recordAudit(req,{action:'PASSWORD_RESET',module:'Usuarios',targetType:'User',targetId:previous.id,detail:reason});res.json({temporaryPassword:password,expiresInHours:env.PASSWORD_RESET_TEMP_EXPIRATION})}
export async function changeRole(req:Request,res:Response){const input=changeRoleSchema.parse(req.body);const previous=await target(req);assertCanManage({id:req.auth!.userId,role:req.auth!.role},previous,'role');assertAssignableRole(req.auth!.role,input.role);if(isActivePrivileged(previous)&&!privilegedRoles.includes(input.role))await ensureNotLastPrivileged(previous);const updated=await prisma.user.update({where:{id:previous.id},data:{role:input.role}});await auditChange(req,'USER_ROLE_CHANGED',previous,updated,input.reason);res.json(safeUser(updated))}
export async function deleteUser(req:Request,res:Response){const {reason}=reasonSchema.parse(req.body);const previous=await target(req);assertCanManage({id:req.auth!.userId,role:req.auth!.role},previous,'delete');await ensureNotLastPrivileged(previous);const updated=await prisma.user.update({where:{id:previous.id},data:{status:UserStatus.INACTIVO,deletedAt:new Date(),deletedBy:req.auth!.userId}});await prisma.userSession.updateMany({where:{userId:previous.id,revokedAt:null},data:{revokedAt:new Date()}});await auditChange(req,'USER_SOFT_DELETED',previous,updated,reason);res.json(safeUser(updated))}

export async function forbiddenPermanentDelete(req:Request,res:Response){await recordAudit(req,{action:'USER_HARD_DELETE_ATTEMPT',module:'Usuarios',targetType:'User',targetId:id(req),result:AuditResult.DENEGADO});res.status(403).json({error:'La eliminación definitiva no está habilitada en esta etapa.'})}
