/* eslint-disable @typescript-eslint/no-unused-vars */
import {useEffect,useMemo,useState} from 'react';
import {AlertTriangle,Check,FileCheck2,LoaderCircle,RotateCcw,ScanLine,Upload,X} from 'lucide-react';
import * as pdfjs from 'pdfjs-dist';
import {useNavigate} from 'react-router-dom';
import {saveDocument,type DocumentMode, type DocumentRecord} from '../data/repository';
import {useDocuments} from '../hooks/useDocuments';
import {cancelProcessing,uploadTemporary,updateQuality} from '../services/documentsApi';
import {actualStages,historicalStages,processDocument,type ExtractionField,type ExtractionKey,type OcrResult} from '../services/documentOcr';
import './digitalizacion.css';
import '../styles/digitalization-workflow.css';

type Phase='config'|'quality'|'processing'|'validation';
const types=['Compraventa','Poder Notarial','Testamento','Escritura Pública','Sucesión Intestada','Otros'];

export function DigitalizacionProcess(){
  const {documents,refresh}=useDocuments();const navigate=useNavigate();const [mode,setMode]=useState<DocumentMode>('actual');const [type,setType]=useState('');const [periodType,setPeriodType]=useState<'ano'|'bienio'>('ano');const [period,setPeriod]=useState(String(new Date().getFullYear()));const [tomo,setTomo]=useState('');const [fojaInicial,setFojaInicial]=useState('');const [fojaFinal,setFojaFinal]=useState('');const [file,setFile]=useState<File>();const [phase,setPhase]=useState<Phase>('config');const [pages,setPages]=useState(0);const [qualityIssue,setQualityIssue]=useState('');const [active,setActive]=useState(0);const [progress,setProgress]=useState(0);const [fields,setFields]=useState<ExtractionField[]>([]);const [result,setResult]=useState<OcrResult>();const [reviewOnly,setReviewOnly]=useState(true);const [message,setMessage]=useState('');const [saving,setSaving]=useState(false);const [savedId,setSavedId]=useState<string>();const [jobId,setJobId]=useState<string>();
  const ready=Boolean(type&&period&&tomo&&(periodType==='ano'||(fojaInicial&&fojaFinal)));const stages=mode==='historico'?historicalStages:actualStages;
  useEffect(()=>{if(!file)return;let alive=true;void file.arrayBuffer().then(bytes=>pdfjs.getDocument({data:new Uint8Array(bytes)}).promise).then(pdf=>{if(alive)setPages(pdf.numPages)}).catch(()=>{if(alive)setQualityIssue('No se pudo leer el PDF para control de calidad.')});return()=>{alive=false}},[file]);
  async function selectFile(value?:File){if(!value)return;if(value.type!=='application/pdf'&&!value.name.toLowerCase().endsWith('.pdf')){setMessage('Solo se permiten archivos PDF.');return}if(value.size>50*1024*1024){setMessage('El PDF supera 50 MB.');return}setFile(value);setMessage('Archivo recibido.');setQualityIssue('');try{const job=await uploadTemporary(value,value.name);setJobId(job.jobId);setPages(job.pageCount);setPhase('quality')}catch(error){setMessage(error instanceof Error?error.message:'No se pudo recibir el PDF en el servidor.');setFile(undefined)}}
  async function process(){if(!file)return;setPhase('processing');const extracted=await processDocument(file,{mode,bienio:periodType==='bienio'?period:undefined,tomo,fojaInicial,fojaFinal,existing:documents,onStage:(index,value=100)=>{setActive(index);setProgress(value)}});setResult(extracted);setFields(extracted.fields);setPhase('validation')}
  function reset(){setFile(undefined);setFields([]);setResult(undefined);setPhase('config');setMessage('');setQualityIssue('')}
  async function save(andContinue=false){if(!file||!result)return;const value=(key:ExtractionKey)=>fields.find(item=>item.key===key)?.value;const escritura=String(value('escritura')||'').trim();const acto=String(value('acto')||'').trim();const contractors=Array.isArray(value('contratantes'))?value('contratantes') as string[]:[];if(!escritura||!acto||!contractors.length){setMessage('Revisa los campos que requieren corrección antes de guardar.');setReviewOnly(true);return}setSaving(true);const record:DocumentRecord={id:Date.now(),documentMode:mode,tipo:type,ano:periodType==='ano'?Number(period):undefined,bienio:periodType==='bienio'?period:undefined,tomo,fojaInicial:Number(value('fojaInicial')||fojaInicial)||undefined,fojaFinal:Number(value('fojaFinal')||fojaFinal)||undefined,numeroMinuta:String(value('minuta')||''),actoJuridico:acto,kardex:String(value('kardex')||''),escritura,contratantes:contractors,observaciones:String(value('observaciones')||''),fecha:String(value('fecha')||''),fechaRegistro:new Date().toLocaleDateString('es-PE'),cantidadPaginas:Number(value('paginas'))||pages,ubicacionHistorica:mode==='historico'?'Bienio '+period:undefined,documento:fields.some(item=>item.review)?'En revisión':'Validado',ocr:'Procesado',confianza:result.averageConfidence,fileName:file.name,fileSize:file.size,file,source:'manual',processingJobId:jobId};(record as DocumentRecord & {ocrFields?:unknown}).ocrFields=fields;const saved=await saveDocument(record);await refresh();setSaving(false);setSavedId(saved.backendId);setMessage('Documento registrado correctamente.');if(andContinue)reset()}
  return <div className="page-content digitPage"><section className="card config historicalConfig"><div className="stepHeading"><span>1</span><h2 className="section-title">Configuración mínima</h2></div><div className="documentMode"><button className={mode==='actual'?'active':''} disabled={phase!=='config'} onClick={()=>setMode('actual')}>Escanear documento</button><button className={mode==='historico'?'active':''} disabled={phase!=='config'} onClick={()=>setMode('historico')}>Importar archivos existentes</button></div><div className="configGrid"><label>Tipo documental<select className="field" value={type} onChange={event=>setType(event.target.value)}><option value="">Seleccionar tipo...</option>{types.map(item=><option key={item}>{item}</option>)}</select></label><label>Organización del período *<select className="field" value={periodType} onChange={event=>setPeriodType(event.target.value as 'ano'|'bienio')}><option value="ano">Por año</option><option value="bienio">Por bienio</option></select></label><label>Año del documento o Bienio<input className="field" value={period} onChange={event=>setPeriod(event.target.value)}/></label><label>Tomo<input className="field" value={tomo} onChange={event=>setTomo(event.target.value)}/></label><label>Foja inicial y final<input className="field" value={fojaInicial} onChange={event=>setFojaInicial(event.target.value)} placeholder="Inicial"/><input className="field" value={fojaFinal} onChange={event=>setFojaFinal(event.target.value)} placeholder="Final"/></label></div></section>{phase==='config'&&<section className="card uploadCard"><div className="stepHeading"><span>2</span><h2 className="section-title">Escanear o cargar documento</h2></div><button className="btn primary" disabled={!ready} onClick={()=>document.getElementById('real-pdf-input')?.click()}><ScanLine size={16}/>Escanear documento</button><button className="btn" disabled={!ready} onClick={()=>document.getElementById('real-pdf-input')?.click()}><Upload size={16}/>Subir PDF</button><input id="real-pdf-input" hidden type="file" accept="application/pdf,.pdf" onChange={event=>selectFile(event.target.files?.[0])}/></section>}{phase==='quality'&&file&&<QualityStep file={file} pages={pages} issue={qualityIssue} onIssue={setQualityIssue} onContinue={()=>{void (async()=>{if(jobId)await updateQuality(jobId,qualityIssue?[{pageNumber:1,issueType:'LOW_SHARPNESS',severity:'WARNING',message:qualityIssue,suggestedAction:'Volver a escanear'}]:[],Boolean(qualityIssue));await process()})()}} onCancel={reset}/>}<p>{message}</p>{savedId&&<div className="saveSuccessActions"><button className="btn" onClick={()=>navigate(`/visor/${savedId}`)}>Ver documento</button><button className="btn" onClick={()=>navigate(`/documentos`)}>Ir a Gestión Documental</button><button className="btn primary" onClick={()=>{setSavedId(undefined);reset()}}>Digitalizar otro</button></div>}</div>
}

function QualityStep({file,pages,issue,onIssue,onContinue,onCancel}:{file:File;pages:number;issue:string;onIssue:(value:string)=>void;onContinue:()=>void;onCancel:()=>void}){const [url]=useState(()=>URL.createObjectURL(file));const pageCount=Math.max(1,pages);const pageLabel=pageCount===1?'1 página':`${pageCount} páginas`;return <section className="card qualityCard"><div className="stepHeading"><span>3</span><h2 className="section-title">Control de calidad previo</h2></div><p className="qualityFile">{file.name} · {pageLabel}</p><div className="qualityLayout"><div className="qualityThumbs">{Array.from({length:pageCount},(_,index)=><button key={index} className="qualityThumb" onClick={()=>onIssue('')}><span>Página {index+1}</span><FileCheck2/></button>)}</div><div className="qualityPreview"><iframe title="Vista previa del PDF" src={url}/></div><aside className="qualityIssues"><h3>Incidencias detectadas</h3>{issue?<p><AlertTriangle/>Página 1 — {issue}</p>:<p className="qualityOk"><Check/>No se han detectado incidencias automáticas.</p>}<button className="btn" onClick={()=>onIssue('Baja nitidez. Se recomienda volver a escanear.')}>Marcar incidencia</button></aside></div><footer className="qualityActions"><button className="btn" onClick={onCancel}>Cancelar</button><button className="btn" onClick={()=>onIssue('Baja nitidez. Se recomienda volver a escanear.')}>Corregir páginas</button><button className="btn primary" onClick={onContinue}>Continuar de todas formas</button></footer></section>}








