import {useMemo,useState} from 'react';
import {Bot,Eye,Info,Search} from 'lucide-react';
import {useNavigate,useSearchParams} from 'react-router-dom';
import type {DocumentRecord} from '../data/repository';
import {useDocuments} from '../hooks/useDocuments';
import './documents.css';

const searchable=(value:unknown)=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es-PE');
const period=(doc:DocumentRecord)=>String(doc.ano??doc.bienio??'—');
const folios=(doc:DocumentRecord)=>doc.fojaInicial||doc.fojaFinal?`${doc.fojaInicial??'—'} – ${doc.fojaFinal??'—'}`:'—';
const instrument=(doc:DocumentRecord)=>[doc.tipo,doc.escritura].filter(Boolean).join(' · ')||'—';
const related=(doc:DocumentRecord)=>doc.relatedDocuments?.map(item=>`${item.tipo}: ${item.fileName}`).join('; ')||'—';

export function Documentos(){
 const navigate=useNavigate();const [params]=useSearchParams();const {documents,loading,error,refresh}=useDocuments(false);const [query,setQuery]=useState(params.get('q')??'');const [page,setPage]=useState(1);const pageSize=10;
 const registered=useMemo(()=>documents.filter(doc=>doc.documentMode==='actual').sort((a,b)=>new Date(b.fechaRegistro).getTime()-new Date(a.fechaRegistro).getTime()),[documents]);
 const filtered=useMemo(()=>{const needle=searchable(query.trim());return needle?registered.filter(doc=>searchable([doc.fileName,doc.kardex,...doc.contratantes,doc.numeroMinuta,doc.tipo,doc.actoJuridico,doc.escritura,doc.tomo,doc.ano,doc.bienio].join(' ')).includes(needle)):registered},[query,registered]);
 const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));const currentPage=Math.min(page,totalPages);const shown=filtered.slice((currentPage-1)*pageSize,currentPage*pageSize);
 function showData(doc:DocumentRecord){window.alert([`Archivo: ${doc.fileName}`,`Clase documental: ${doc.tipo||'—'}`,`Kardex: ${doc.kardex||'—'}`,`Contratante principal: ${doc.contratantes[0]||'—'}`,`Acto jurídico: ${doc.actoJuridico||'—'}`,`Instrumento: ${instrument(doc)}`,`Tomo: ${doc.tomo||'—'}`,`Foja: ${folios(doc)}`,`Año o bienio: ${period(doc)}`,`Documento relacionado: ${related(doc)}`,`Estado de relación: ${doc.relationStatus||'Kardex sin confirmar'}`,`Fecha de registro: ${new Date(doc.fechaRegistro).toLocaleString('es-PE')}`].join('\n'))}
 if(!loading&&error)return <div className="page-content docsPage"><section className="card tableCard documentsTableCard"><div className="documentsEmpty compactDocumentsEmpty"><p>No se pudieron cargar los documentos: {error}</p><button className="btn" onClick={()=>void refresh()}>Reintentar</button></div></section></div>;
 const columns=['Nombre del PDF','Clase documental','Kardex','Contratante principal','Acto jurídico','Instrumento','Tomo','Foja','Año o bienio','Fecha de registro','Documento relacionado','Estado de relación','Acción'];
 return <div className="page-content docsPage"><section className="card documentsControls simpleDocumentsControls"><div className="docSearch"><Search size={15}/><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="Buscar por archivo, kardex, contratante, minuta, instrumento, tomo o periodo..."/></div><button className="btn documentsAiButton" onClick={()=>navigate('/asistente?scope=documents')}><Bot size={14}/>Consultar con IA</button></section><section className="card tableCard documentsTableCard">
 {loading?<div className="documentsLoading">Leyendo documentos registrados…</div>:registered.length===0?<div className="documentsEmpty compactDocumentsEmpty"><p>No hay documentos registrados todavía.</p><button className="btn" onClick={()=>navigate('/digitalizacion')}>Ir al Centro de Digitalización</button></div>:shown.length===0?<div className="documentsEmpty compactDocumentsEmpty"><p>No se encontraron documentos con esa búsqueda.</p></div>:<><div className="tableViewport"><table className="documentsTable"><thead><tr>{columns.map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{shown.map(doc=><tr key={doc.id}><td className="documentFileName">{doc.fileName}</td><td>{doc.tipo||'—'}</td><td>{doc.kardex||'—'}</td><td>{doc.contratantes[0]||'—'}</td><td>{doc.actoJuridico||'—'}</td><td>{instrument(doc)}</td><td>{doc.tomo||'—'}</td><td>{folios(doc)}</td><td>{period(doc)}</td><td>{new Date(doc.fechaRegistro).toLocaleString('es-PE')}</td><td>{related(doc)}</td><td>{doc.relationStatus||'Kardex sin confirmar'}</td><td><div className="documentPrimaryActions"><button className="btn" onClick={()=>navigate('/visor/'+doc.id)}><Eye/>Ver PDF</button><button className="btn" onClick={()=>showData(doc)}><Info/>Ver datos</button></div></td></tr>)}</tbody></table></div>{totalPages>1&&<footer className="documentsPagination"><span>Página {currentPage} de {totalPages} · {filtered.length} registros</span><div><button disabled={currentPage<=1} onClick={()=>setPage(value=>value-1)}>‹</button><button disabled={currentPage>=totalPages} onClick={()=>setPage(value=>value+1)}>›</button></div></footer>}</>}
 </section></div>;
}
