import {useEffect,useMemo,useState} from 'react';
import {Bot,Eye,Info,MoreVertical,Search,Trash2,X} from 'lucide-react';
import {useNavigate,useSearchParams} from 'react-router-dom';
import {useAuth} from '../auth/AuthContext';
import {softDeleteDocument,type DocumentRecord} from '../data/repository';
import {useDocuments} from '../hooks/useDocuments';
import {documentTableFolio} from '../services/documentFolio';
import {cancelAttentionJob,listAttentionJobs,retryAttentionJob,type AttentionJob} from '../services/documentsApi';
import {addNotification} from '../services/notifications';
import {hasProcessingError,lacksOcrProcessing,needsDocumentReview} from '../utils/dashboardMetrics';
import './documents.css';

const searchable=(value:unknown)=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es-PE');
const period=(doc:DocumentRecord)=>String(doc.ano??doc.bienio??'—');
const folios=documentTableFolio;
const instrument=(doc:DocumentRecord)=>[doc.tipo,doc.escritura].filter(Boolean).join(' · ')||'—';
const related=(doc:DocumentRecord)=>doc.relatedDocuments?.map(item=>`${item.tipo}: ${item.fileName}`).join('; ')||'—';
const reasons=['Documento duplicado','Documento incorrecto','Prueba del sistema','Otro'] as const;

export function Documentos(){
 const navigate=useNavigate();const {user}=useAuth();const [params]=useSearchParams();const attention=params.get('attention');const {documents,loading,error,refresh}=useDocuments(false);const [query,setQuery]=useState(params.get('q')??'');const [page,setPage]=useState(1);const [menu,setMenu]=useState<number>();const [menuPosition,setMenuPosition]=useState<{top:number;left:number}>({top:0,left:0});const [selected,setSelected]=useState<DocumentRecord>();const [reason,setReason]=useState('');const [otherReason,setOtherReason]=useState('');const [deleting,setDeleting]=useState(false);const [deleteError,setDeleteError]=useState('');const [notice,setNotice]=useState('');const pageSize=10;
 const canDelete=user?.role==='Notario'||user?.role==='Administrador';
 const [jobs,setJobs]=useState<AttentionJob[]>([]);
 useEffect(()=>{if(attention)void listAttentionJobs().then(setJobs).catch(()=>setJobs([]))},[attention]);
 const visibleJobs=jobs.filter(job=>attention==='review'?['UPLOADED','QUALITY_ANALYSIS','QUALITY_REVIEW','REVIEW_REQUIRED','READY_TO_SAVE'].includes(job.status):attention==='ocr-pending'?['OCR_PENDING','OCR_PROCESSING'].includes(job.status):attention==='ocr-error'?job.status==='FAILED':false);
 async function actOnJob(job:AttentionJob,action:'retry'|'cancel'){try{if(action==='retry')await retryAttentionJob(job.id);else await cancelAttentionJob(job.id);setJobs(await listAttentionJobs())}catch(cause){setNotice(cause instanceof Error?cause.message:'No se pudo actualizar la carga.')}}
 const registered=useMemo(()=>documents.sort((a,b)=>new Date(b.fechaRegistro).getTime()-new Date(a.fechaRegistro).getTime()),[documents]);
 const filtered=useMemo(()=>{let rows=attention==='review'?registered.filter(needsDocumentReview):attention==='ocr-pending'?registered.filter(lacksOcrProcessing):attention==='ocr-error'?registered.filter(hasProcessingError):registered;const needle=searchable(query.trim());if(needle)rows=rows.filter(doc=>searchable([doc.fileName,doc.kardex,...doc.contratantes,doc.numeroMinuta,doc.tipo,doc.actoJuridico,doc.escritura,doc.tomo,doc.ano,doc.bienio].join(' ')).includes(needle));return rows},[query,registered,attention]);
 const totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));const currentPage=Math.min(page,totalPages);const shown=filtered.slice((currentPage-1)*pageSize,currentPage*pageSize);
 function showData(doc:DocumentRecord){setMenu(undefined);window.alert([`Archivo: ${doc.fileName}`,`Clase documental: ${doc.tipo||'—'}`,`Kardex: ${doc.kardex||'—'}`,`Contratante principal: ${doc.contratantes[0]||'—'}`,`Acto jurídico: ${doc.actoJuridico||'—'}`,`Instrumento: ${instrument(doc)}`,`Tomo: ${doc.tomo||'—'}`,`Foja: ${folios(doc)}`,`Año o bienio: ${period(doc)}`,`Documento relacionado: ${related(doc)}`,`Estado de relación: ${doc.relationStatus||'Kardex sin confirmar'}`,`Fecha de registro: ${new Date(doc.fechaRegistro).toLocaleString('es-PE')}`].join('\n'))}
 function openDelete(doc:DocumentRecord){setMenu(undefined);setSelected(doc);setReason('');setOtherReason('');setDeleteError('')}
 function closeDelete(){if(deleting)return;setSelected(undefined);setDeleteError('')}
 async function confirmDelete(){if(!selected)return;const finalReason=reason==='Otro'?otherReason.trim():reason;if(!finalReason){setDeleteError('Seleccione e indique un motivo de eliminación.');return}setDeleting(true);setDeleteError('');try{const fileName=selected.fileName;await softDeleteDocument(selected.id,finalReason);setSelected(undefined);setNotice('Documento eliminado correctamente.');addNotification('delete','Documento eliminado',fileName);await refresh()}catch(cause){setDeleteError(cause instanceof Error?cause.message:'No se pudo eliminar el documento.')}finally{setDeleting(false)}}
 if(!loading&&error)return <div className="page-content docsPage"><section className="card tableCard documentsTableCard"><div className="documentsEmpty compactDocumentsEmpty"><p>No se pudieron cargar los documentos: {error}</p><button className="btn" onClick={()=>void refresh()}>Reintentar</button></div></section></div>;
 const columns=['Nombre del PDF','Clase documental','Kardex','Contratante principal','Acto jurídico','Instrumento','Tomo','Foja','Año o bienio','Fecha de registro','Documento relacionado','Estado de relación','Acción'];
 return <div className="page-content docsPage" onClick={()=>setMenu(undefined)}><section className="card documentsControls simpleDocumentsControls"><div className="docSearch"><Search size={15}/><input value={query} onChange={event=>{setQuery(event.target.value);setPage(1)}} placeholder="Buscar por archivo, kardex, contratante, minuta, instrumento, tomo o periodo..."/></div><button className="btn documentsAiButton" onClick={()=>navigate('/asistente?scope=documents')}><Bot size={14}/>Consultar con IA</button></section>{attention&&<section className="card attentionJobList"><h3>Cargas que requieren atención</h3>{visibleJobs.length===0?<p>No hay cargas sin confirmar en esta categoría.</p>:visibleJobs.map(job=><article key={job.id}><div><b>{job.originalFileName}</b><small>{job.pageCount} páginas ? {job.status.replaceAll('_',' ')} ? {new Date(job.createdAt).toLocaleString('es-PE')}</small>{job.errorMessage&&<small>{job.errorMessage}</small>}</div>{job.status==='FAILED'&&<button className="btn" onClick={()=>void actOnJob(job,'retry')}>Reintentar OCR</button>}<button className="btn" onClick={()=>navigate('/digitalizacion')}>Ir a Digitalización</button><button className="btn" onClick={()=>void actOnJob(job,'cancel')}>Descartar carga</button></article>)}</section>}{notice&&<p className="documentsNotice" role="status">{notice}</p>}<section className="card tableCard documentsTableCard">
 {loading?<div className="documentsLoading">Leyendo documentos registrados…</div>:registered.length===0?<div className="documentsEmpty compactDocumentsEmpty"><p>No hay documentos registrados todavía.</p><button className="btn" onClick={()=>navigate('/digitalizacion')}>Ir al Centro de Digitalización</button></div>:shown.length===0?<div className="documentsEmpty compactDocumentsEmpty"><p>No se encontraron documentos con esa búsqueda.</p></div>:<><div className="tableViewport"><table className="documentsTable"><thead><tr>{columns.map(label=><th key={label}>{label}</th>)}</tr></thead><tbody>{shown.map(doc=><tr key={doc.id}><td className="documentFileName">{doc.fileName}</td><td>{doc.tipo||'—'}</td><td>{doc.kardex||'—'}</td><td>{doc.contratantes[0]||'—'}</td><td>{doc.actoJuridico||'—'}</td><td>{instrument(doc)}</td><td>{doc.tomo||'—'}</td><td>{folios(doc)}</td><td>{period(doc)}</td><td>{new Date(doc.fechaRegistro).toLocaleString('es-PE')}</td><td>{related(doc)}</td><td>{doc.relationStatus||'Kardex sin confirmar'}</td><td><div className="documentPrimaryActions"><button className="btn" onClick={()=>navigate('/visor/'+(doc.backendId??doc.id))}><Eye/>Ver PDF</button><div className="documentActionsMenu"><button className="btn iconButton" aria-label="Más acciones" aria-expanded={menu===doc.id} onClick={event=>{event.stopPropagation();setMenuPosition({top:Math.min(event.currentTarget.getBoundingClientRect().bottom+5,window.innerHeight-100),left:Math.max(8,event.currentTarget.getBoundingClientRect().right-180)});setMenu(value=>value===doc.id?undefined:doc.id)}}><MoreVertical/></button>{menu===doc.id&&<div className="documentActionsDropdown" style={menuPosition} role="menu" onClick={event=>event.stopPropagation()}><button role="menuitem" onClick={()=>showData(doc)}><Info/>Ver información</button>{canDelete&&<button className="dangerItem" role="menuitem" onClick={()=>openDelete(doc)}><Trash2/>Eliminar documento</button>}</div>}</div></div></td></tr>)}</tbody></table></div>{totalPages>1&&<footer className="documentsPagination"><span>Página {currentPage} de {totalPages} · {filtered.length} registros</span><div><button disabled={currentPage<=1} onClick={()=>setPage(value=>value-1)}>‹</button><button disabled={currentPage>=totalPages} onClick={()=>setPage(value=>value+1)}>›</button></div></footer>}</>}
 </section>{selected&&<div className="modalBackdrop" role="presentation"><section className="card documentDeleteModal" role="dialog" aria-modal="true" aria-labelledby="delete-document-title"><header><div><h2 id="delete-document-title">Eliminar documento</h2><p>¿Está seguro de que desea eliminar este documento?</p></div><button type="button" aria-label="Cerrar" disabled={deleting} onClick={closeDelete}><X/></button></header><p>El documento dejará de aparecer en Gestión Documental y Gestión de Tomos. Esta acción quedará registrada en Auditoría.</p>{['Documento duplicado','Documento incorrecto'].includes(reason)&&<p className="permanentDeleteNotice">Este motivo eliminará definitivamente el PDF y liberará el archivo para volver a cargarlo.</p>}<dl><dt>Nombre del archivo</dt><dd>{selected.fileName}</dd><dt>Kardex</dt><dd>{selected.kardex||'—'}</dd><dt>Tipo documental</dt><dd>{selected.tipo||'—'}</dd><dt>Año o bienio</dt><dd>{period(selected)}</dd><dt>Tomo</dt><dd>{selected.tomo||'—'}</dd></dl><label>Motivo de eliminación *<select className="field" value={reason} onChange={event=>{setReason(event.target.value);setDeleteError('')}}><option value="">Seleccionar motivo…</option>{reasons.map(value=><option key={value}>{value}</option>)}</select></label>{reason==='Otro'&&<label>Explicación *<textarea className="field" maxLength={250} value={otherReason} onChange={event=>{setOtherReason(event.target.value);setDeleteError('')}} placeholder="Indique brevemente el motivo"/></label>}{deleteError&&<p className="validationError" role="alert">{deleteError}</p>}<footer><button className="btn" disabled={deleting} onClick={closeDelete}>Cancelar</button><button className="btn danger" disabled={deleting||!reason||(reason==='Otro'&&!otherReason.trim())} onClick={()=>void confirmDelete()}>{deleting?'Eliminando…':'Eliminar documento'}</button></footer></section></div>}</div>;
}
