import {useState} from 'react';
import {Archive,ArrowRight,Eye,EyeOff} from 'lucide-react';
import {Navigate,useNavigate} from 'react-router-dom';
import {useAuth} from '../auth/AuthContext';
import {Brand} from '../components/Brand';
import {RegisterModal} from '../components/RegisterModal';
import bovedaNtz from '../../src-tauri/icons/Square310x310Logo.png';
import './login.css';
export function Login(){
  const navigate=useNavigate();const {user,loading,login}=useAuth();const remembered=localStorage.getItem('sigadn-remembered-username')??'';const [email,setEmail]=useState(remembered);const [password,setPassword]=useState('');const [showPassword,setShowPassword]=useState(false);const [remember,setRemember]=useState(Boolean(remembered));const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [registerOpen,setRegisterOpen]=useState(false);
  if(!loading&&user)return <Navigate to="/dashboard" replace/>;
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError('');try{await login(email.trim().toLowerCase(),password);if(remember)localStorage.setItem('sigadn-remembered-username',email.trim().toLowerCase());else localStorage.removeItem('sigadn-remembered-username');navigate('/dashboard')}catch(cause){setError(cause instanceof Error?cause.message:'No fue posible iniciar sesión.')}finally{setBusy(false)}}
  return <div className="loginPage"><section className="loginHero"><Brand light/><div className="heroCopy"><h1>Sistema Inteligente<br/>de Gestión y Archivo<br/>Documental<br/>Notarial</h1><ul><li><Archive/>Archivos PDF conservados localmente</li></ul><img className="loginVaultLogo" src={bovedaNtz} alt="Bóveda - NTZ"/></div><small>Notaría Torres Zevallos · Sistema de uso interno · Bóveda</small></section><section className="loginMain"><form className="loginCard card" onSubmit={submit}><div className="eyebrow">ACCESO SEGURO</div><h2>Iniciar sesión</h2><p>Tu rol y permisos se asignan automáticamente a tu cuenta</p><label>CORREO</label><input className="field" required type="email" autoComplete="username" value={email} onChange={event=>setEmail(event.target.value)} placeholder="usuario@notariatorreszevallos.pe"/><label>CONTRASEÑA</label><div className="password"><input className="field" required minLength={8} autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)} type={showPassword?'text':'password'} placeholder="••••••••"/><button type="button" aria-label={showPassword?'Ocultar contraseña':'Mostrar contraseña'} onClick={()=>setShowPassword(value=>!value)}>{showPassword?<EyeOff size={16}/>:<Eye size={16}/>}</button></div>{error&&<div className="loginError" role="alert">{error}</div>}<div className="remember"><span><input type="checkbox" checked={remember} onChange={event=>setRemember(event.target.checked)}/> Recordar correo</span><button type="button" className="forgotButton" onClick={()=>window.alert('Solicita el restablecimiento al Notario autorizado.')}>¿Olvidó su contraseña?</button></div><button className="btn primary submit" disabled={busy}><ArrowRight size={17}/>{busy?'Verificando…':'Iniciar sesión'}</button><div className="registrationPrompt">¿No tienes una cuenta? <button type="button" onClick={()=>setRegisterOpen(true)}>Crear cuenta</button></div></form><div className="security"><span>♧ Acceso auditado</span><span>♙ Sesión segura</span></div></section>{registerOpen&&<RegisterModal onClose={()=>setRegisterOpen(false)}/>}</div>;
}

