import {useEffect,useMemo,useState} from 'react';
import {Download} from 'lucide-react';
import {getDocumentReport,type ReportResponse} from '../services/reportsApi';
import {csvCell,downloadText} from '../utils/client';
import {documentStatusLabel,ocrStatusLabel} from '../utils/statusLabels';
import './reports.css';
const colors=['#c8a64b','#e7d08a','#3a8f5d','#d99b12','#956b0c','#c9c9c9'];const months=['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep','Oct','Nov','Dic'];
const empty:ReportResponse={documents:[],options:{periods:[],tomes:[],types:[]},total:0,totalBytes:0};
export function Reportes(){
 const [period,setPeriod]=useState('');const [tome,setTome]=useState('');const [type,setType]=useState('');const [status,setStatus]=useState('CONFIRMED');const [report,setReport]=useState<ReportResponse>(empty);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(active){setLoading(true);setError('')}});void getDocumentReport({period,tome,type,status}).then(data=>{if(active)setReport(data)}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:'No se pudo cargar el reporte.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[period,tome,type,status]);
 const monthly=useMemo(()=>Array.from({length:12},(_,index)=>report.documents.filter(doc=>new Date(doc.createdAt).getMonth()===index).length),[report.documents]);const maxMonth=Math.max(1,...monthly);const points=monthly.map((value,index)=>`${30+index*58},${190-value/maxMonth*150}`).join(' ');const typeCounts=[...new Set(report.documents.map(doc=>doc.documentType))].map(name=>[name,report.documents.filter(doc=>doc.documentType===name).length] as const);const maxType=Math.max(1,...typeCounts.map(([,count])=>count));
 function exportCsv(){const header=['Archivo','Clase','Tipo','Año/Bienio','Tomo','Foja exacta','Minuta','Acto jurídico','Kardex','Escritura','Contratantes','Observaciones','Estado','Lectura documental','Tamaño','Fecha de registro'];const rows=report.documents.map(doc=>[doc.displayName,doc.documentMode,doc.documentType,doc.year??doc.biennium??(doc.bienniumStart&&doc.bienniumEnd?`${doc.bienniumStart}-${doc.bienniumEnd}`:''),doc.tomo,doc.printedFolio??doc.fojaInitial,doc.minuta,doc.actoJuridico,doc.kardex,doc.escritura,doc.contractors.map(item=>item.name).join('; '),doc.observations,documentStatusLabel(doc.documentStatus),ocrStatusLabel(doc.ocrStatus),doc.fileSize,doc.createdAt]);downloadText(`reporte-boveda-${period||'completo'}.csv`,[header,...rows].map(row=>row.map(csvCell).join(',')).join('\n'),'text/csv;charset=utf-8')}
 return <div className="page-content reportsPage"><div className="reportFilters"><select aria-label="Año o bienio" className="field" value={period} onChange={event=>setPeriod(event.target.value)}><option value="">Todos los años y bienios</option>{report.options.periods.map(value=><option key={value}>{value}</option>)}</select><select aria-label="Tomo" className="field" value={tome} onChange={event=>setTome(event.target.value)}><option value="">Todos los tomos</option>{report.options.tomes.map(value=><option key={value}>{value}</option>)}</select><select aria-label="Tipo documental" className="field" value={type} onChange={event=>setType(event.target.value)}><option value="">Todos los tipos</option>{report.options.types.map(value=><option key={value}>{value}</option>)}</select><select aria-label="Estado" className="field" value={status} onChange={event=>setStatus(event.target.value)}><option value="CONFIRMED">Confirmado</option></select><span/><button className="btn" disabled={loading||!report.total} onClick={exportCsv}><Download size={14}/>CSV</button><button className="btn primary" disabled={loading||!report.total} onClick={()=>window.print()}><Download size={14}/>PDF</button></div>{error&&<div className="card reportError">{error}</div>}<div className="reportStats"><Metric n={loading?'…':String(report.total)} label="Documentos confirmados"/><Metric n={loading?'…':String(report.documents.filter(doc=>doc.documentMode==='historico').length)} label="Documentos históricos"/><Metric n={loading?'…':formatBytes(report.totalBytes)} label="Almacenamiento utilizado" green/><Metric n="0" label="Fallidos incluidos"/></div><div className="reportCharts"><div className="card reportChart"><h3>Documentos registrados por mes</h3><p>Calculado con la fecha real de registro en PostgreSQL</p><svg viewBox="0 0 700 220" preserveAspectRatio="none"><g className="grid">{[30,80,130,180].map(y=><line key={y} x1="20" x2="680" y1={y} y2={y}/>)}</g>{report.total>0&&<polyline points={points}/>} {monthly.map((value,index)=><circle key={index} cx={30+index*58} cy={190-value/maxMonth*150} r="4"><title>{value} documentos</title></circle>)}{months.map((month,index)=><text key={month} x={30+index*58} y="210">{month}</text>)}</svg></div><div className="card reportChart typeBars"><h3>Documentos por tipo documental</h3><p>Solo documentos confirmados, activos y procesados</p><div>{typeCounts.map(([name,count],index)=><label key={name}><span>{name}</span><i><b style={{width:`${count/maxType*92}%`,background:colors[index%colors.length]}}/></i><strong>{count}</strong></label>)}{!loading&&typeCounts.length===0&&<p className="emptyChart">Sin datos disponibles</p>}</div></div></div></div>
}
function Metric({n,label,green}:{n:string,label:string,green?:boolean}){return <div className="card reportMetric"><strong className={green?'green':''}>{n}</strong><b>{label}</b></div>}
function formatBytes(bytes:number){return `${(bytes/1024/1024).toFixed(2)} MB`}
