import {useEffect,useMemo,useState} from 'react';
import {BookOpen,CalendarDays,ChevronDown,ChevronRight,FileText,FileType2} from 'lucide-react';
import {useNavigate} from 'react-router-dom';
import {useDocuments} from '../hooks/useDocuments';
import {buildTomeHierarchy} from '../services/tomeHierarchy';
import './tomos.css';
const OPEN_KEY='sigadn-tomos-open-v1';const SCROLL_KEY='sigadn-tomos-scroll-v1';
function initialOpen(){try{return JSON.parse(sessionStorage.getItem(OPEN_KEY)??'{}') as Record<string,boolean>}catch{return {}}}
export function Tomos(){
 const navigate=useNavigate();const {documents,loading,error,refresh}=useDocuments();const [open,setOpen]=useState<Record<string,boolean>>(initialOpen);const groups=useMemo(()=>buildTomeHierarchy(documents),[documents]);const totalTomos=groups.reduce((sum,group)=>sum+group.tomes.length,0);const totalDocuments=groups.reduce((sum,group)=>sum+group.tomes.reduce((subtotal,tome)=>subtotal+tome.categories.reduce((count,item)=>count+item.documents.length,0),0),0);
 useEffect(()=>{const top=Number(sessionStorage.getItem(SCROLL_KEY)??0);if(top)requestAnimationFrame(()=>window.scrollTo({top}))},[]);
 function toggle(key:string,expanded:boolean){setOpen(current=>{const next={...current,[key]:!expanded};sessionStorage.setItem(OPEN_KEY,JSON.stringify(next));return next})}
 function view(id:number){sessionStorage.setItem(OPEN_KEY,JSON.stringify(open));sessionStorage.setItem(SCROLL_KEY,String(window.scrollY));navigate(`/visor/${id}`,{state:{from:'/tomos'}})}
 return <div className="page-content tomosPage"><div className="tomosLead"><span>{totalTomos} {totalTomos===1?'tomo registrado':'tomos registrados'}</span></div><div className="tomoStats"><Mini icon={<CalendarDays/>} n={String(groups.length)} label="Años y bienios"/><Mini icon={<BookOpen/>} n={String(totalTomos)} label="Total tomos"/><Mini icon={<FileText/>} n={String(totalDocuments)} label="Documentos"/></div><section className="card yearList">{loading?<div className="emptyTomo">Cargando organización documental…</div>:error?<div className="emptyTomo"><p>No se pudo cargar la organización documental.</p><button className="btn" onClick={()=>void refresh()}>Reintentar</button></div>:groups.map(group=><TreeNode key={group.key} nodeKey={group.key} open={open} toggle={toggle} icon={<CalendarDays/>} title={group.label} subtitle={`${group.tomes.length} ${group.tomes.length===1?'tomo':'tomos'}`} level="year">{group.tomes.map(tome=>{const documentCount=tome.categories.reduce((sum,item)=>sum+item.documents.length,0);return <TreeNode key={tome.key} nodeKey={tome.key} open={open} toggle={toggle} icon={<BookOpen/>} title={tome.label} subtitle={`${documentCount} ${documentCount===1?'documento':'documentos'}`} level="tome">{tome.categories.map(item=>{const key=`${tome.key}/category:${item.name}`;return <TreeNode key={key} nodeKey={key} open={open} toggle={toggle} icon={<FileType2/>} title={item.name} subtitle={`${item.documents.length} ${item.documents.length===1?'documento':'documentos'}`} level="category">{item.documents.map(({document,label,requiresReview})=><button className="tomePdf" key={document.id} onClick={()=>view(document.id)}><FileText/><span>{label}</span>{requiresReview&&<small>Requiere revisión</small>}</button>)}</TreeNode>})}</TreeNode>})}</TreeNode>)}{!loading&&!error&&!groups.length&&<div className="emptyTomo">No hay documentos confirmados organizados en tomos todavía.</div>}</section></div>
}
function TreeNode({nodeKey,open,toggle,icon,title,subtitle,level,children}:{nodeKey:string;open:Record<string,boolean>;toggle:(key:string,expanded:boolean)=>void;icon:React.ReactNode;title:string;subtitle:string;level:'year'|'tome'|'category';children:React.ReactNode}){const expanded=open[nodeKey]??level==='year';return <div className={`tomeTreeNode ${level} ${expanded?'expanded':''}`}><button className="tomeTreeHead" onClick={()=>toggle(nodeKey,expanded)}>{expanded?<ChevronDown/>:<ChevronRight/>}<span className="icon-disc">{icon}</span><span className="tomeTreeLabel"><b>{title}</b><small>{subtitle}</small></span></button>{expanded&&<div className="tomeTreeChildren">{children}</div>}</div>}
function Mini({icon,n,label}:{icon:React.ReactNode;n:string;label:string}){return <div className="card tomoStat"><div className="icon-disc">{icon}</div><div><strong>{n}</strong><small>{label}</small></div></div>}
