import {useEffect,useState} from 'react';
import {Bot,ChevronLeft,Download,Maximize2,Minus,Plus,Printer,RotateCw,ScanSearch,Sparkles,Users} from 'lucide-react';
import {useLocation,useNavigate,useParams} from 'react-router-dom';
import {StatusBadge} from '../components/StatusBadge';
import {addAudit,documentUrl,getDocument,type DocumentRecord} from '../data/repository';
import {sanitizeDisplayText} from '../utils/displayText';
import './viewer.css';

const display=(value:unknown)=>sanitizeDisplayText(value)||'—';

export function Visor(){
  const {id}=useParams();const baseNavigate=useNavigate();const location=useLocation();const navigate=(target:string)=>baseNavigate(target==='/documentos'&&location.state?.from==='/tomos'?'/tomos':target);const [document,setDocument]=useState<DocumentRecord>();const [url,setUrl]=useState('');const [zoom,setZoom]=useState(100);const [rotation,setRotation]=useState(0);
  useEffect(()=>{let active=true;let objectUrl='';void getDocument(Number(id)).then(record=>{if(!active||!record)return;objectUrl=documentUrl(record);setDocument(record);setUrl(objectUrl);void addAudit('VISUALIZACIÓN','Documentos',`Escritura ${record.escritura}`)});return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl)}},[id]);
  function download(){if(!document)return;const fileUrl=documentUrl(document);const link=window.document.createElement('a');link.href=fileUrl;link.download=document.fileName;link.click();URL.revokeObjectURL(fileUrl)}
  function fullscreen(){if(!window.document.fullscreenElement)void window.document.documentElement.requestFullscreen();else void window.document.exitFullscreen()}
  function print(){if(!url)return;const tab=window.open(url,'_blank');tab?.addEventListener('load',()=>tab.print())}
  function ask(action:string){navigate(`/asistente?document=${document?.id}&action=${action}`)}
  function back(){navigate('/documentos')}
  if(!document)return <div className="viewerPage viewerEmpty"><button className="btn" onClick={back}><ChevronLeft size={15}/>Volver</button><p>Abriendo documento…</p></div>;
  const fileName=display(document.fileName);
  return <div className="viewerPage"><div className="viewerToolbar"><button className="btn" onClick={()=>navigate('/documentos')}><ChevronLeft size={15}/>Volver</button><div><b>Escritura {display(document.escritura)}</b><span>{fileName} · {document.documentMode==='historico'?'Documento histórico':'Documento actual'}</span></div><div className="viewerTools"><button title="Alejar" onClick={()=>setZoom(value=>Math.max(60,value-10))}><Minus/></button><span>{zoom}%</span><button title="Acercar" onClick={()=>setZoom(value=>Math.min(160,value+10))}><Plus/></button><button title="Rotar visor" onClick={()=>setRotation(value=>(value+90)%360)}><RotateCw/></button><button title="Pantalla completa" onClick={fullscreen}><Maximize2/></button><button title="Imprimir PDF" onClick={print}><Printer/></button><button className="download" onClick={download}><Download/>Descargar original</button></div></div><div className="viewerBody realViewerBody"><main className="canvas realCanvas">{url&&<iframe title={`PDF ${fileName}`} src={url} style={{width:`${zoom}%`,transform:`rotate(${rotation}deg)`}}/>}</main><aside className="metadata"><h3>Información documental</h3><StatusBadge>{display(document.documento)}</StatusBadge><dl><dt>Clasificación</dt><dd>{document.documentMode==='historico'?'Documento histórico':'Documento actual'}</dd><dt>Archivo original</dt><dd>{fileName}</dd><dt>Número de escritura</dt><dd>{display(document.escritura)}</dd><dt>Número de minuta</dt><dd>{display(document.numeroMinuta)}</dd><dt>Acto jurídico</dt><dd>{display(document.actoJuridico)}</dd><dt>Kardex</dt><dd>{display(document.kardex)}</dd><dt>Tipo documental</dt><dd>{display(document.tipo)}</dd><dt>{document.documentMode==='historico'?'Bienio':'Año'}</dt><dd>{display(document.bienio??document.ano)}</dd><dt>Tomo</dt><dd>{display(document.tomo)}</dd>{document.documentMode==='historico'&&<><dt>Rango de fojas</dt><dd>{display(document.fojaInicial)} – {display(document.fojaFinal)}</dd></>}<dt>Contratantes</dt>{document.contratantes.length?document.contratantes.map((value,index)=><dd key={index}>{index+1}. {display(value)}</dd>):<dd>—</dd>}<dt>Observaciones</dt><dd>{display(document.observaciones)}</dd></dl><div className="ocrBox"><span>Estado OCR <b>{display(document.ocr)}</b></span><small>El archivo original permanece sin alteraciones.</small></div><section className="viewerAssistant"><div><Bot/><b>Asistente IA</b></div><p>¿Qué deseas hacer con este documento?</p><button onClick={()=>ask('summary')}><Sparkles/>Resumir documento</button><button onClick={()=>ask('extract')}><Users/>Extraer datos y contratantes</button><button onClick={()=>ask('inconsistencies')}><ScanSearch/>Buscar inconsistencias</button><button onClick={()=>ask('compare')}><ScanSearch/>Comparar OCR y metadatos</button><button onClick={()=>ask('question')}><Bot/>Hacer una pregunta</button></section><button className="btn" onClick={()=>navigate('/auditoria')}>Ver historial</button></aside></div></div>
}
