import {useEffect,useRef,useState} from 'react';
import {ChevronLeft,Download,Minus,Pencil,Plus,Printer,RotateCw,Save,X} from 'lucide-react';
import {useLocation,useNavigate,useParams} from 'react-router-dom';
import {StatusBadge} from '../components/StatusBadge';
import {useAuth} from '../auth/AuthContext';
import {documentUrl,getDocument,type DocumentRecord} from '../data/repository';
import {documentFolioDisplay} from '../services/documentFolio';
import {canManageRemoteDocument,replaceRemotePdf,updateRemoteMetadata,type DocumentMetadataPatch} from '../services/documentsApi';
import {openExternalUrl} from '../services/externalLinks';
import {sanitizeDisplayText} from '../utils/displayText';
import {documentStatusLabel,ocrStatusLabel} from '../utils/statusLabels';
import {generateNormalizedFilename} from '../utils/documentFilename';
import './viewer.css';
import './viewer-edit.css';

const display=(value:unknown)=>sanitizeDisplayText(value)||'—';
const relatedLabel=(item:NonNullable<DocumentRecord['relatedDocuments']>[number])=>/minuta/i.test(item.tipo)&&item.minuteNumber?`Minuta ${item.minuteNumber}`:item.instrumentNumber?`Escritura ${item.instrumentNumber}`:item.tipo;
type EditDraft={escritura:string;numeroMinuta:string;actoJuridico:string;kardex:string;tipo:string;ano:string;tomo:string;foja:string;contratantes:string;observaciones:string;qrUrl:string};
const editDraft=(doc:DocumentRecord):EditDraft=>({escritura:doc.escritura,numeroMinuta:doc.numeroMinuta,actoJuridico:doc.actoJuridico,kardex:doc.kardex,tipo:doc.tipo,ano:String(doc.ano??''),tomo:doc.tomo,foja:String(doc.printedFolio??doc.fojaInicial??''),contratantes:doc.contratantes.join('\n'),observaciones:doc.observaciones,qrUrl:doc.qrUrl??''});
export function Visor(){
 const {user:sessionUser}=useAuth();
 const {id}=useParams();const baseNavigate=useNavigate();const location=useLocation();const [document,setDocument]=useState<DocumentRecord>();const [url,setUrl]=useState('');const [loadError,setLoadError]=useState('');const [zoom,setZoom]=useState(100);const [rotation,setRotation]=useState(0);const [editing,setEditing]=useState(false);const [draft,setDraft]=useState<EditDraft>();const [changedFields,setChangedFields]=useState<Set<keyof EditDraft>>(()=>new Set());const [saving,setSaving]=useState(false);const savingId=useRef<string|undefined>(undefined);const [editError,setEditError]=useState('');const [savedMessage,setSavedMessage]=useState('');
 const [qrOpenError,setQrOpenError]=useState('');
 const canManage=canManageRemoteDocument(document,sessionUser?.role);
 const user=canManage&&sessionUser?{...sessionUser,role:'Administrador' as const}:sessionUser;
 const navigate=(target:string)=>baseNavigate(target==='/documentos'&&location.state?.from==='/tomos'?'/tomos':target);
 useEffect(()=>{let active=true;let objectUrl='';queueMicrotask(()=>{if(active){setDocument(undefined);setLoadError('')}});void getDocument(id??'').then(async record=>{if(!active)return;if(!record){setLoadError('Documento no encontrado.');return}objectUrl=await documentUrl(record);if(!active){URL.revokeObjectURL(objectUrl);return}setDocument(record);setUrl(objectUrl)}).catch(error=>{if(active)setLoadError(error instanceof Error?error.message:'No se pudo abrir el documento.')});return()=>{active=false;if(objectUrl)URL.revokeObjectURL(objectUrl)}},[id]);
 useEffect(()=>{const request=document?.tipo.trim().toLocaleLowerCase('es-PE')==='solicitud';window.document.body.classList.toggle('viewingRequest',request);window.document.body.classList.toggle('viewingReadOnlyDocument',Boolean(document&&!canManage));return()=>{window.document.body.classList.remove('viewingRequest');window.document.body.classList.remove('viewingReadOnlyDocument')}},[document,canManage]);
 useEffect(()=>{if(!document?.backendId||!['Administrador','Notario'].includes(user?.role??''))return;const tools=window.document.querySelector('.viewerTools');const downloadButton=tools?.querySelector('.download');if(!tools||!downloadButton)return;const button=window.document.createElement('button');const input=window.document.createElement('input');button.type='button';button.className='replacePdfButton';button.textContent='Reemplazar PDF';input.type='file';input.accept='application/pdf,.pdf';input.hidden=true;button.onclick=()=>input.click();input.onchange=()=>{const file=input.files?.[0];input.value='';if(!file)return;if(file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf')){window.alert('Seleccione un archivo PDF válido.');return}if(!window.confirm(`¿Desea reemplazar el PDF actual por "${file.name}"? Los datos documentales se conservarán.`))return;button.disabled=true;button.textContent='Reemplazando…';void replaceRemotePdf(document.backendId!,file).then(async updated=>{const replacementUrl=await documentUrl(updated);setUrl(previous=>{if(previous)URL.revokeObjectURL(previous);return replacementUrl});setDocument(updated);setSavedMessage('PDF reemplazado correctamente. Los datos documentales se conservaron.')}).catch(error=>window.alert(error instanceof Error?error.message:'No se pudo reemplazar el PDF.')).finally(()=>{button.disabled=false;button.textContent='Reemplazar PDF'})};tools.insertBefore(button,downloadButton);tools.appendChild(input);return()=>{button.remove();input.remove()}},[document?.backendId,user?.role]);
 if(!document)return <div className="viewerPage viewerEmpty"><button className="btn" onClick={()=>navigate('/documentos')}><ChevronLeft/>Volver</button><p>{loadError||'Abriendo documento…'}</p></div>;
 const current=document;const {exact}=documentFolioDisplay(current);const biennium=current.bienniumStart&&current.bienniumEnd?`${current.bienniumStart}-${current.bienniumEnd}`:undefined;
 async function download(){
  const fileUrl=await documentUrl(current);
  const link=window.document.createElement('a');
  link.href=fileUrl;
  link.download=current.fileName.toLowerCase().endsWith('.pdf')?current.fileName:`${current.fileName}.pdf`;
  link.style.display='none';
  window.document.body.appendChild(link);
  link.click();
  link.remove();
  setTimeout(()=>URL.revokeObjectURL(fileUrl),10_000);
 }
 function print(){const tab=window.open(url,'_blank');tab?.addEventListener('load',()=>tab.print())}
 function beginEdit(){setDraft(editDraft(current));setChangedFields(new Set());setEditError('');setSavedMessage('');setEditing(true)}
 function cancelEdit(){if(saving)return;setEditing(false);setDraft(undefined);setChangedFields(new Set());setEditError('')}
 function change(field:keyof EditDraft,value:string){setChangedFields(fields=>new Set(fields).add(field));setDraft(valueDraft=>valueDraft?{...valueDraft,[field]:value}:valueDraft)}
 async function openQr(url:string){setQrOpenError('');try{await openExternalUrl(url)}catch{setQrOpenError('No se pudo abrir el enlace del QR en el navegador.')}}
 async function saveMetadata(){
  if(!draft||!current.backendId||savingId.current===current.backendId)return;
  const contractors=draft.contratantes.split(/[\n;,]+/).map(value=>value.trim()).filter(Boolean);
  if(!draft.tipo.trim()||!draft.kardex.trim()||!draft.tomo.trim()){setEditError('Tipo documental, Kardex y tomo son obligatorios.');return}
  const qrUrl=draft.qrUrl.trim();
  if(qrUrl){try{const parsed=new URL(qrUrl);if(!['http:','https:'].includes(parsed.protocol)||!parsed.hostname)throw new Error()}catch{setEditError('El enlace del QR debe ser una URL completa que comience con http:// o https://.');return}}
  const patch:DocumentMetadataPatch={};const changed=(field:keyof EditDraft)=>changedFields.has(field);
  if(changed('tipo'))patch.documentType=draft.tipo.trim();if(changed('ano'))patch.year=draft.ano?Number(draft.ano):null;if(changed('tomo'))patch.tomo=draft.tomo.trim();if(changed('foja'))patch.printedFolio=draft.foja?Number(draft.foja):null;if(changed('escritura'))patch.escritura=draft.escritura.trim();if(changed('numeroMinuta'))patch.minuta=draft.numeroMinuta.trim();if(changed('actoJuridico'))patch.actoJuridico=draft.actoJuridico.trim();if(changed('kardex'))patch.kardex=draft.kardex.trim();if(changed('contratantes'))patch.contractors=contractors;if(changed('observaciones'))patch.observations=draft.observaciones.trim();if(changed('qrUrl'))patch.qrUrl=qrUrl;
  if(!Object.keys(patch).length){setEditing(false);setDraft(undefined);setSavedMessage('');return}
  const renameRequested=['documentType','kardex','escritura','contractors'].some(key=>Object.prototype.hasOwnProperty.call(patch,key));const documentClass=/^minuta$/i.test(draft.tipo.trim())?'MINUTA':/^solicitud$/i.test(draft.tipo.trim())?'SOLICITUD':'REGISTRO_NOTARIAL';const expectedFileName=generateNormalizedFilename({contractor:contractors[0],kardexNumber:draft.kardex,instrumentNumber:draft.escritura,documentClass});
  savingId.current=current.backendId;setSaving(true);setEditError('');try{const updated=await updateRemoteMetadata(current.backendId,patch);const refreshed=renameRequested&&updated.fileName===current.fileName?{...updated,fileName:expectedFileName}:updated;setDocument(refreshed);window.dispatchEvent(new CustomEvent('boveda:documents-changed',{detail:{documentId:refreshed.backendId,document:refreshed}}));setEditing(false);setDraft(undefined);setChangedFields(new Set());setSavedMessage(renameRequested?`Información actualizada. El PDF ahora se descargará como: ${refreshed.fileName}`:'Información actualizada correctamente.')}catch(error){setEditError(error instanceof Error?error.message:'No se pudo actualizar la información.')}finally{savingId.current=undefined;setSaving(false)}
 }
 return <div className="viewerPage"><div className="viewerToolbar"><button className="btn" onClick={()=>navigate('/documentos')}><ChevronLeft/>Volver</button><div><b>{display(document.fileName)}</b><span>Documento actual</span></div><div className="viewerTools"><button onClick={()=>setZoom(v=>Math.max(60,v-10))}><Minus/></button><span>{zoom}%</span><button onClick={()=>setZoom(v=>Math.min(160,v+10))}><Plus/></button><button onClick={()=>setRotation(v=>(v+90)%360)}><RotateCw/></button><button onClick={print}><Printer/></button><button className="download" onClick={download}><Download/>Descargar con nombre registrado</button></div></div><div className="viewerBody realViewerBody"><main className="canvas realCanvas">{url&&<iframe title={`PDF ${document.fileName}`} src={`${url}#toolbar=0&navpanes=0`} style={{width:`${zoom}%`,transform:`rotate(${rotation}deg)`}}/>}</main><aside className="metadata"><div className="metadataHeading"><h3>Información documental</h3>{!editing&&<button type="button" onClick={beginEdit}><Pencil/>Editar</button>}</div><StatusBadge>{documentStatusLabel(document.documento)}</StatusBadge>{savedMessage&&<p className="metadataSuccess" role="status">{savedMessage}</p>}{editing&&draft?<div className="metadataEditForm">
 <label>Número de escritura<input value={draft.escritura} onChange={event=>change('escritura',event.target.value)}/></label><label>Número de minuta<input value={draft.numeroMinuta} onChange={event=>change('numeroMinuta',event.target.value)}/></label><label>Acto jurídico<input value={draft.actoJuridico} onChange={event=>change('actoJuridico',event.target.value)}/></label><label>Kardex relacionado *<input required value={draft.kardex} onChange={event=>change('kardex',event.target.value)}/></label><label>Tipo documental *<input required value={draft.tipo} onChange={event=>change('tipo',event.target.value)}/></label><label>Año<input inputMode="numeric" value={draft.ano} onChange={event=>change('ano',event.target.value.replace(/\D/g,''))}/></label><label>Tomo *<input required value={draft.tomo} onChange={event=>change('tomo',event.target.value)}/></label><label>Foja exacta<input inputMode="numeric" value={draft.foja} onChange={event=>change('foja',event.target.value.replace(/\D/g,''))}/></label><label>Contratantes<textarea rows={3} value={draft.contratantes} onChange={event=>change('contratantes',event.target.value)} placeholder="Un nombre por línea"/></label><label>Observaciones<textarea rows={3} value={draft.observaciones} onChange={event=>change('observaciones',event.target.value)}/></label><label>Enlace del QR<input type="url" value={draft.qrUrl} onChange={event=>change('qrUrl',event.target.value)} placeholder="https://..."/></label>{editError&&<p className="metadataError" role="alert">{editError}</p>}<div className="metadataEditActions"><button className="btn" disabled={saving} onClick={cancelEdit}><X/>Cancelar</button><button className="btn primary" disabled={saving} onClick={()=>void saveMetadata()}><Save/>{saving?'Guardando…':'Guardar cambios'}</button></div>
 </div>:<dl><dt>Número de escritura</dt><dd>{display(document.escritura)}</dd><dt>Número de minuta</dt><dd>{display(document.numeroMinuta)}</dd><dt>Acto jurídico</dt><dd>{display(document.actoJuridico)}</dd><dt>Kardex relacionado</dt><dd>{display(document.normalizedKardex??document.kardex)}</dd><dt>Tipo documental</dt><dd>{display(document.tipo)}</dd><dt>{biennium?'Bienio':'Año'}</dt><dd>{biennium??display(document.ano)}</dd><dt>Tomo</dt><dd>{display(document.tomo)}</dd><dt>Foja exacta</dt><dd>{exact}</dd><dt>Contratantes</dt><dd>{document.contratantes.length?document.contratantes.map(display).join('; '):'—'}</dd><dt>Observaciones</dt><dd>{display(document.observaciones)}</dd><dt>Enlace del QR</dt><dd>{document.qrUrl?<><a className="metadataQrLink" href={document.qrUrl} title="Ir al enlace del QR" onClick={event=>{event.preventDefault();void openQr(document.qrUrl!)}}>{document.qrUrl}</a>{qrOpenError&&<small className="metadataQrError" role="alert">{qrOpenError}</small>}</>:document.qrRawValue?'QR detectado sin enlace web válido':'No se detectó un QR con enlace'}</dd>{document.qrPageNumber&&<><dt>Página del QR</dt><dd>{document.qrPageNumber}</dd></>}<dt>Estado de lectura</dt><dd>{ocrStatusLabel(document.ocr)}</dd></dl>}
 <h3>Documentos del mismo Kardex</h3>{document.relatedDocuments?.length?<><p>{document.relationStatus}</p><div className="documentPrimaryActions">{document.relatedDocuments.map(item=><button className="btn" key={item.backendId??item.id} onClick={()=>baseNavigate(`/visor/${item.backendId??item.id}`,{state:location.state})}>{relatedLabel(item)} — {item.fileName}</button>)}</div></>:<p>No hay otro documento relacionado todavía.</p>}
 </aside></div></div>;
}
