import {useEffect,useMemo,useRef,useState} from 'react';
import {ChevronLeft,ChevronRight,Download,FileSpreadsheet,FolderOpen,Pause,Play,RefreshCw,Search,X} from 'lucide-react';
import type {ExcelSheetProfile,ExcelTargetField,ExcelWorkbookProfile,ImportJob,ImportValidationResult,InventoryFile,NormalizedExcelRow,ValidationMatchStatus} from '../domain/document-domain';
import {analyzeInventoryPath,compareInventoryWithExcel} from '../services/importAnalysis';
import {normalizeExcelRows} from '../services/excelImport';
import {allExcelRows,allInventoryFiles,getDirectoryHandle,getExcelProfile,inventoryPage,latestImportJob,replaceExcelRows,replaceValidationResults,saveDirectoryHandle,saveExcelProfile,saveImportJob,saveInventoryFiles,validationCounts,validationPage} from '../services/importStore';

type FileSystemFileHandleLike={kind:'file';name:string;getFile:()=>Promise<File>};
type FileSystemDirectoryHandleLike={kind:'directory';name:string;values:()=>AsyncIterableIterator<FileSystemFileHandleLike|FileSystemDirectoryHandleLike>};
type PickerWindow=Window&{showDirectoryPicker?:()=>Promise<FileSystemDirectoryHandleLike>};
type InventorySource={kind:'file-list';files:FileList}|{kind:'directory';handle:FileSystemDirectoryHandleLike};
const PAGE_SIZE=25;const targetOptions:Array<[ExcelTargetField,string]>=[['IGNORE','No importar'],['correlative','Cantidad o correlativo'],['kardexNumber','Número de kardex'],['tomeNumber','Número de tomo'],['year','Año'],['biennium','Bienio'],['instrumentType','Tipo de instrumento'],['instrumentNumber','Número de instrumento'],['minuteNumber','Número de minuta'],['legalAct','Contrato o acto jurídico'],['contractor','Contratante'],['folios','Número o rango de fojas'],['date','Fecha'],['registryType','Tipo de registro']];

export function ExistingImports(){
  const [job,setJob]=useState<ImportJob>();const [files,setFiles]=useState<InventoryFile[]>([]);const [fileTotal,setFileTotal]=useState(0);const [page,setPage]=useState(1);const [profile,setProfile]=useState<ExcelWorkbookProfile>();const [selectedSheet,setSelectedSheet]=useState('');const [rawSheets,setRawSheets]=useState<Record<string,unknown[][]>>({});const [results,setResults]=useState<ImportValidationResult[]>([]);const [resultTotal,setResultTotal]=useState(0);const [resultPage,setResultPage]=useState(1);const [filter,setFilter]=useState<ValidationMatchStatus|'ALL'>('ALL');const [counts,setCounts]=useState<Partial<Record<ValidationMatchStatus,number>>>({});const [detail,setDetail]=useState<string>();const [message,setMessage]=useState('');const inputRef=useRef<HTMLInputElement>(null);const excelRef=useRef<HTMLInputElement>(null);const sourceRef=useRef<InventorySource|undefined>(undefined);const pauseRef=useRef(false);const cancelRef=useRef(false);
  useEffect(()=>{void (async()=>{const restored=await latestImportJob();if(!restored)return;setJob(restored);setProfile(await getExcelProfile(restored.id));const handle=await getDirectoryHandle<FileSystemDirectoryHandleLike>(restored.id);if(handle)sourceRef.current={kind:'directory',handle};await loadFiles(restored.id,1);await loadResults(restored.id,'ALL',1)})()},[]);
  async function loadFiles(jobId:string,nextPage:number){const data=await inventoryPage(jobId,nextPage,PAGE_SIZE);setFiles(data.rows);setFileTotal(data.total);setPage(nextPage)}
  async function loadResults(jobId:string,nextFilter:ValidationMatchStatus|'ALL',nextPage:number){const data=await validationPage(jobId,nextFilter,nextPage,PAGE_SIZE);setResults(data.rows);setResultTotal(data.total);setCounts(await validationCounts(jobId));setFilter(nextFilter);setResultPage(nextPage)}
  function createJob(folderName:string,totalFiles=0):ImportJob{const now=new Date().toISOString();return{id:crypto.randomUUID(),sourceType:'DOCUMENT_FOLDER',status:'SELECTING_FOLDER',totalFiles,totalBytes:0,inventoriedFiles:0,uploadedFiles:0,processedFiles:0,confirmedFiles:0,reviewFiles:0,failedFiles:0,folderCount:0,pdfFiles:0,excelFiles:0,unsupportedFiles:0,batchSize:250,cursor:0,folderName,createdAt:now,updatedAt:now}}
  async function selectNativeFolder(){const picker=(window as PickerWindow).showDirectoryPicker;if(!picker){inputRef.current?.click();return}try{const handle=await picker();const next=createJob(handle.name);sourceRef.current={kind:'directory',handle};setJob(next);await saveDirectoryHandle(next.id,handle);await saveImportJob(next);await runInventory(next)}catch(error){if((error as DOMException).name!=='AbortError')setMessage('No se pudo seleccionar la carpeta.')}}
  async function selectFallback(filesList:FileList|null){if(!filesList?.length)return;const root=(filesList[0] as File&{webkitRelativePath?:string}).webkitRelativePath?.split('/')[0]||'Carpeta seleccionada';const next=createJob(root,filesList.length);sourceRef.current={kind:'file-list',files:filesList};setJob(next);await saveImportJob(next);await runInventory(next)}
  async function* directoryFiles(handle:FileSystemDirectoryHandleLike,prefix=''):AsyncGenerator<{file:File;relativePath:string;folder:boolean}> {for await(const entry of handle.values()){const relativePath=prefix?`${prefix}/${entry.name}`:entry.name;if(entry.kind==='directory'){yield{file:new File([],entry.name),relativePath,folder:true};yield*directoryFiles(entry,relativePath)}else yield{file:await entry.getFile(),relativePath,folder:false}}}
  async function runInventory(base:ImportJob){const source=sourceRef.current;if(!source){setMessage('Para continuar el inventario debe volver a autorizar la carpeta.');return}pauseRef.current=false;cancelRef.current=false;let current:ImportJob={...base,status:'INVENTORY_RUNNING',updatedAt:new Date().toISOString()};setJob(current);await saveImportJob(current);const batch:InventoryFile[]=[];let cursor=base.cursor,totalFiles=source.kind==='file-list'?source.files.length:base.totalFiles;let bytes=base.totalBytes,pdf=base.pdfFiles,excel=base.excelFiles,unsupported=base.unsupportedFiles,folders=base.folderCount,failed=base.failedFiles;
    const commit=async()=>{if(batch.length)await saveInventoryFiles(batch.splice(0));current={...current,totalFiles,totalBytes:bytes,inventoriedFiles:cursor,processedFiles:cursor,pdfFiles:pdf,excelFiles:excel,unsupportedFiles:unsupported,folderCount:folders,failedFiles:failed,cursor,status:'INVENTORY_RUNNING',updatedAt:new Date().toISOString()};setJob(current);await saveImportJob(current);await new Promise(resolve=>window.setTimeout(resolve,0))};
    try{if(source.kind==='file-list'){for(let index=base.cursor;index<source.files.length;index++){if(cancelRef.current||pauseRef.current)break;const file=source.files.item(index);if(!file)continue;const relative=(file as File&{webkitRelativePath?:string}).webkitRelativePath||file.name;try{const analyzed=analyzeInventoryPath({jobId:base.id,relativePath:relative,name:file.name,size:file.size,modifiedAt:file.lastModified});batch.push(analyzed);bytes+=file.size;cursor=index+1;if(analyzed.extension==='pdf')pdf++;else if(['xlsx','xls'].includes(analyzed.extension))excel++;if(analyzed.analysisStatus==='UNSUPPORTED')unsupported++}catch{failed++;cursor=index+1}if(batch.length>=base.batchSize)await commit()}}else{let seenFiles=0;for await(const entry of directoryFiles(source.handle)){if(cancelRef.current||pauseRef.current)break;if(entry.folder){if(base.cursor===0)folders++;continue}if(seenFiles++<base.cursor)continue;totalFiles++;try{const analyzed=analyzeInventoryPath({jobId:base.id,relativePath:entry.relativePath,name:entry.file.name,size:entry.file.size,modifiedAt:entry.file.lastModified});batch.push(analyzed);bytes+=entry.file.size;cursor++;if(analyzed.extension==='pdf')pdf++;else if(['xlsx','xls'].includes(analyzed.extension))excel++;if(analyzed.analysisStatus==='UNSUPPORTED')unsupported++}catch{failed++;cursor++}if(batch.length>=base.batchSize)await commit()}}await commit();const status=cancelRef.current?'INVENTORY_CANCELLED':pauseRef.current?'INVENTORY_PAUSED':'INVENTORY_COMPLETED';current={...current,status,updatedAt:new Date().toISOString()};setJob(current);await saveImportJob(current);await loadFiles(current.id,1)}catch(error){current={...current,status:'INVENTORY_FAILED',errorMessage:error instanceof Error?error.message:'Error de inventario',updatedAt:new Date().toISOString()};setJob(current);await saveImportJob(current)}}
  function pause(){pauseRef.current=true}
  function cancel(){cancelRef.current=true}
  async function resume(){if(job)await runInventory(job)}
  async function selectExcel(file?:File){if(!file)return;if(!file.name.toLowerCase().endsWith('.xlsx')){setMessage('ExcelJS admite archivos .xlsx. Los archivos .xls deben convertirse antes de importarlos.');return}setMessage('Leyendo Excel localmente…');const worker=new Worker(new URL('../workers/excelImport.worker.ts',import.meta.url),{type:'module'});try{const parsed=await new Promise<{profile:ExcelWorkbookProfile;rawSheets:Record<string,unknown[][]>}>((resolve,reject)=>{worker.onmessage=(event:MessageEvent<{ok:boolean;profile?:ExcelWorkbookProfile;rawSheets?:Record<string,unknown[][]>;error?:string}>)=>event.data.ok&&event.data.profile&&event.data.rawSheets?resolve({profile:event.data.profile,rawSheets:event.data.rawSheets}):reject(new Error(event.data.error));worker.onerror=()=>reject(new Error('El worker de Excel no pudo completar la lectura.'));worker.postMessage({file})});setProfile(parsed.profile);setSelectedSheet(parsed.profile.selectedSheet);setRawSheets(parsed.rawSheets);if(job)await saveExcelProfile(job.id,parsed.profile);setMessage('Excel leído. Revise y valide el mapeo de columnas.')}catch(error){setMessage(`No se pudo leer ${file.name}: ${error instanceof Error?error.message:'formato inválido'}`)}finally{worker.terminate()}}
  const sheet=profile?.sheets.find(item=>item.name===(selectedSheet||profile.selectedSheet));
  function updateMapping(columnIndex:number,target:ExcelTargetField){if(!profile||!sheet)return;const next={...profile,sheets:profile.sheets.map(item=>item.name===sheet.name?{...item,columns:item.columns.map(column=>column.index===columnIndex?{...column,target}:column)}:item)};setProfile(next)}
  async function validateMapping(){if(!job||!profile||!sheet)return;const duplicateTargets=sheet.columns.filter(column=>column.target!=='IGNORE'&&sheet.columns.filter(other=>other.target===column.target).length>1);if(duplicateTargets.length){setMessage('Hay campos de destino repetidos. Corrija el mapeo antes de validar.');return}const rows=normalizeExcelRows(job.id,sheet,rawSheets[sheet.name]??[]);await replaceExcelRows(job.id,rows);await saveExcelProfile(job.id,{...profile,selectedSheet:sheet.name});await compare(job.id,rows);setMessage('Mapeo validado y comparación completada.')}
  async function compare(jobId:string,excelRows?:NormalizedExcelRow[]){const inventory=await allInventoryFiles(jobId);const normalized=excelRows??await allExcelRows(jobId);const pdfs=inventory.filter(item=>item.extension==='pdf');const output:ImportValidationResult[]=pdfs.map(file=>{const comparison=compareInventoryWithExcel(file,normalized);return{id:`${jobId}:${file.id}`,jobId,inventoryFileId:file.id,excelRowIds:comparison.matches.map(row=>row.id),status:comparison.status,conflicts:comparison.conflicts,multipleContractors:comparison.contractors.length>1?comparison.contractors:[],legalAct:String(comparison.matches[0]?.values.legalAct?.normalizedValue??file.legalAct?.value??''),fileSnapshot:file}});await replaceValidationResults(jobId,output);await loadResults(jobId,'ALL',1)}
  async function fileAction(file:InventoryFile,action:'retry'|'ignore'){if(!job)return;const updated=action==='ignore'?{...file,analysisStatus:'IGNORED' as const}:{...analyzeInventoryPath({jobId:file.jobId,relativePath:file.relativePath,name:file.originalName,size:file.size,modifiedAt:file.modifiedAt}),id:file.id};await saveInventoryFiles([updated]);await loadFiles(job.id,page)}
  const fileMap=useMemo(()=>new Map(files.map(file=>[file.id,file])),[files]);const selectedResult=results.find(item=>item.id===detail);const selectedFile=selectedResult?.fileSnapshot??(selectedResult?fileMap.get(selectedResult.inventoryFileId):undefined);
  function exportErrors(){if(!job)return;void allInventoryFiles(job.id).then(rows=>{const errors=rows.filter(row=>row.analysisStatus==='ERROR'||row.analysisStatus==='UNSUPPORTED').map(row=>`${row.relativePath},${row.errorStage??'VALIDATION'},${row.error??(row.analysisStatus==='UNSUPPORTED'?'Extensión no admitida':'Error')}`);download(`errores-importacion-${job.id}.csv`,`ruta,etapa,error\n${errors.join('\n')}`)})}
  return <div className="existingPhaseTwo"><div className="existingGrid"><section className="card importCard"><FolderOpen/><h2>Subir carpeta documental</h2><p>{'showDirectoryPicker' in window?'Selector seguro del sistema disponible.':'El navegador usará selección compatible de carpeta.'}</p><div className="importDropzone"><button className="btn primary" onClick={selectNativeFolder}>Seleccionar carpeta</button><input ref={inputRef} hidden type="file" multiple {...({webkitdirectory:''} as React.InputHTMLAttributes<HTMLInputElement>)} onChange={event=>void selectFallback(event.target.files)}/></div><JobSummary job={job}/><div className="inventoryActions">{job?.status==='INVENTORY_RUNNING'&&<><button className="btn" onClick={pause}><Pause/>Pausar</button><button className="btn danger" onClick={cancel}><X/>Cancelar</button></>}{job?.status==='INVENTORY_PAUSED'&&<button className="btn primary" onClick={resume}><Play/>Continuar</button>}{job?.status==='INVENTORY_FAILED'&&<button className="btn" onClick={resume}><RefreshCw/>Reintentar</button>}</div></section><section className="card importCard"><FileSpreadsheet/><h2>Subir índice Excel</h2><p>Lectura local de hojas, encabezados, filas y tipos aparentes.</p><div className="importDropzone"><button className="btn primary" onClick={()=>excelRef.current?.click()}>Seleccionar Excel</button><input ref={excelRef} hidden type="file" accept=".xlsx" onChange={event=>void selectExcel(event.target.files?.[0])}/></div>{profile?<dl className="inventoryRows"><div><dt>Archivo</dt><dd>{profile.fileName}</dd></div><div><dt>Hojas</dt><dd>{profile.sheetNames.length}</dd></div><div><dt>Filas</dt><dd>{sheet?.rowCount??0}</dd></div></dl>:<p className="emptyInventory">Aún no se seleccionó un Excel .xlsx.</p>}</section></div>{message&&<p className="importMessage">{message}</p>}<ImportProgress job={job}/>{profile&&<ColumnMapping profile={profile} sheet={sheet} selectedSheet={selectedSheet||profile.selectedSheet} onSheet={setSelectedSheet} onMap={updateMapping} onValidate={validateMapping}/>} {job&&fileTotal>0&&<InventoryTable rows={files} total={fileTotal} page={page} onPage={next=>loadFiles(job.id,next)} onAction={fileAction}/>} {resultTotal>0&&<ValidationResults rows={results} files={files} total={resultTotal} page={resultPage} filter={filter} counts={counts} onFilter={next=>job&&loadResults(job.id,next,1)} onPage={next=>job&&loadResults(job.id,filter,next)} onDetail={setDetail}/>} {selectedResult&&selectedFile&&<ValidationDetail result={selectedResult} file={selectedFile} onClose={()=>setDetail(undefined)}/>} {job&&<button className="btn exportErrors" onClick={exportErrors}><Download/>Exportar reporte de errores</button>}</div>;
}

function JobSummary({job}:{job?:ImportJob}){if(!job)return<p className="emptyInventory">Aún no se seleccionó una carpeta.</p>;return <dl className="inventoryRows"><div><dt>Carpeta</dt><dd>{job.folderName}</dd></div><div><dt>Estado</dt><dd>{job.status}</dd></div><div><dt>Archivos</dt><dd>{job.totalFiles}</dd></div><div><dt>PDF</dt><dd>{job.pdfFiles}</dd></div><div><dt>Excel</dt><dd>{job.excelFiles}</dd></div><div><dt>Carpetas</dt><dd>{job.folderCount}</dd></div></dl>}
function ImportProgress({job}:{job?:ImportJob}){const percentage=job&&job.totalFiles?Math.min(100,Math.round(job.inventoriedFiles/job.totalFiles*100)):0;return <section className="card importProgress"><div><b>Inventario progresivo</b><span>{job?.status??'IDLE'}</span></div><progress value={percentage} max="100"/><div className="importMetrics"><span>Procesados <b>{job?.processedFiles??0}</b></span><span>Pendientes <b>{Math.max(0,(job?.totalFiles??0)-(job?.processedFiles??0))}</b></span><span>PDF <b>{job?.pdfFiles??0}</b></span><span>Excel <b>{job?.excelFiles??0}</b></span><span>No admitidos <b>{job?.unsupportedFiles??0}</b></span><span>Errores <b>{job?.failedFiles??0}</b></span></div><small>{formatBytes(job?.totalBytes??0)} · Lotes de {job?.batchSize??250} archivos · {percentage}%</small></section>}
function ColumnMapping({profile,sheet,selectedSheet,onSheet,onMap,onValidate}:{profile:ExcelWorkbookProfile;sheet?:ExcelSheetProfile;selectedSheet:string;onSheet:(value:string)=>void;onMap:(index:number,target:ExcelTargetField)=>void;onValidate:()=>void}){return <section className="card mappingCard"><header><div><h2>Correspondencia de columnas</h2><p>Las sugerencias deben ser confirmadas antes de comparar.</p></div><select className="field" value={selectedSheet} onChange={event=>onSheet(event.target.value)}>{profile.sheetNames.map(name=><option key={name}>{name}</option>)}</select></header><div className="mappingTable"><table><thead><tr><th>Columna Excel</th><th>Destino sugerido</th><th>Vacías</th><th>Tipos aparentes</th></tr></thead><tbody>{sheet?.columns.map(column=><tr key={column.index}><td>{column.header}{column.duplicateHeader&&<small>Encabezado duplicado</small>}</td><td><select className="field" value={column.target} onChange={event=>onMap(column.index,event.target.value as ExcelTargetField)}>{targetOptions.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></td><td>{column.emptyCells}</td><td>{column.apparentTypes.join(', ')}</td></tr>)}</tbody></table></div><button className="btn primary" onClick={onValidate}>Validar mapeo y comparar</button></section>}
function InventoryTable({rows,total,page,onPage,onAction}:{rows:InventoryFile[];total:number;page:number;onPage:(page:number)=>void;onAction:(file:InventoryFile,action:'retry'|'ignore')=>void}){return <section className="card resultCard"><h2>Inventario documental</h2><div className="resultTable"><table><thead><tr><th>Archivo</th><th>Clase preliminar</th><th>Kardex</th><th>Tomo</th><th>Año o bienio</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td title={row.relativePath}>{row.originalName}<small>{row.relativePath}</small></td><td>{row.preliminaryClass}</td><td>{row.kardex?.value??'No detectado'}</td><td>{row.tome?.value??'—'}</td><td>{row.period?.value??'—'}</td><td>{row.analysisStatus}</td><td>{['ERROR','UNSUPPORTED'].includes(row.analysisStatus)&&<><button className="btn" onClick={()=>onAction(row,'retry')}>Reintentar</button><button className="btn" onClick={()=>onAction(row,'ignore')}>Ignorar</button></>}</td></tr>)}</tbody></table></div><Pagination page={page} total={total} onPage={onPage}/></section>}
function ValidationResults({rows,files,total,page,filter,counts,onFilter,onPage,onDetail}:{rows:ImportValidationResult[];files:InventoryFile[];total:number;page:number;filter:ValidationMatchStatus|'ALL';counts:Partial<Record<ValidationMatchStatus,number>>;onFilter:(filter:ValidationMatchStatus|'ALL')=>void;onPage:(page:number)=>void;onDetail:(id:string)=>void}){const map=new Map(files.map(file=>[file.id,file]));return <section className="card resultCard"><h2>Resultados de validación</h2><div className="resultSummary">{(['MATCHED','PARTIAL_MATCH','CONFLICT','NOT_FOUND_IN_EXCEL','DUPLICATE_IN_EXCEL','KARDEX_NOT_DETECTED'] as ValidationMatchStatus[]).map(status=><span key={status}>{status}<b>{counts[status]??0}</b></span>)}</div><div className="resultFilters"><Search/>{(['ALL','MATCHED','PARTIAL_MATCH','CONFLICT','NOT_FOUND_IN_EXCEL','KARDEX_NOT_DETECTED'] as const).map(value=><button className={filter===value?'active':''} key={value} onClick={()=>onFilter(value)}>{value}</button>)}</div><div className="resultTable"><table><thead><tr><th>Archivo</th><th>Clase preliminar</th><th>Kardex</th><th>Acto jurídico</th><th>Contratante</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{rows.map(row=>{const file=row.fileSnapshot??map.get(row.inventoryFileId);return <tr key={row.id}><td>{file?.originalName??row.inventoryFileId}</td><td>{file?.preliminaryClass??'—'}</td><td>{file?.kardex?.value??'—'}</td><td>{row.legalAct||'Sin clasificar'}</td><td>{file?.contractor?.value??'—'}</td><td>{row.status}</td><td><button className="btn" onClick={()=>onDetail(row.id)}>Ver detalle</button></td></tr>})}</tbody></table></div><Pagination page={page} total={total} onPage={onPage}/></section>}
function ValidationDetail({result,file,onClose}:{result:ImportValidationResult;file:InventoryFile;onClose:()=>void}){return <div className="detailOverlay"><section className="card validationDetail"><header><h2>Detalle de validación</h2><button onClick={onClose}><X/></button></header><div className="detailColumns"><article><h3>Datos de carpeta</h3><p>Periodo: {file.period?.source==='FOLDER'?file.period.value:'—'}</p><p>Tomo: {file.tome?.source==='FOLDER'?file.tome.value:'—'}</p><p>Fojas: {file.folios?.source==='FOLDER'?file.folios.value:'—'}</p><p>Contratante: {file.contractor?.value??'—'}</p></article><article><h3>Nombre del archivo</h3><p>{file.originalName}</p><p>Kardex: {file.kardex?.source==='FILENAME'?file.kardex.value:'—'}</p></article><article><h3>Datos del Excel</h3><p>Filas relacionadas: {result.excelRowIds.length?result.excelRowIds.join(', '):'Ninguna'}</p><p>Acto jurídico: {result.legalAct||'Sin clasificar'}</p></article><article><h3>Resultado recomendado</h3><p>{result.status}</p>{result.conflicts.map(value=><p key={value}>Conflicto: {value}</p>)}{result.multipleContractors.length>1&&<p>Posible inconsistencia: se encontraron varios contratantes para el kardex {file.kardex?.value}.</p>}</article></div></section></div>}
function Pagination({page,total,onPage}:{page:number;total:number;onPage:(page:number)=>void}){const pages=Math.max(1,Math.ceil(total/PAGE_SIZE));return <div className="resultPagination"><span>{total} registros</span><div><button disabled={page<=1} onClick={()=>onPage(page-1)}><ChevronLeft/></button><b>{page} / {pages}</b><button disabled={page>=pages} onClick={()=>onPage(page+1)}><ChevronRight/></button></div></div>}
function formatBytes(bytes:number){if(!bytes)return'0 B';const units=['B','KB','MB','GB','TB'];const index=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),units.length-1);return`${(bytes/1024**index).toFixed(index?1:0)} ${units[index]}`}
function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)}
