import {useEffect,useRef,useState} from 'react';
import {ScanLine,Upload} from 'lucide-react';
import type {ScanConfiguration,ScanSession,ScanUiStatus} from '../domain/document-domain';
import {czurDesktop,type DetectedScanFile,type ScanStatusEvent} from '../services/czurDesktop';
import {scanWorkflowStore,useScanWorkflow,type AcquisitionStatus} from '../services/scanWorkflowStore';
import {isTauriEnvironment} from '../utils/environment';

const activeStatuses=new Set(['CZUR_OPENING','WAITING_FOR_SCAN','FILE_DETECTED','FILE_STABILIZING','COPYING','PREPROCESSING','READY_FOR_REVIEW']);

export function ScanAcquisition({config,ready,fileRef,onManualFile,onSession}:{config:ScanConfiguration;ready:boolean;fileRef:React.RefObject<HTMLInputElement|null>;onManualFile:(file?:File)=>void;onSession:(session:ScanSession)=>void}){
 const desktop=isTauriEnvironment();const workflow=useScanWorkflow();const [status,setStatus]=useState<ScanUiStatus>('IDLE');const [message,setMessage]=useState('');const processingRef=useRef(Promise.resolve());
 useEffect(()=>{if(!desktop)return;void czurDesktop.listSessions(0,100).then(sessions=>{const root=sessions.find(session=>session.sourceType==='CZUR'&&session.status==='WAITING_FOR_SCAN')??sessions.find(session=>session.sourceType&&activeStatuses.has(session.status));if(root)scanWorkflowStore.recoverAcquisition(root.sourceType!=='MANUAL'?'CZUR':'MANUAL',root.status==='READY_FOR_REVIEW'?'READY_FOR_PREVIEW':'WAITING_FOR_FILE',root.acquisitionId??root.id);const readySession=sessions.find(session=>session.status==='READY_FOR_REVIEW'&&session.pageCount>0);if(readySession&&root)onSession(readySession)}).catch(()=>undefined);let stop:(()=>void)|undefined;void czurDesktop.onStatus(handleEvent).then(value=>{stop=value;void czurDesktop.resumeQueue()});return()=>stop?.()},[desktop]);
 function newSession(sourceType:'CZUR'|'MANUAL',sessionStatus:ScanSession['status']='CREATED'):ScanSession{const id=crypto.randomUUID();return{id,sourceType,acquisitionId:id,documentClass:config.documentClass,registryTypeId:config.registryTypeId,tomeNumber:config.tomeNumber,folioQuantity:Number.isFinite(Number(config.folioQuantity))?Number(config.folioQuantity):0,year:Number(config.period.slice(0,4)),pageCount:0,status:sessionStatus,startedAt:new Date().toISOString(),pages:[]}}
 function acquisitionStatus(event:ScanStatusEvent):AcquisitionStatus{return event.status==='SCAN_DETECTED'?'FILE_DETECTED':event.status==='READY_FOR_REVIEW'?'READY_FOR_PREVIEW':event.status==='ERROR'?'FAILED':event.status==='WAITING_FOR_SCAN'?'WAITING_FOR_FILE':'PREPARING'}
 function handleEvent(event:ScanStatusEvent){setStatus(event.status);if(scanWorkflowStore.get().acquisitionMode==='CZUR')scanWorkflowStore.setAcquisitionStatus(acquisitionStatus(event));if(event.status==='SCAN_DETECTED')setMessage('PDF detectado. Preparando documento…');else if(event.status==='PREPARING_PAGES')setMessage('Preparando documento…');else if(event.status==='READY_FOR_REVIEW')setMessage('Abriendo Control previo…');if(event.file){const file=event.file;processingRef.current=processingRef.current.then(()=>prepare(event.sessionId,file)).catch(()=>undefined)}}
 async function prepare(sessionId:string,file:DetectedScanFile){try{const session=await czurDesktop.selectDetectedFile(sessionId,file.id);scanWorkflowStore.setAcquisitionStatus('READY_FOR_PREVIEW');onSession(session)}catch{const active=scanWorkflowStore.get();if(active.acquisitionSessionId)await czurDesktop.cancelSession(active.acquisitionSessionId,false).catch(()=>undefined);scanWorkflowStore.finishAcquisition('FAILED');setStatus('ERROR');setMessage('No se pudo preparar el PDF exportado. Inténtelo nuevamente.')}}
 async function scan(){const session=newSession('CZUR','CZUR_OPENING');if(!ready||!desktop||!scanWorkflowStore.beginAcquisition('CZUR',session.id))return;setStatus('CHECKING_CZUR');setMessage('Abriendo CZUR…');try{const configuration=await czurDesktop.detect();if(!configuration.executableConfigured||!configuration.exportFolderConfigured)throw new Error();await czurDesktop.startSession(session);scanWorkflowStore.setAcquisitionStatus('WAITING_FOR_FILE',session.id);await czurDesktop.open();setStatus('WAITING_FOR_SCAN');setMessage('Esperando el PDF exportado desde CZUR…')}catch{scanWorkflowStore.finishAcquisition('FAILED');setStatus('ERROR');setMessage('No se pudo iniciar CZUR. Inténtelo nuevamente.')}}
 async function manual(){if(!ready||!scanWorkflowStore.beginAcquisition('MANUAL'))return;if(!desktop){const release=()=>setTimeout(()=>{if(!fileRef.current?.files?.length&&scanWorkflowStore.get().acquisitionMode==='MANUAL')scanWorkflowStore.finishAcquisition('CANCELLED')},250);window.addEventListener('focus',release,{once:true});fileRef.current?.click();return}try{const session=newSession('MANUAL');scanWorkflowStore.setAcquisitionStatus('STARTING',session.id);const selected=await czurDesktop.selectManualFile(session);scanWorkflowStore.setAcquisitionStatus('READY_FOR_PREVIEW',selected.id);onSession(selected)}catch(error){const cancelled=String(error).toLowerCase().includes('cancel');scanWorkflowStore.finishAcquisition(cancelled?'CANCELLED':'FAILED');setStatus(cancelled?'IDLE':'ERROR');setMessage(cancelled?'':'No se pudo abrir el PDF seleccionado.')}}
 async function cancel(){if(workflow.acquisitionMode!=='CZUR'||!workflow.acquisitionSessionId||!window.confirm('¿Cancelar la espera del PDF de CZUR? CZUR permanecerá abierto.'))return;try{await czurDesktop.cancelSession(workflow.acquisitionSessionId,false)}finally{scanWorkflowStore.finishAcquisition('CANCELLED');setStatus('IDLE');setMessage('')}}
 const locked=workflow.acquisitionMode!=='IDLE';const waiting=workflow.acquisitionMode==='CZUR'&&['STARTING','WAITING_FOR_FILE','FILE_DETECTED','PREPARING'].includes(workflow.acquisitionStatus);
 return <section className="card uploadCard phaseOneUpload scanAcquisition"><div className="stepHeading"><span>2</span><h2 className="section-title">Escanear documento</h2></div><div className="uploadCenter"><div className="scanBox"><ScanLine size={31}/></div><h3>{desktop?'CZUR Scanner':'SIGADN en navegador'}</h3><p>{desktop?'Adquiera un documento con CZUR o seleccione un PDF manualmente.':'Las funciones nativas requieren SIGADN Desktop.'}</p><div className="scanButtons"><button type="button" className="btn primary" disabled={!ready||locked} aria-disabled={!ready||locked} onClick={scan}><ScanLine/>Escanear con CZUR</button><button type="button" className="btn" disabled={!ready||locked} aria-disabled={!ready||locked} onClick={()=>void manual()}><Upload/>Seleccionar PDF manualmente</button>{waiting&&<button type="button" className="btn" onClick={()=>void cancel()}>Cancelar</button>}<input ref={fileRef} hidden type="file" accept="application/pdf,.pdf" onChange={event=>{const selected=event.target.files?.[0];if(selected){scanWorkflowStore.setAcquisitionStatus('PREPARING');onManualFile(selected)}}}/></div>{message&&<small className={status==='ERROR'?'validationError':''}>{message}</small>}</div></section>;
}
