import {useEffect,useRef,useState} from 'react';
import {ScanLine,Upload} from 'lucide-react';
import type {ScanConfiguration,ScanSession,ScanUiStatus} from '../domain/document-domain';
import {czurDesktop,type DetectedScanFile,type ScanStatusEvent} from '../services/czurDesktop';
import {scanWorkflowStore,useScanWorkflow,type AcquisitionStatus} from '../services/scanWorkflowStore';
import {isTauriEnvironment} from '../utils/environment';
import {auditApi} from '../services/auditApi';
import {normalizedTomeNumber} from '../utils/tomeNumber';

export function ScanAcquisition({config,ready,fileRef,onManualFile,onSession}:{config:ScanConfiguration;ready:boolean;fileRef:React.RefObject<HTMLInputElement|null>;onManualFile:(file?:File)=>void;onSession:(session:ScanSession)=>void}){
 const desktop=isTauriEnvironment();const workflow=useScanWorkflow();const [status,setStatus]=useState<ScanUiStatus>('IDLE');const [message,setMessage]=useState('');const processingRef=useRef(Promise.resolve());const mountedRef=useRef(true);
 function newSession(sourceType:'CZUR'|'MANUAL',sessionStatus:ScanSession['status']='CREATED'):ScanSession{const id=crypto.randomUUID();const range=config.folioQuantity.trim().match(/^(\d+)\s*(?:-|–|al)\s*(\d+)$/i);const folioRangeStart=config.folioRangeStart??(range?Number(range[1]):undefined);const folioRangeEnd=config.folioRangeEnd??(range?Number(range[2]):undefined);const isBiennium=config.period.includes('-');return{id,sourceType,acquisitionId:id,documentClass:config.documentClass,registryTypeId:config.registryTypeId,registryType:config.registryTypeId,tomeNumber:normalizedTomeNumber(config.tomeNumber)??'',periodKey:config.period,periodType:isBiennium?'BIENNIUM':'YEAR',folioQuantity:Number.isFinite(Number(config.folioQuantity))?Number(config.folioQuantity):0,folioRangeStart,folioRangeEnd,year:isBiennium?undefined:Number(config.period),bienniumStart:isBiennium?Number(config.period.slice(0,4)):undefined,bienniumEnd:isBiennium?Number(config.period.slice(5)):undefined,pageCount:0,status:sessionStatus,startedAt:new Date().toISOString(),pages:[]}}
 function acquisitionStatus(event:ScanStatusEvent):AcquisitionStatus{return event.status==='SCAN_DETECTED'?'FILE_DETECTED':event.status==='READY_FOR_REVIEW'?'READY_FOR_PREVIEW':event.status==='ERROR'?'FAILED':event.status==='WAITING_FOR_SCAN'?'WAITING_FOR_FILE':'PREPARING'}
 function hasActiveCzur(){const active=scanWorkflowStore.get();return mountedRef.current&&active.acquisitionMode==='CZUR'&&Boolean(active.acquisitionSessionId)}
 function handleEvent(event:ScanStatusEvent){if(!hasActiveCzur())return;if(import.meta.env.DEV)console.debug('[UI] evento recibido');setStatus(event.status);scanWorkflowStore.setAcquisitionStatus(acquisitionStatus(event));if(event.status==='SCAN_DETECTED')setMessage('PDF detectado. Preparando documento…');else if(event.status==='PREPARING_PAGES')setMessage('Preparando documento…');else if(event.status==='READY_FOR_REVIEW')setMessage('Abriendo Control previo…');else if(event.status==='ERROR')setMessage(event.message||'No se pudo detectar el PDF exportado.');if(event.file){const file=event.file;processingRef.current=processingRef.current.then(()=>prepare(event.sessionId,file)).catch(()=>undefined)}}
 async function handleReady(event:{sessionId:string;sourceType:'CZUR'|'MANUAL'}){if(event.sourceType!=='CZUR'||!hasActiveCzur())return;try{const session=await czurDesktop.getSession(event.sessionId);if(!hasActiveCzur())return;if(import.meta.env.DEV){console.debug('[UI] sesión recuperada');console.debug(`[UI] páginas cargadas: ${session.pageCount}`);console.debug('[UI] Control previo abierto')}scanWorkflowStore.setAcquisitionStatus('READY_FOR_PREVIEW');onSession(session)}catch{if(hasActiveCzur()){scanWorkflowStore.finishAcquisition('FAILED');setStatus('ERROR');setMessage('No se pudo recuperar el PDF preparado.')}}}
 async function prepare(sessionId:string,file:DetectedScanFile){if(!hasActiveCzur())return;try{await czurDesktop.selectDetectedFile(sessionId,file.id)}catch{if(!hasActiveCzur())return;await czurDesktop.cancelSession(sessionId,false).catch(()=>undefined);scanWorkflowStore.finishAcquisition('FAILED');setStatus('ERROR');setMessage('No se pudo preparar el PDF exportado. Inténtelo nuevamente.')}}
 async function scan(){const session=newSession('CZUR','CZUR_OPENING');if(!ready||!desktop||!scanWorkflowStore.beginAcquisition('CZUR',session.id))return;if(import.meta.env.DEV)console.debug('[CZUR] sesión creada');setStatus('CHECKING_CZUR');setMessage('Abriendo CZUR…');try{const configuration=await czurDesktop.detect();if(!configuration.executableConfigured||!configuration.exportFolderConfigured)throw new Error();await czurDesktop.startSession(session);await auditApi.record('CZUR_SCAN_STARTED','Digitalización',`Sesión ${session.id.slice(0,8)}`);scanWorkflowStore.setAcquisitionStatus('WAITING_FOR_FILE',session.id);await czurDesktop.open();if(import.meta.env.DEV)console.debug('[CZUR] aplicación abierta');setStatus('WAITING_FOR_SCAN');setMessage('Esperando el PDF exportado desde CZUR…')}catch{scanWorkflowStore.finishAcquisition('FAILED');setStatus('ERROR');setMessage('No se pudo iniciar CZUR. Inténtelo nuevamente.')}}
 async function manual(){if(!ready||!scanWorkflowStore.beginAcquisition('MANUAL'))return;if(!desktop){const release=()=>setTimeout(()=>{if(!fileRef.current?.files?.length&&scanWorkflowStore.get().acquisitionMode==='MANUAL')scanWorkflowStore.finishAcquisition('CANCELLED')},250);window.addEventListener('focus',release,{once:true});fileRef.current?.click();return}try{const session=newSession('MANUAL');if(import.meta.env.DEV)console.debug('[MANUAL] sesión creada');scanWorkflowStore.setAcquisitionStatus('STARTING',session.id);const selected=await czurDesktop.selectManualFile(session);await auditApi.record('MANUAL_PDF_SELECTED','Digitalización',selected.originalFileName??'PDF manual');if(import.meta.env.DEV){console.debug('[MANUAL] PDF seleccionado');console.debug(`[MANUAL] páginas preparadas: ${selected.pageCount}`);console.debug('[MANUAL] Control previo abierto')}scanWorkflowStore.setAcquisitionStatus('READY_FOR_PREVIEW',selected.id);onSession(selected)}catch(error){const cancelled=String(error).toLowerCase().includes('cancel');scanWorkflowStore.finishAcquisition(cancelled?'CANCELLED':'FAILED');setStatus(cancelled?'IDLE':'ERROR');setMessage(cancelled?'':'No se pudo abrir el PDF seleccionado.')}}
 async function cancel(){if(workflow.acquisitionMode!=='CZUR'||!workflow.acquisitionSessionId||!window.confirm('¿Cancelar la espera del PDF de CZUR? CZUR permanecerá abierto.'))return;try{await czurDesktop.cancelSession(workflow.acquisitionSessionId,false)}finally{scanWorkflowStore.finishAcquisition('CANCELLED');setStatus('IDLE');setMessage('')}}
 // Los listeners se registran una vez por entorno de ejecución. Sus callbacks
 // consultan el store actual, por lo que no deben reinscribirse en cada render.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{mountedRef.current=true;if(!desktop)return()=>{mountedRef.current=false};const stops:(()=>void)[]=[];void Promise.all([czurDesktop.onStatus(handleEvent),czurDesktop.onReadyForPreview(handleReady)]).then(values=>{if(mountedRef.current)stops.push(...values);else values.forEach(stop=>stop())});return()=>{mountedRef.current=false;stops.forEach(stop=>stop())}},[desktop]);
 const locked=workflow.acquisitionMode!=='IDLE';const waiting=workflow.acquisitionMode==='CZUR'&&['STARTING','WAITING_FOR_FILE','FILE_DETECTED','PREPARING'].includes(workflow.acquisitionStatus);
 return <section className="card uploadCard phaseOneUpload scanAcquisition"><div className="stepHeading"><span>2</span><h2 className="section-title">Escanear documento</h2></div><div className="uploadCenter"><div className="scanBox"><ScanLine size={31}/></div><h3>{desktop?'CZUR Scanner':'Bóveda en navegador'}</h3><p>{desktop?'Adquiera un documento con CZUR o seleccione un PDF manualmente.':'Las funciones nativas requieren Bóveda Desktop.'}</p><div className="scanButtons"><button type="button" className="btn primary" disabled={!ready||locked} aria-disabled={!ready||locked} onClick={scan}><ScanLine/>Escanear con CZUR</button><button type="button" className="btn" disabled={!ready||locked} aria-disabled={!ready||locked} onClick={()=>void manual()}><Upload/>Seleccionar PDF manualmente</button>{waiting&&<button type="button" className="btn" onClick={()=>void cancel()}>Cancelar</button>}<input ref={fileRef} hidden type="file" accept="application/pdf,.pdf" onChange={event=>{const selected=event.target.files?.[0];if(selected){scanWorkflowStore.setAcquisitionStatus('PREPARING');onManualFile(selected)}}}/></div>{message&&<small className={status==='ERROR'?'validationError':''}>{message}</small>}</div></section>;
}
