import {useEffect,useMemo,useState} from 'react';
import {ArrowDown,ArrowUp,Columns2,CornerDownLeft,RotateCcw,RotateCw,ScanLine,Trash2,Undo2,X} from 'lucide-react';
import {generateTemporaryCleanPdf} from '../services/scanPdf';
type LocalPage={id:string;originalPageNumber:number;currentOrder:number;rotation:number;excluded:boolean};
export function ScanControlPreview({file,pages,onBack,onCancel,onContinue}:{file:File;pages:number;onBack:()=>void;onCancel:()=>void;onContinue:(clean:File)=>void}){
 const url=useMemo(()=>URL.createObjectURL(file),[file]);const [selected,setSelected]=useState(0);const [compare,setCompare]=useState(false);const [working,setWorking]=useState(false);const [cancelling,setCancelling]=useState(false);const [rows,setRows]=useState<LocalPage[]>(()=>Array.from({length:pages},(_,index)=>({id:crypto.randomUUID(),originalPageNumber:index+1,currentOrder:index,rotation:0,excluded:false})));
 useEffect(()=>()=>URL.revokeObjectURL(url),[url]);const active=rows[selected]??rows[0];const blocked=working||cancelling;
 function update(change:Partial<LocalPage>){setRows(current=>current.map((row,index)=>index===selected?{...row,...change}:row))}
 function move(delta:number){const target=selected+delta;if(target<0||target>=rows.length)return;setRows(current=>{const next=[...current];[next[selected],next[target]]=[next[target],next[selected]];return next.map((row,index)=>({...row,currentOrder:index}))});setSelected(target)}
 async function generate(){setWorking(true);try{const bytes=await generateTemporaryCleanPdf(file,rows);const buffer=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength) as ArrayBuffer;onContinue(new File([buffer],'document-clean.pdf',{type:'application/pdf'}))}finally{setWorking(false)}}
 function cancel(){if(!window.confirm('Cancelar documento\n\n¿Está seguro de que desea cancelar este documento? Los cambios realizados en el Control previo se perderán.'))return;setCancelling(true);onCancel()}
 return <section className="card qualityCard phaseThreePreview"><div className="stepHeading"><span>2</span><h2 className="section-title">Control previo</h2></div><p className="qualityFile">{file.name} · {rows.filter(row=>!row.excluded).length} de {pages} páginas</p><div className="phaseThreeLayout"><div className="qualityThumbs">{rows.map((row,index)=><button type="button" disabled={blocked} key={row.id} className={`qualityThumb ${index===selected?'active':''} ${row.excluded?'excluded':''}`} onClick={()=>setSelected(index)}><span>Página {row.originalPageNumber}</span><small>{row.excluded?'Eliminada':row.rotation?`${row.rotation}°`:'Lista'}</small></button>)}</div><div className={`qualityPreview comparison-${compare}`}><iframe title="Vista original del PDF" src={`${url}#page=${active?.originalPageNumber??1}`}/>{compare&&<iframe title="Vista procesada del PDF" src={`${url}#page=${active?.originalPageNumber??1}`}/>}</div><aside className="previewTools"><h3>Herramientas</h3><button type="button" className="btn" disabled={blocked} onClick={()=>update({rotation:(active.rotation+270)%360})}><RotateCcw/>Rotar izquierda</button><button type="button" className="btn" disabled={blocked} onClick={()=>update({rotation:(active.rotation+90)%360})}><RotateCw/>Rotar derecha</button><button type="button" className="btn" disabled><CornerDownLeft/>Ajustar esquinas</button><button type="button" className="btn" disabled><ScanLine/>Volver a detectar</button><button type="button" className="btn" disabled={blocked} onClick={()=>setCompare(value=>!value)}><Columns2/>Comparar original</button><button type="button" className="btn" disabled={blocked} onClick={()=>move(-1)}><ArrowUp/>Mover arriba</button><button type="button" className="btn" disabled={blocked} onClick={()=>move(1)}><ArrowDown/>Mover abajo</button><button type="button" className="btn" disabled={blocked} onClick={()=>update({excluded:!active.excluded})}>{active.excluded?<Undo2/>:<Trash2/>}{active.excluded?'Restaurar':'Eliminar página'}</button><button type="button" className="btn" disabled={blocked} onClick={()=>update({rotation:0,excluded:false})}><Undo2/>Restaurar cambios</button><small>El original permanece intacto. El PDF limpio se genera solo al continuar.</small></aside></div><footer className="qualityActions"><button type="button" className="btn" disabled={blocked} onClick={cancel}><X/>{cancelling?'Cancelando…':'Cancelar'}</button><button type="button" className="btn" disabled={blocked} onClick={onBack}>Regresar</button><button type="button" className="btn primary" disabled={blocked||rows.every(row=>row.excluded)} onClick={generate}>{working?'Generando PDF…':'Continuar'}</button></footer></section>
}
