import {useEffect,useRef,useState} from 'react';
import {ScanLine,Upload} from 'lucide-react';
import type {ScanConfiguration,ScanSession,ScanUiStatus} from '../domain/document-domain';
import {czurDesktop,type DetectedScanFile} from '../services/czurDesktop';
import {isTauriEnvironment} from '../utils/environment';

const labels:Record<ScanUiStatus,string>={IDLE:'Listo',CHECKING_CZUR:'Comprobando CZUR',OPENING_CZUR:'Abriendo CZUR',WAITING_FOR_SCAN:'Esperando escaneo',SCAN_DETECTED:'Escaneo detectado',RECEIVING_FILE:'Recibiendo archivo',PREPARING_PAGES:'Preparando páginas',READY_FOR_REVIEW:'Listo para revisión',ERROR:'Error'};
export function ScanAcquisition({config,ready,fileRef,onManualFile,onSession}:{config:ScanConfiguration;ready:boolean;fileRef:React.RefObject<HTMLInputElement|null>;onManualFile:(file?:File)=>void;onSession:(session:ScanSession)=>void}){
 const desktop=isTauriEnvironment(); const [status,setStatus]=useState<ScanUiStatus>('IDLE'); const [message,setMessage]=useState(''); const [session,setSession]=useState<ScanSession>(); const [detected,setDetected]=useState<DetectedScanFile[]>([]); const receivingRef=useRef(false);
 useEffect(()=>{if(!desktop)return;let stop:(()=>void)|undefined;void czurDesktop.onStatus(e=>{if(session&&e.sessionId!==session.id)return;setStatus(e.status);setMessage(e.message);if(e.file){setDetected([e.file]);if(session&&!receivingRef.current)void choose(e.file)}}).then(v=>{stop=v});return()=>stop?.()},[desktop,session]);
 function newSession(status:ScanSession['status']='CREATED'):ScanSession{return{id:crypto.randomUUID(),documentClass:config.documentClass,registryTypeId:config.registryTypeId,tomeNumber:config.tomeNumber,folioQuantity:Number.isFinite(Number(config.folioQuantity))?Number(config.folioQuantity):0,year:Number(config.period.slice(0,4)),pageCount:0,status,startedAt:new Date().toISOString(),pages:[]}}
 async function scan(){if(!ready||!desktop)return;try{setStatus('CHECKING_CZUR');setMessage('Buscando CZUR Scanner…');const c=await czurDesktop.detect();if(!c.executableConfigured){setStatus('ERROR');setMessage('CZUR Scanner no fue encontrado en este equipo.');return}if(!c.exportFolderConfigured){setStatus('ERROR');setMessage('Configure CZUR para exportar en la carpeta definida para SIGADN.');return}const next=newSession('CZUR_OPENING');setSession(next);await czurDesktop.startSession(next);setStatus('OPENING_CZUR');setMessage('Abriendo CZUR Scanner…');await czurDesktop.open();setStatus('WAITING_FOR_SCAN');setMessage('CZUR Scanner se abrió. Exporte el documento como PDF; SIGADN lo mostrará automáticamente.')}catch(e){setStatus('ERROR');setMessage(e instanceof Error?e.message:String(e))}}
 async function manual(){if(!ready)return;if(!desktop){fileRef.current?.click();return}try{setStatus('RECEIVING_FILE');setMessage('Seleccione el PDF que desea visualizar.');const next=newSession();setSession(next);const updated=await czurDesktop.selectManualFile(next);setSession(updated);onSession(updated)}catch(e){const value=e instanceof Error?e.message:String(e);if(value.toLowerCase().includes('cancel')){setStatus('IDLE');setMessage('Selección cancelada.')}else{setStatus('ERROR');setMessage(value)}}}
 async function choose(file:DetectedScanFile){if(!session||receivingRef.current)return;receivingRef.current=true;try{setStatus('RECEIVING_FILE');setMessage(`Preparando ${file.displayName}…`);const updated=await czurDesktop.selectDetectedFile(session.id,file.id);setSession(updated);onSession(updated)}catch(e){receivingRef.current=false;setStatus('ERROR');setMessage(e instanceof Error?e.message:String(e))}}
 return <section className="card uploadCard phaseOneUpload scanAcquisition"><div className="stepHeading"><span>2</span><h2 className="section-title">Escanear documento</h2></div><div className="uploadCenter"><div className="scanBox"><ScanLine size={31}/></div><h3>{desktop?'CZUR Scanner':'SIGADN en navegador'}</h3><p>{desktop?'Adquiera un documento con CZUR o seleccione un PDF manualmente.':'Las funciones nativas requieren SIGADN Desktop.'}</p><div className="scanButtons"><button type="button" className="btn primary" disabled={!ready} onClick={scan}><ScanLine/>Escanear con CZUR</button><button type="button" className="btn" disabled={!ready} onClick={()=>void manual()}><Upload/>Seleccionar PDF manualmente</button><input ref={fileRef} hidden type="file" accept="application/pdf,.pdf" onChange={e=>onManualFile(e.target.files?.[0])}/></div><div className={`scanStatus ${status.toLowerCase()}`}><b>{labels[status]}</b><span>{message||'Complete la configuración mínima para comenzar.'}</span></div>{detected[0]&&<div className="detectedScans"><b>PDF más reciente</b><button type="button" disabled={receivingRef.current} onClick={()=>void choose(detected[0])}><span>{detected[0].displayName}</span><small>{detected[0].pageCount} páginas</small></button></div>}</div></section>;
}
