use chrono::{DateTime,Utc};
use notify::{EventKind,RecommendedWatcher,RecursiveMode,Watcher};
use serde::{Deserialize,Serialize};
use std::{collections::{HashMap,HashSet},fs,path::{Path,PathBuf},process::Command,sync::{Arc,Mutex},thread,time::Duration};
use tauri::{AppHandle,Emitter,Manager,State};
use tauri_plugin_dialog::DialogExt;
use uuid::Uuid;

#[derive(Default)]
struct DesktopState{watcher:Mutex<Option<RecommendedWatcher>>,processed:Arc<Mutex<HashSet<PathBuf>>>,detected:Arc<Mutex<HashMap<String,PathBuf>>>}

#[derive(Clone,Serialize,Deserialize,Default)]
#[serde(rename_all="camelCase")]
struct CzurConfiguration{
  executable_path:Option<PathBuf>,export_folder:Option<PathBuf>,temporary_folder:Option<PathBuf>,
  last_checked_at:Option<DateTime<Utc>>,detected_version:Option<String>,launch_type:Option<String>,shortcut_path:Option<PathBuf>,validation_status:Option<String>
}
#[derive(Serialize)]
#[serde(rename_all="camelCase")]
struct PublicCzurConfiguration{
  executable_configured:bool,export_folder_configured:bool,temporary_folder_configured:bool,
  executable_display_name:Option<String>,export_folder_display_name:Option<String>,temporary_folder_display_name:Option<String>,
  last_checked_at:Option<DateTime<Utc>>,detected_version:Option<String>,valid:bool,issues:Vec<String>
}
#[derive(Clone,Serialize,Deserialize)]
#[serde(rename_all="camelCase")]
struct ScanPage{
  id:String,original_page_number:u32,current_order:u32,width:u32,height:u32,resolution:u32,rotation:i32,excluded:bool,
  original_preview_url:String,processed_preview_url:String,detected_corners:Option<serde_json::Value>,crop_confidence:Option<f32>,
  perspective_applied:bool,requires_manual_review:bool,transformations:Vec<String>
}
#[derive(Clone,Serialize,Deserialize)]
#[serde(rename_all="camelCase")]
struct ScanSession{
  id:String,document_class:String,registry_type_id:String,tome_number:String,folio_quantity:u32,year:Option<u32>,
  biennium_start:Option<u32>,biennium_end:Option<u32>,started_at:String,czur_opened_at:Option<String>,
  detected_file_path:Option<String>,temporary_copy_path:Option<String>,original_file_name:Option<String>,
  clean_pdf_path:Option<String>,page_count:u32,status:String,error:Option<String>,pages:Vec<ScanPage>
}
#[derive(Clone,Serialize)]
#[serde(rename_all="camelCase")]
struct ScanStatusEvent{session_id:String,status:String,message:String,file:Option<DetectedScanFile>}
#[derive(Clone,Serialize)]
#[serde(rename_all="camelCase")]
struct DetectedScanFile{id:String,display_name:String,size:u64,page_count:u32,detected_at:String,kind:String}

fn config_path(app:&AppHandle)->Result<PathBuf,String>{app.path().app_config_dir().map(|path|path.join("czur-station.json")).map_err(|error|error.to_string())}
fn sessions_dir(app:&AppHandle)->Result<PathBuf,String>{app.path().app_cache_dir().map(|path|path.join("scan-sessions")).map_err(|error|error.to_string())}
fn configured_export_folder()->Option<PathBuf>{
  [option_env!("CZUR_EXPORT_FOLDER"),option_env!("VITE_CZUR_EXPORT_FOLDER")].into_iter().flatten().map(PathBuf::from).find(|path|path.is_dir()&&!dangerous_folder(path))
    .or_else(||std::env::var("CZUR_EXPORT_FOLDER").ok().or_else(||std::env::var("VITE_CZUR_EXPORT_FOLDER").ok()).or_else(||std::env::var("carpeta").ok()).map(PathBuf::from).filter(|path|path.is_dir()&&!dangerous_folder(path)))
}
fn sanitize_config(mut config:CzurConfiguration)->CzurConfiguration{if config.executable_path.as_deref().is_some_and(|path|!validate_executable(path)){config.executable_path=None}if config.export_folder.as_deref().is_some_and(|path|path.file_name().is_some_and(|name|name.to_string_lossy().eq_ignore_ascii_case("vehicular"))){config.export_folder=None}if let Some(environment_folder)=configured_export_folder(){config.export_folder=Some(environment_folder)}config}
fn read_config(app:&AppHandle)->CzurConfiguration{sanitize_config(config_path(app).ok().and_then(|path|fs::read(path).ok()).and_then(|bytes|serde_json::from_slice(&bytes).ok()).unwrap_or_default())}
fn save_config(app:&AppHandle,config:&CzurConfiguration)->Result<(),String>{let path=config_path(app)?;if let Some(parent)=path.parent(){fs::create_dir_all(parent).map_err(|error|error.to_string())?}fs::write(path,serde_json::to_vec_pretty(config).map_err(|error|error.to_string())?).map_err(|error|error.to_string())}
fn safe_display(path:&Path)->Option<String>{path.file_name().map(|name|name.to_string_lossy().to_string())}
fn validate_executable(path:&Path)->bool{let name=path.file_name().map(|n|n.to_string_lossy().to_lowercase()).unwrap_or_default();path.is_file()&&path.extension().is_some_and(|ext|ext.eq_ignore_ascii_case("exe"))&&name.contains("czur")&&!(["setup","installer","install","uninstall","updater","update","unins"].iter().any(|bad|name.contains(bad)))}
fn allowed_scan_file(path:&Path)->bool{path.extension().is_some_and(|extension|["pdf","jpg","jpeg","png","tif","tiff"].iter().any(|value|extension.eq_ignore_ascii_case(value)))}
fn dangerous_folder(path:&Path)->bool{let value=path.to_string_lossy().to_lowercase();["c:\\windows","c:\\program files","c:\\program files (x86)"].iter().any(|root|value.trim_end_matches('\\')==*root)}
fn public_config(config:&CzurConfiguration)->PublicCzurConfiguration{let mut issues=Vec::new();if !config.executable_path.as_deref().is_some_and(validate_executable){issues.push("CZUR Scanner no fue detectado.".into())}if !config.export_folder.as_deref().is_some_and(|path|path.is_dir()&&!dangerous_folder(path)){issues.push("La carpeta de exportación no está configurada o no es segura.".into())}if !config.temporary_folder.as_deref().is_some_and(|path|path.is_dir()||fs::create_dir_all(path).is_ok()){issues.push("La carpeta temporal no está disponible.".into())}PublicCzurConfiguration{executable_configured:config.executable_path.is_some(),export_folder_configured:config.export_folder.is_some(),temporary_folder_configured:config.temporary_folder.is_some(),executable_display_name:config.executable_path.as_deref().and_then(safe_display),export_folder_display_name:config.export_folder.as_deref().and_then(safe_display),temporary_folder_display_name:config.temporary_folder.as_deref().and_then(safe_display),last_checked_at:config.last_checked_at,detected_version:config.detected_version.clone(),valid:issues.is_empty(),issues}}
fn resolve_shortcut(path:&Path)->Option<PathBuf>{let script=format!("$s=(New-Object -ComObject WScript.Shell).CreateShortcut('{}');$s.TargetPath",path.display().to_string().replace("'","''"));let output=Command::new("powershell").args(["-NoProfile","-NonInteractive","-Command",&script]).output().ok()?;let target=String::from_utf8_lossy(&output.stdout).trim().to_string();let candidate=PathBuf::from(target);candidate.is_file().then_some(candidate)}
fn find_czur()->Option<PathBuf>{let mut candidates=Vec::new();for root in [std::env::var_os("ProgramFiles"),std::env::var_os("ProgramFiles(x86)")].into_iter().flatten(){for entry in walkdir::WalkDir::new(root).max_depth(5).into_iter().filter_map(Result::ok){let path=entry.path();if validate_executable(path){candidates.push(path.to_path_buf())}}}for folder in [std::env::var("PUBLIC").ok().map(|v|PathBuf::from(v).join("Desktop")),std::env::var("USERPROFILE").ok().map(|v|PathBuf::from(v).join("Desktop"))].into_iter().flatten(){if let Ok(entries)=fs::read_dir(folder){for entry in entries.flatten(){let path=entry.path();if path.extension().is_some_and(|e|e.eq_ignore_ascii_case("lnk"))&&path.file_stem().is_some_and(|n|n.to_string_lossy().to_lowercase().contains("czur")){if let Some(target)=resolve_shortcut(&path){if validate_executable(&target){return Some(target)}}}}}}candidates.into_iter().next()}
fn page_count(path:&Path)->Result<u32,String>{let document=lopdf::Document::load(path).map_err(|error|error.to_string())?;let count=document.get_pages().len() as u32;if count==0{Err("El PDF no contiene páginas.".into())}else{Ok(count)}}
fn stable_pdf(path:&Path)->Result<(u64,u32),String>{let mut previous=0;for _ in 0..5{let size=fs::metadata(path).map_err(|error|error.to_string())?.len();if size>0&&size==previous{return Ok((size,page_count(path)?))}previous=size;thread::sleep(Duration::from_millis(900))}Err("El archivo todavía se está escribiendo.".into())}
fn session_path(app:&AppHandle,id:&str)->Result<PathBuf,String>{Ok(sessions_dir(app)?.join(id).join("session.json"))}
fn save_session(app:&AppHandle,session:&ScanSession)->Result<(),String>{let path=session_path(app,&session.id)?;if let Some(parent)=path.parent(){fs::create_dir_all(parent).map_err(|error|error.to_string())?}fs::write(path,serde_json::to_vec_pretty(session).map_err(|error|error.to_string())?).map_err(|error|error.to_string())}
fn vision_dir(app:&AppHandle)->Result<PathBuf,String>{let resource=app.path().resource_dir().map_err(|error|error.to_string())?.join("vision");if resource.is_dir(){return Ok(resource)}let development=PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("vision");if development.is_dir(){return Ok(development)}Err("VISION_NOT_FOUND: no existe el directorio vision".into())}
fn python_path(app:&AppHandle)->Result<PathBuf,String>{let vision=vision_dir(app)?;let candidates=[vision.join(".venv/Scripts/python.exe"),vision.join(".venv/bin/python")];candidates.into_iter().find(|path|path.is_file()).ok_or_else(||format!("VENV_NOT_FOUND: no existe el intérprete Python en {}",vision.join(".venv").display()))}
fn script_path(app:&AppHandle)->Result<PathBuf,String>{let script=vision_dir(app)?.join("processor.py");if script.is_file(){Ok(script)}else{Err(format!("PROCESSOR_NOT_FOUND: no existe {}",script.display()))}}
fn run_processor(app:&AppHandle,source:&Path,session_dir:&Path)->Result<serde_json::Value,String>{let python=python_path(app)?;let script=script_path(app)?;let output=Command::new(python).args([script.to_string_lossy().as_ref(),"preprocess","--source",source.to_string_lossy().as_ref(),"--session",session_dir.to_string_lossy().as_ref()]).output().map_err(|error|format!("PYTHON_NOT_FOUND: {error}"))?;if !output.status.success(){return Err(format!("PYTHON_PROCESS_FAILED: {}",String::from_utf8_lossy(&output.stderr)))}serde_json::from_slice(&output.stdout).map_err(|error|format!("PYTHON_INVALID_JSON: {error}"))}
fn run_clean_pdf(app:&AppHandle,session_dir:&Path)->Result<serde_json::Value,String>{let python=python_path(app)?;let script=script_path(app)?;let output=Command::new(python).args([script.to_string_lossy().as_ref(),"generate_clean_pdf","--source",session_dir.join("original/scan-original.pdf").to_string_lossy().as_ref(),"--session",session_dir.to_string_lossy().as_ref()]).output().map_err(|error|format!("PYTHON_NOT_FOUND: {error}"))?;if !output.status.success(){return Err(format!("CLEAN_PDF_FAILED: {}",String::from_utf8_lossy(&output.stderr)))}serde_json::from_slice(&output.stdout).map_err(|error|format!("PYTHON_INVALID_JSON: {error}"))}

#[tauri::command] fn get_czur_configuration(app:AppHandle)->PublicCzurConfiguration{let config=read_config(&app);let _=save_config(&app,&config);public_config(&config)}
#[tauri::command] fn reset_czur_configuration(app:AppHandle)->Result<PublicCzurConfiguration,String>{let mut config=read_config(&app);config.executable_path=None;config.export_folder=None;config.detected_version=None;config.last_checked_at=None;save_config(&app,&config)?;Ok(public_config(&config))}
#[tauri::command] fn validate_czur_configuration(app:AppHandle)->Result<PublicCzurConfiguration,String>{let mut config=read_config(&app);config.last_checked_at=Some(Utc::now());save_config(&app,&config)?;Ok(public_config(&config))}
#[tauri::command] fn detect_czur_scanner(app:AppHandle)->Result<PublicCzurConfiguration,String>{let mut config=read_config(&app);if !config.executable_path.as_deref().is_some_and(validate_executable){config.executable_path=find_czur()}if config.temporary_folder.is_none(){config.temporary_folder=Some(sessions_dir(&app)?)}config.last_checked_at=Some(Utc::now());save_config(&app,&config)?;Ok(public_config(&config))}
#[tauri::command] fn configure_czur_executable(app:AppHandle)->Result<PublicCzurConfiguration,String>{let selected=app.dialog().file().add_filter("CZUR Scanner",&["exe"]).blocking_pick_file().and_then(|value|value.as_path().map(PathBuf::from)).ok_or("Selección cancelada.")?;if !validate_executable(&selected){return Err("La aplicación seleccionada no corresponde a CZUR.".into())}let mut config=read_config(&app);config.executable_path=Some(selected);config.last_checked_at=Some(Utc::now());save_config(&app,&config)?;Ok(public_config(&config))}
#[tauri::command] fn configure_czur_export_folder(app:AppHandle)->Result<PublicCzurConfiguration,String>{let selected=app.dialog().file().blocking_pick_folder().and_then(|value|value.as_path().map(PathBuf::from)).ok_or("Selección cancelada.")?;if dangerous_folder(&selected){return Err("No se permite usar una carpeta crítica del sistema.".into())}fs::read_dir(&selected).map_err(|_|"La carpeta no se puede leer.")?;let mut config=read_config(&app);config.export_folder=Some(selected);config.last_checked_at=Some(Utc::now());save_config(&app,&config)?;Ok(public_config(&config))}
#[tauri::command] fn open_czur_scanner(app:AppHandle)->Result<serde_json::Value,String>{let config=read_config(&app);let executable=config.executable_path.filter(|path|validate_executable(path)).ok_or("CZUR Scanner no fue detectado.")?;Command::new(executable).spawn().map_err(|error|error.to_string())?;Ok(serde_json::json!({"openedAt":Utc::now()}))}
#[tauri::command] fn start_scan_session(app:AppHandle,state:State<DesktopState>,mut session:ScanSession)->Result<ScanSession,String>{let config=read_config(&app);let folder=config.export_folder.ok_or("Configure la carpeta de exportación de CZUR.")?;session.status="WAITING_FOR_SCAN".into();save_session(&app,&session)?;if let Ok(mut set)=state.processed.lock(){set.clear()}if let Ok(mut files)=state.detected.lock(){files.clear()}let session_id=session.id.clone();let emitted_app=app.clone();let processed=state.processed.clone();let detected=state.detected.clone();let mut watcher=notify::recommended_watcher(move|event:Result<notify::Event,notify::Error>|{if let Ok(event)=event{if !matches!(event.kind,EventKind::Create(_)|EventKind::Modify(_)){return}for path in event.paths{if !allowed_scan_file(&path){continue}let reserved=processed.lock().is_ok_and(|mut set|set.insert(path.clone()));if !reserved{continue}let app=emitted_app.clone();let id=session_id.clone();let processed=processed.clone();let detected=detected.clone();thread::spawn(move||{if path.extension().is_some_and(|extension|extension.eq_ignore_ascii_case("pdf")){if let Ok((size,pages))=stable_pdf(&path){let file_id=Uuid::new_v4().to_string();if let Ok(mut files)=detected.lock(){files.clear();files.insert(file_id.clone(),path.clone());}let file=DetectedScanFile{id:file_id,display_name:path.file_name().unwrap_or_default().to_string_lossy().to_string(),size,page_count:pages,detected_at:Utc::now().to_rfc3339(),kind:"PDF".into()};if let Some(window)=app.get_webview_window("main"){let _=window.show();let _=window.set_focus();}let _=app.emit("scan-session-status",ScanStatusEvent{session_id:id,status:"SCAN_DETECTED".into(),message:"PDF más reciente detectado. Preparando vista previa…".into(),file:Some(file)});return}}if let Ok(mut set)=processed.lock(){set.remove(&path);}});}}}).map_err(|error|error.to_string())?;watcher.watch(&folder,RecursiveMode::Recursive).map_err(|error|error.to_string())?;*state.watcher.lock().map_err(|_|"No se pudo iniciar la vigilancia.")?=Some(watcher);Ok(session)}
#[tauri::command] fn select_scan_file(app:AppHandle,state:State<DesktopState>,session_id:String,file_id:String)->Result<ScanSession,String>{let source=state.detected.lock().map_err(|_|"No se pudo resolver el archivo detectado.")?.get(&file_id).cloned().ok_or("El archivo detectado ya no está disponible.")?;if !allowed_scan_file(&source)||!source.is_file(){return Err("PDF_INVALID: el archivo detectado no es válido.".into())}let session_file=session_path(&app,&session_id)?;let mut session:ScanSession=serde_json::from_slice(&fs::read(&session_file).map_err(|error|error.to_string())?).map_err(|error|error.to_string())?;let base=sessions_dir(&app)?.join(format!("scan-session-{session_id}"));let original=base.join("original");let pages=base.join("pages");let output=base.join("output");for dir in [&original,&pages.join("original"),&pages.join("processed"),&output]{fs::create_dir_all(dir).map_err(|error|format!("TEMP_COPY_FAILED: {error}"))?}let copied=original.join("scan-original.pdf");fs::copy(&source,&copied).map_err(|error|format!("TEMP_COPY_FAILED: {error}"))?;let result=run_processor(&app,&copied,&base)?;session.detected_file_path=Some(source.to_string_lossy().to_string());session.temporary_copy_path=Some(copied.to_string_lossy().to_string());session.original_file_name=source.file_name().map(|name|name.to_string_lossy().to_string());session.page_count=result.get("pageCount").and_then(serde_json::Value::as_u64).unwrap_or(0) as u32;session.pages=serde_json::from_value(result.get("pages").cloned().unwrap_or_default()).map_err(|error|format!("PDF_RENDER_FAILED: {error}"))?;session.status="READY_FOR_REVIEW".into();session.error=None;save_session(&app,&session)?;Ok(session)}
#[tauri::command] fn select_manual_scan_file(app:AppHandle,state:State<DesktopState>,session:ScanSession)->Result<ScanSession,String>{save_session(&app,&session)?;let selected=app.dialog().file().add_filter("PDF",&["pdf"]).blocking_pick_file().and_then(|value|value.as_path().map(PathBuf::from)).ok_or("Selección cancelada.")?;if !selected.is_file()||!selected.extension().is_some_and(|ext|ext.eq_ignore_ascii_case("pdf")){return Err("PDF_INVALID: seleccione un PDF válido.".into())}let file_id=Uuid::new_v4().to_string();state.detected.lock().map_err(|_|"No se pudo registrar el archivo seleccionado.")?.insert(file_id.clone(),selected);select_scan_file(app,state,session.id,file_id)}
#[tauri::command] fn read_scan_asset(app:AppHandle,session_id:String,page_id:String,variant:String)->Result<Vec<u8>,String>{if variant!="original"&&variant!="processed"{return Err("ASSET_VARIANT_INVALID".into())}let session:ScanSession=serde_json::from_slice(&fs::read(session_path(&app,&session_id)?).map_err(|e|e.to_string())?).map_err(|e|e.to_string())?;let page=session.pages.iter().find(|p|p.id==page_id).ok_or("PAGE_NOT_FOUND")?;let base=sessions_dir(&app)?.join(format!("scan-session-{session_id}"));let path=base.join("pages").join(&variant).join(format!("page-{:04}.png",page.original_page_number));let canonical_base=fs::canonicalize(&base).map_err(|e|e.to_string())?;let canonical=fs::canonicalize(&path).map_err(|e|e.to_string())?;if !canonical.starts_with(&canonical_base){return Err("ASSET_PATH_INVALID".into())}fs::read(canonical).map_err(|e|e.to_string())}
#[tauri::command] fn read_scan_original(app:AppHandle,session_id:String)->Result<Vec<u8>,String>{let base=sessions_dir(&app)?.join(format!("scan-session-{session_id}"));let path=base.join("original/scan-original.pdf");let canonical_base=fs::canonicalize(&base).map_err(|e|e.to_string())?;let canonical=fs::canonicalize(&path).map_err(|_|"SCAN_ORIGINAL_NOT_FOUND".to_string())?;if !canonical.starts_with(&canonical_base){return Err("SCAN_ORIGINAL_OUTSIDE_TEMP_DIRECTORY".into())}fs::read(canonical).map_err(|e|e.to_string())}
#[tauri::command] fn update_scan_pages(app:AppHandle,session_id:String,pages:Vec<ScanPage>)->Result<ScanSession,String>{let path=session_path(&app,&session_id)?;let mut session:ScanSession=serde_json::from_slice(&fs::read(path).map_err(|error|error.to_string())?).map_err(|error|error.to_string())?;session.pages=pages;save_session(&app,&session)?;Ok(session)}
#[tauri::command] fn rotate_scan_page(app:AppHandle,session_id:String,page_id:String,degrees:i32)->Result<ScanSession,String>{let path=session_path(&app,&session_id)?;let mut session:ScanSession=serde_json::from_slice(&fs::read(path).map_err(|error|error.to_string())?).map_err(|error|error.to_string())?;if let Some(page)=session.pages.iter_mut().find(|page|page.id==page_id){page.rotation=(page.rotation+degrees).rem_euclid(360);page.transformations.push(format!("ROTATE_{degrees}"))}save_session(&app,&session)?;Ok(session)}
#[tauri::command] fn adjust_scan_page_corners(_app:AppHandle,_session_id:String,_page_id:String,_corners:serde_json::Value)->Result<ScanSession,String>{Err("El ajuste de perspectiva requiere el servicio local OpenCV.".into())}
#[tauri::command] fn use_original_scan_page(app:AppHandle,session_id:String,page_id:String)->Result<ScanSession,String>{rotate_scan_page(app,session_id,page_id,0)}
#[tauri::command] fn redetect_scan_page(_app:AppHandle,_session_id:String,_page_id:String)->Result<ScanSession,String>{Err("La redetección requiere el servicio local OpenCV.".into())}
#[tauri::command] fn generate_clean_pdf(app:AppHandle,session_id:String)->Result<ScanSession,String>{let path=session_path(&app,&session_id)?;let mut session:ScanSession=serde_json::from_slice(&fs::read(&path).map_err(|error|error.to_string())?).map_err(|error|error.to_string())?;let base=sessions_dir(&app)?.join(format!("scan-session-{session_id}"));let result=run_clean_pdf(&app,&base)?;session.clean_pdf_path=result.get("cleanPdf").and_then(serde_json::Value::as_str).map(String::from);session.status="READY_FOR_REVIEW".into();save_session(&app,&session)?;Ok(session)}
#[tauri::command] fn cancel_scan_session(app:AppHandle,state:State<DesktopState>,session_id:String,remove_temporary:bool)->Result<(),String>{*state.watcher.lock().map_err(|_|"No se pudo detener la vigilancia.")?=None;if remove_temporary{let path=sessions_dir(&app)?.join(session_id);if path.exists(){fs::remove_dir_all(path).map_err(|error|error.to_string())?}}Ok(())}
#[tauri::command] fn recover_scan_sessions(app:AppHandle)->Result<Vec<ScanSession>,String>{let root=sessions_dir(&app)?;if !root.exists(){return Ok(Vec::new())}let mut sessions=Vec::new();for entry in fs::read_dir(root).map_err(|error|error.to_string())?.flatten(){let path=entry.path().join("session.json");if let Ok(bytes)=fs::read(path){if let Ok(session)=serde_json::from_slice::<ScanSession>(&bytes){if !["CANCELLED","FAILED"].contains(&session.status.as_str()){sessions.push(session)}}}}Ok(sessions)}

#[tauri::command] fn read_clean_pdf(app:AppHandle,session_id:String)->Result<Vec<u8>,String>{let session:ScanSession=serde_json::from_slice(&fs::read(session_path(&app,&session_id)?).map_err(|e|e.to_string())?).map_err(|e|e.to_string())?;let path=session.clean_pdf_path.ok_or("CLEAN_PDF_NOT_FOUND")?;let canonical=fs::canonicalize(&path).map_err(|_|"CLEAN_PDF_NOT_FOUND".to_string())?;let base=fs::canonicalize(sessions_dir(&app)?.join(format!("scan-session-{session_id}"))).map_err(|e|e.to_string())?;if !canonical.starts_with(&base){return Err("CLEAN_PDF_OUTSIDE_TEMP_DIRECTORY".into())}fs::read(canonical).map_err(|e|e.to_string())}
#[cfg_attr(mobile,tauri::mobile_entry_point)]
pub fn run(){tauri::Builder::default().manage(DesktopState::default()).plugin(tauri_plugin_dialog::init()).invoke_handler(tauri::generate_handler![get_czur_configuration,reset_czur_configuration,validate_czur_configuration,detect_czur_scanner,configure_czur_executable,configure_czur_export_folder,open_czur_scanner,start_scan_session,select_scan_file,select_manual_scan_file,read_scan_asset,read_scan_original,read_clean_pdf,update_scan_pages,rotate_scan_page,adjust_scan_page_corners,use_original_scan_page,redetect_scan_page,generate_clean_pdf,cancel_scan_session,recover_scan_sessions]).run(tauri::generate_context!()).expect("error al iniciar SIGADN Desktop")}

#[cfg(test)]
mod tests{
  use super::*;
  #[test] fn only_document_scan_extensions_are_allowed(){assert!(allowed_scan_file(Path::new("scan.PDF")));assert!(allowed_scan_file(Path::new("page.tiff")));assert!(!allowed_scan_file(Path::new("malware.exe")));assert!(!allowed_scan_file(Path::new("partial.pdf.tmp")))}
  #[test] fn system_roots_are_rejected(){assert!(dangerous_folder(Path::new(r"C:\Windows")));assert!(dangerous_folder(Path::new(r"C:\Program Files")));assert!(!dangerous_folder(Path::new(r"C:\SIGADN\EntradaCZUR")))}
}
