import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './App';
import {AuthProvider} from './auth/AuthContext';
import './styles/global.css';
import './styles/role.css';
import './styles/interactions.css';
import './styles/doc-interactions.css';
import './styles/tomo-interactions.css';
import './styles/audit-interactions.css';
import './styles/layout-interactions.css';
import './styles/real-viewer.css';
import './styles/real-dashboard.css';
import './styles/real-tomos.css';
import './styles/historical-documents.css';
import './styles/historical-table.css';
import './styles/digitalization-workflow.css';
import './styles/sidebar-profile.css';
import './styles/gestion-documental.css';
import './styles/viewer-ai.css';
import './styles/profile-runtime.css';
import './styles/auth-runtime.css';
import './styles/assistant-no-history.css';
import './styles/responsive.css';
import './styles/profile-clean.css';
import './styles/digitalizacion-quality.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><AuthProvider><App /></AuthProvider></BrowserRouter></React.StrictMode>);
